/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import <XXUnknownSuperclass.h> // Unknown library

@class UITextField;

__attribute__((visibility("hidden")))
@interface CBLTextEntryCell : NSObject { //XXUnknownSuperclass {
	UITextField* _textField;
	float _textFieldLeftInset;
}
@property(assign, nonatomic) float textFieldLeftInset;
@property(retain, nonatomic) UITextField* textField;
//-(void).cxx_destruct;
-(void)layoutSubviews;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

