/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:24 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/Message.framework/Message
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol MFLibraryContentIndexDataSource <NSObject>
@required
-(id)itemsRequiringIndexingForContentIndex:(id)arg1 limit:(unsigned)arg2;
-(void)contentIndex:(id)arg1 assignTransactionIdentifier:(unsigned)arg2 forDocumentIdentifiers:(id)arg3;
-(void)contentIndex:(id)arg1 invalidateItemsGreaterThanTransactionId:(unsigned)arg2;

@end

