/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "PHFrecentResultViewController.h"

//#import "ABUnknownPersonViewControllerDelegate-Protocol.h"
//#import "PHAddressBookControllerDelegate-Protocol.h"
//#import "PHFrecentResultViewControllerDelegate-Protocol.h"
//#import "UISearchControllerDelegate-Protocol.h"

@class NSMutableArray, NSString, PHFrecentNoContentView, UIBarButtonItem, UISearchController, UISegmentedControl;
/*
@interface PHFrecentViewController : PHFrecentResultViewController <UISearchControllerDelegate, PHFrecentResultViewControllerDelegate, PHAddressBookControllerDelegate, ABUnknownPersonViewControllerDelegate>
{
    _Bool _isSwipeToDelete;
    NSMutableArray *_recentCalls;
    id <PHSearchResultProtocol> _call;
    NSMutableArray *_audioRecentCalls;
    NSMutableArray *_videoRecentCalls;
    UIBarButtonItem *_removeItem;
    UISearchController *_searchController;
    PHFrecentNoContentView *_noContentView;
    UIBarButtonItem *_contactsButton;
    UISegmentedControl *_facetimeFilter;
    unsigned long long _tableFilterMode;
}*/
@interface PHFrecentViewController (iOS9)
@property(nonatomic) unsigned long long tableFilterMode; // @synthesize tableFilterMode=_tableFilterMode;
@property(retain, nonatomic) UISegmentedControl *facetimeFilter; // @synthesize facetimeFilter=_facetimeFilter;
@property(retain, nonatomic) UIBarButtonItem *contactsButton; // @synthesize contactsButton=_contactsButton;
@property(retain, nonatomic) PHFrecentNoContentView *noContentView; // @synthesize noContentView=_noContentView;
@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) UIBarButtonItem *removeItem; // @synthesize removeItem=_removeItem;
@property(nonatomic) _Bool isSwipeToDelete; // @synthesize isSwipeToDelete=_isSwipeToDelete;
@property(retain, nonatomic) NSMutableArray *videoRecentCalls; // @synthesize videoRecentCalls=_videoRecentCalls;
@property(retain, nonatomic) NSMutableArray *audioRecentCalls; // @synthesize audioRecentCalls=_audioRecentCalls;
//@property(retain, nonatomic) id <PHSearchResultProtocol> call; // @synthesize call=_call;
- (void)setRecentCalls:(id)arg1;
- (id)recentCalls;
//- (void).cxx_destruct;
- (void)refresh;
- (void)markAllRecentCallsRead;
- (void)fetchRecentCalls;
- (void)savePreferences;
- (void)toggleTableFilterMode:(id)arg1;
- (void)removeRecentCalls:(id)arg1;
- (void)presentContactPickerViewController:(id)arg1;
- (void)prepareSubviewsForFilter:(id)arg1;
- (void)fetchVideoRecentCalls;
- (void)fetchAudioRecentCalls;
- (void)configureSearchBar:(id)arg1;
- (unsigned int)callTypeForTableFilterMode:(unsigned long long)arg1;
- (void)contentSizeCategoryDidChange:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)callCapabilitiesRelayCallingChanged:(id)arg1;
- (void)showCallDetail:(id)arg1;
- (_Bool)addressBookControllerShouldContinueAfterSelectingPerson:(void *)arg1;
- (void)addressBookControllerDidCancel:(id)arg1;
- (void)unknownPersonViewController:(id)arg1 didResolveToPerson:(void *)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)willDismissSearchController:(id)arg1;
- (void)willPresentSearchController:(id)arg1;
- (void)updateNoContentViewVisibility;
- (void)hideNoContentView;
- (void)handleNoContentTapGesture:(id)arg1;
- (void)showNoContentView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)applicationWillSuspend;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

