/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "ACAccountStore.h"

//#import "FBTestable-Protocol.h"

@class NSString;
/*
@interface FBAccountStore : ACAccountStore <FBTestable>
{
}*/
@interface FBAccountStore (Facebook_16_0)
+ (id)sharedAccountStore;
- (void)requestSystemAccountForApplicationWithFBID:(id)arg1 completion:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

