/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "FBValueObject.h"

//#import "NSCopying-Protocol.h"

@class FBMAdminText, FBMMessageAttachment, FBMMessageAttribution, FBMStringWithRedactedDescription, FBMSyncedThreadKey, NSArray, NSDictionary, NSString;
/*
@interface FBMMessage : FBValueObject <NSCopying>
{
    NSString *_messageId;
    NSString *_offlineThreadingId;
    FBMSyncedThreadKey *_threadKey;
    NSString *_senderId;
    FBMStringWithRedactedDescription *_text;
    FBMMessageAttachment *_attachment;
    NSArray *_tags;
    NSDictionary *_logMessage;
    FBMMessageAttribution *_attribution;
    unsigned int _type;
    FBMAdminText *_adminText;
    int _messageLifeTime;
    unsigned long long _timestamp;
    long long _actionId;
}*/
@interface FBMMessage (Messenger_54_0)
@property(readonly, nonatomic) int messageLifeTime; // @synthesize messageLifeTime=_messageLifeTime;
@property(readonly, copy, nonatomic) FBMAdminText *adminText; // @synthesize adminText=_adminText;
@property(readonly, nonatomic) unsigned int type; // @synthesize type=_type;
@property(readonly, copy, nonatomic) FBMMessageAttribution *attribution; // @synthesize attribution=_attribution;
@property(readonly, nonatomic) long long actionId; // @synthesize actionId=_actionId;
@property(readonly, nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, copy, nonatomic) NSDictionary *logMessage; // @synthesize logMessage=_logMessage;
@property(readonly, copy, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(readonly, copy, nonatomic) FBMMessageAttachment *attachment; // @synthesize attachment=_attachment;
@property(readonly, copy, nonatomic) FBMStringWithRedactedDescription *text; // @synthesize text=_text;
@property(readonly, copy, nonatomic) NSString *senderId; // @synthesize senderId=_senderId;
@property(readonly, copy, nonatomic) FBMSyncedThreadKey *threadKey; // @synthesize threadKey=_threadKey;
@property(readonly, copy, nonatomic) NSString *offlineThreadingId; // @synthesize offlineThreadingId=_offlineThreadingId;
@property(readonly, copy, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
//- (void).cxx_destruct;
- (id)initWithMessageId:(id)arg1 offlineThreadingId:(id)arg2 threadKey:(id)arg3 senderId:(id)arg4 text:(id)arg5 attachment:(id)arg6 tags:(id)arg7 logMessage:(id)arg8 timestamp:(unsigned long long)arg9 actionId:(long long)arg10 attribution:(id)arg11 type:(unsigned int)arg12 adminText:(id)arg13 messageLifeTime:(int)arg14;

@end

