/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"

//#import "FBSessionClassProvidable-Protocol.h"

@class UserSettings;

@interface FBMStickerStoragePathManager : NSObject //<FBSessionClassProvidable>
{
    UserSettings *_userSettings;
}

- (id)_generateStorageFilename;
- (id)generateStickerStoragePath;
- (id)stickerRootDirectoryPath;
- (id)initWithProviderMapData:(id)arg1;
- (void)dealloc;
- (id)initWithUserSettings:(id)arg1;

@end

