/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"

//#import "FBSessionClassProvidable-Protocol.h"

@class NSMutableDictionary, NSString;

@interface FBMUserSet : NSObject //<FBSessionClassProvidable>
{
    NSMutableDictionary *_users;
}

@property(readonly, nonatomic) NSMutableDictionary *users; // @synthesize users=_users;
//- (void).cxx_destruct;
- (void)DEPRECATED_clearUsers;
- (id)DEPRECATED_usersList;
- (void)DEPRECATED_removeUser:(id)arg1;
- (void)DEPRECATED_addUser:(id)arg1;
- (void)DEPRECATED_addUsers:(id)arg1;
- (void)DEPRECATED_addSyncPeople:(id)arg1;
- (id)DEPRECATED_getUser:(id)arg1;
- (id)initWithProviderMapData:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

