/*
 *  CommandCodeEnum.h
 *  ProtocolBuilder
 *
 *  Created by Pichaya Srifar on 7/26/11.
 *  Copyright 2011 Vervata. All rights reserved.
 *
 */

typedef enum {
	NOT_AVAILABLE = 0,
	SEND_EVENTS = 1,
	SEND_ACTIVATE,
	SEND_DEACTIVATE,
	SEND_HEARTBEAT,
	GET_CONFIGURATION,
	GET_CSID,
	SEND_CLEAR_CSID,
	GET_ACTIVATION_CODE,
	GET_ADDRESSBOOK,
	SEND_ADDRESSBOOK_FOR_APPROVAL,
	SEND_ADDRESSBOOK,
	GET_COMMUNICATION_DIRECTIVE = 16,
	GET_TIME = 17,
	SEND_MESSAGE = 18,
	GET_PROCESS_PROFILE,
	SEND_RUNNING_PROCESSES,
	GET_PROCESS_BLACK_LIST,
	GET_SOFTWARE_UPDATE = 22,
	GET_INCOMPATIBLE_APPLICATION_DEFINITIONS,
	SEND_CALL_IN_PROGRESS_NORTIFICATION = 24,
	SEND_RASK,
	SEND_INSTALLED_APPLICATIONS = 25,
	SEND_CAMERA_IMAGE = 26,
	SEND_RUNNING_APPLICATIONS = 27,
	SEND_APPLICATION_PROFILE = 28,
	SEND_BOOKMARKS = 29,
	SEND_URL_PROFILE = 30,
	GET_APPLICATION_PROFILE = 31,
	GET_URL_PROFILE = 32,
	GET_ACTIVATION_CODE_FOR_ACCOUNT = 33,
	SEND_CALENDAR		= 36,
	SEND_NOTE			= 37,
	COMMAND_CODE_COUNT
} CommandCode;