//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"
/*
@interface IMAVTelephonyManager : NSObject
{
    BOOL _isDesignatedAudioServiceProvider;
    BOOL _isDesignatedVideoServiceProvider;
    struct __CFMachPort *_ctServerMachPort;
    struct __CFUUID *_ctAudioToken;
    struct __CFUUID *_ctVideoToken;
}*/
@interface IMAVTelephonyManager (iOS8)
+ (id)numberToDialForNumber:(id)arg1 dialAssist:(char *)arg2;
+ (id)sharedInstance;
- (BOOL)_breakCSCallsIfNecessary;
- (BOOL)_wantsBreakBeforeMake;
- (void)stopWatchingForCTRequests;
- (void)startWatchingForCTRequests;
- (void)_chatStateChanged:(id)arg1;
- (void)notifyCallEndedForChat:(id)arg1;
- (void)_notifyMissedCallForInviteFromID:(id)arg1 isVideo:(BOOL)arg2;
- (void)notifyMissedCallForChat:(id)arg1;
- (void)notifyCallStartedForChat:(id)arg1;
- (void)notifyCallConnectingForChat:(id)arg1;
- (void)notifyCallConnectedForChat:(id)arg1;
- (BOOL)_isOnCallToID:(id)arg1;
- (void)_disconnectCSCallWithID:(id)arg1;
@property(readonly, nonatomic) unsigned int callState;
- (BOOL)_disconnectCTServerConnection;
- (BOOL)_reconnectCTServerConnectionIfNecessary;
- (BOOL)_setupCTServerConnection;
- (void)_cleanupMachInfo;
- (BOOL)_unregisterCTRequestService;
- (BOOL)_registerCTRequestService;
- (void)dealloc;
- (id)init;

@end

