//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  4 2016 10:44:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FBMGroupThreadProperties, FBMMontageThreadProperties, FBMSecureThreadProperties, NSString;

@interface FBMThreadSummaryTypeProperties : NSObject <NSCoding, NSCopying>
{
    unsigned long long _subtype;
    NSString *_canonical_otherUserId;
    FBMGroupThreadProperties *_group;
    FBMSecureThreadProperties *_secure;
    FBMMontageThreadProperties *_montage;
}

+ (id)secure:(id)arg1;
+ (id)montage:(id)arg1;
+ (id)group:(id)arg1;
+ (id)canonicalWithOtherUserId:(id)arg1;

- (void)matchCanonical:(id)arg1 group:(id)arg2 secure:(id)arg3 montage:(id)arg4;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;

@end

