//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class GroupPrivate, IRCollation, IRKey, Item, Media, Member, NSString, Schema, User;

@interface Group : NSObject
{
    Schema *_schema;
    id _peer;
}

+ (id)groupForKey:(id)arg1;
- (id)proxy;

@property(readonly, nonatomic) IRCollation *stories;
@property(readonly, nonatomic) IRCollation *members;
@property(readonly, nonatomic) _Bool hasOtherNewUnreadGroups;
@property(readonly, nonatomic) Item *nearLastReadPostItem;
@property(readonly, nonatomic) Group *forwardingGroup;
@property(readonly, nonatomic) _Bool isDraft;
@property(readonly, nonatomic) _Bool exists;
@property(readonly, nonatomic) GroupPrivate *groupPrivate;
@property(readonly, nonatomic) IRCollation *joinedMembers;
@property(readonly, nonatomic) IRCollation *invitedMembers;
@property(readonly, nonatomic) IRKey *lastReadItemKey;
@property(readonly, nonatomic) _Bool cleared;
@property(readonly, nonatomic) _Bool oneOnOne;
@property(readonly, nonatomic) _Bool unread;
@property(readonly, nonatomic) IRCollation *postedItems;
@property(readonly, nonatomic) Member *me;
@property(readonly, nonatomic) int itemCount;
@property(readonly, nonatomic) int memberCount;
@property(readonly, nonatomic) long long lastItemTime;
@property(readonly, nonatomic) long long lastItemId;
@property(readonly, nonatomic) Media *picture;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) _Bool readOnly;
@property(readonly, nonatomic) User *defaultGroupOtherUser;
@property(readonly, nonatomic) long long createdTime;
@property(readonly, nonatomic) NSString *groupId;
- (id)peer;
- (void)dealloc;
- (id)initWithSchema:(id)arg1 peer:(id)arg2;

@end

