/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"

@class FBMImageUrlCollection, FBMStringWithRedactedDescription, FBMThreadSnippet, NSArray, NSDictionary, NSMutableArray, NSString;
/*
@interface FBMThread : NSObject
{
    _Bool _unread;
    _Bool _canReply;
    _Bool _archived;
    _Bool _isFlaggedAsImportant;
    _Bool _dirty;
    _Bool _isGroupThread;
    _Bool _hasCustomName;
    int _numMessages;
    int _numUnreadMessages;
    NSString *_FBID;
    FBMStringWithRedactedDescription *_name;
    FBMImageUrlCollection *_imageUrls;
    NSString *_picHash;
    NSString *_viewerFBID;
    NSMutableArray *_senders;
    NSArray *_DEPRECATED_messages;
    NSDictionary *_participantsByUserId;
    FBMThreadSnippet *_serverSnippet;
    long long _timestamp;
    long long _clientTimestamp;
    long long _actionId;
    long long _refetchActionId;
    long long _lastVisibleActionId;
    long long _rawLastVisibleActionId;
    long long _mute;
    unsigned long long _cannotReplyReason;
    unsigned long long _folderType;
    NSString *_fbGroupId;
    NSString *_fbEventId;
    NSString *_customLikeEmoji;
    long long _ephemeralMessageLifeTime;
}*/
@interface FBMThread (Messenger_47_0)
@property(nonatomic) long long ephemeralMessageLifeTime; // @synthesize ephemeralMessageLifeTime=_ephemeralMessageLifeTime;
@property(copy, nonatomic) NSString *customLikeEmoji; // @synthesize customLikeEmoji=_customLikeEmoji;
@property(copy, nonatomic) NSString *fbEventId; // @synthesize fbEventId=_fbEventId;
@property(copy, nonatomic) NSString *fbGroupId; // @synthesize fbGroupId=_fbGroupId;
@property(nonatomic) unsigned long long folderType; // @synthesize folderType=_folderType;
@property(readonly, nonatomic) _Bool hasCustomName; // @synthesize hasCustomName=_hasCustomName;
@property(nonatomic) _Bool isGroupThread; // @synthesize isGroupThread=_isGroupThread;
@property(nonatomic) _Bool dirty; // @synthesize dirty=_dirty;
@property(nonatomic) _Bool isFlaggedAsImportant; // @synthesize isFlaggedAsImportant=_isFlaggedAsImportant;
@property(readonly, nonatomic) _Bool archived; // @synthesize archived=_archived;
@property(nonatomic) unsigned long long cannotReplyReason; // @synthesize cannotReplyReason=_cannotReplyReason;
@property(nonatomic) _Bool canReply; // @synthesize canReply=_canReply;
@property(nonatomic) _Bool unread; // @synthesize unread=_unread;
@property(readonly, nonatomic) long long mute; // @synthesize mute=_mute;
@property(nonatomic) int numUnreadMessages; // @synthesize numUnreadMessages=_numUnreadMessages;
@property(nonatomic) int numMessages; // @synthesize numMessages=_numMessages;
@property(nonatomic) long long rawLastVisibleActionId; // @synthesize rawLastVisibleActionId=_rawLastVisibleActionId;
@property(nonatomic) long long lastVisibleActionId; // @synthesize lastVisibleActionId=_lastVisibleActionId;
@property(nonatomic) long long refetchActionId; // @synthesize refetchActionId=_refetchActionId;
@property(nonatomic) long long actionId; // @synthesize actionId=_actionId;
@property(nonatomic) long long clientTimestamp; // @synthesize clientTimestamp=_clientTimestamp;
@property(nonatomic) long long timestamp; // @synthesize timestamp=_timestamp;
@property(copy, nonatomic) FBMThreadSnippet *serverSnippet; // @synthesize serverSnippet=_serverSnippet;
@property(copy, nonatomic) NSDictionary *participantsByUserId; // @synthesize participantsByUserId=_participantsByUserId;
@property(copy, nonatomic) NSArray *DEPRECATED_messages; // @synthesize DEPRECATED_messages=_DEPRECATED_messages;
@property(retain, nonatomic) NSMutableArray *senders; // @synthesize senders=_senders;
@property(copy, nonatomic) NSString *viewerFBID; // @synthesize viewerFBID=_viewerFBID;
@property(readonly, copy, nonatomic) NSString *picHash; // @synthesize picHash=_picHash;
@property(copy, nonatomic) FBMImageUrlCollection *imageUrls; // @synthesize imageUrls=_imageUrls;
@property(readonly, copy, nonatomic) FBMStringWithRedactedDescription *name; // @synthesize name=_name;
@property(readonly, copy, nonatomic) NSString *FBID; // @synthesize FBID=_FBID;
//- (void).cxx_destruct;
- (unsigned long long)checksum;
- (void)DEPRECATED_setArchived:(_Bool)arg1;
- (void)DEPRECATED_setPicHash:(id)arg1;
- (void)DEPRECATED_setMuteStatus:(long long)arg1;
- (void)DEPRECATED_setThreadName:(id)arg1 hasCustomName:(_Bool)arg2;
@property(readonly, nonatomic) long long rawActionId;
- (id)description;
- (id)initWithFBID:(id)arg1;

@end

