/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "UIView.h"
//
//#import "LiCoDisplayMetric-Protocol.h"
//#import "UITextFieldDelegate-Protocol.h"

@class UIButton, UIImageView, UILabel, UITextField;

@interface LiCoLoginSignInBoxView : UIView //<UITextFieldDelegate, LiCoDisplayMetric>
{
    UIImageView *_signInBackgroundView;
    UITextField *_emailField;
    UITextField *_passwordField;
    UIButton *_signInButton;
    UILabel *_forgotPasswordLabel;
    id _onSignIn;
}

+ (id)view;
@property(copy, nonatomic) id onSignIn; // @synthesize onSignIn=_onSignIn;
@property(retain, nonatomic)  UILabel *forgotPasswordLabel; // @synthesize forgotPasswordLabel=_forgotPasswordLabel;
@property(retain, nonatomic)  UIButton *signInButton; // @synthesize signInButton=_signInButton;
@property(retain, nonatomic)  UITextField *passwordField; // @synthesize passwordField=_passwordField;
@property(retain, nonatomic)  UITextField *emailField; // @synthesize emailField=_emailField;
@property(retain, nonatomic)  UIImageView *signInBackgroundView; // @synthesize signInBackgroundView=_signInBackgroundView;
//- (void).cxx_destruct;
- (id)serverMetricsObject;
- (id)displayCustomInfo;
- (id)displayMetric;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)setup;

@end

