/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import "Y_Messenger-Structs.h"
//#import "NSCoding.h"
//#import <XXUnknownSuperclass.h> // Unknown library
//#import "NSCopying.h"

@class NSString;

@interface YMIdentity : NSObject {//XXUnknownSuperclass <NSCoding, NSCopying> {
	NSString* uid_;
	int cloud_;
}
@property(copy, nonatomic) NSString* uid;
@property(assign, nonatomic) int cloud;
@property(copy, nonatomic) NSString* cloudIdentifier;
+(id)identityWithUid:(id)uid;
+(id)identityWithUid:(id)uid cloudIdentifier:(id)identifier;
+(id)identityWithUid:(id)uid cloud:(int)cloud;
+(int)cloudForIdentifier:(id)identifier;
+(id)identifierForCloud:(int)cloud;
-(id)initWithUid:(id)uid;
-(id)initWithUid:(id)uid cloudIdentifier:(id)identifier;
-(id)initWithUid:(id)uid cloud:(int)cloud;
-(id)initWithCoder:(id)coder;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(BOOL)isEqualToIdentity:(id)identity;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)description;
-(id)sanitizeUid:(id)uid;
-(void)normalize;
@end

