
/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "GBMAttachment.h"

@class NSString;
typedef struct{
    double latitude;
    double longtitude;
} CDStruct_2c43369c;
@interface GBMPlaceAttachment : GBMAttachment
{
    NSString *url_;
    CDStruct_2c43369c coordinate_;
    NSString *locationName_;
    NSString *locationAddress_;
}

@property(copy, nonatomic) NSString *locationAddress; // @synthesize locationAddress=locationAddress_;
@property(copy, nonatomic) NSString *locationName; // @synthesize locationName=locationName_;
@property(readonly, nonatomic) CDStruct_2c43369c coordinate; // @synthesize coordinate=coordinate_;
@property(copy, nonatomic) NSString *url; // @synthesize url=url_;
//- (void).cxx_destruct;
//- (id)initWithCoordinate:(CDStruct_2c43369c)arg1 locationName:(id)arg2 locationAddress:(id)arg3;
- (id)initWithUrl:(id)arg1 locationName:(id)arg2 locationAddress:(id)arg3;

@end

