/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"
//
//#import "GBMFavoriteable-Protocol.h"
//#import "NSCoding-Protocol.h"
//#import "NSCopying-Protocol.h"

@class GPCPersonMetadata, GPCPersonProfile, GPCPersonSuggestionData, NSArray, NSMutableDictionary, NSNumber, NSString, NSURL;

@interface GPCPerson : NSObject //<GBMFavoriteable, NSCoding, NSCopying>
{
    NSMutableDictionary *extensions_;
    NSString *gaiaId_;
    NSString *displayName_;
    GPCPersonMetadata *editMetadata_;
    NSString *firstName_;
    NSString *familyName_;
    int affinity_;
    NSString *affinitySortKey_;
    NSURL *avatarUrl_;
    NSURL *coverPhotoBestUrl_;
    NSURL *coverPhotoDisplayableUrl_;
    NSURL *defaultCoverPhotoUrl_;
    int gender_;
    int ageRange_;
    int userType_;
    int entityType_;
    int plusPageType_;
    NSString *canonicalUrlString_;
    int blockedState_;
    int domain_;
    int mutedState_;
    int verifiedState_;
    NSArray *circleMembershipIds_;
    NSArray *contactGroups_;
    NSNumber *followerCount_;
    int incomingCircleState_;
    GPCPersonProfile *profile_;
    GPCPersonSuggestionData *suggestionData_;
}

+ (void)registerExtension:(Class)arg1;
+ (void)initialize;
+ (id)uncachedPstnPersonWithJid:(id)arg1 displayName:(id)arg2 rate:(unsigned int)arg3 rateDescription:(id)arg4;
+ (void)setUnknownPersonFirstName:(id)arg1 unknownPersonDisplayName:(id)arg2 unknownPhoneNumberDisplayName:(id)arg3 localizedPersonNameFormat:(id)arg4;
+ (int)genderTypeToPbType:(int)arg1;
+ (long long)imageVersionFromUrl:(id)arg1;
+ (long long)int64FromBase64String:(id)arg1;
@property(retain, nonatomic) GPCPersonSuggestionData *suggestionData; // @synthesize suggestionData=suggestionData_;
@property(retain, nonatomic) GPCPersonProfile *profile; // @synthesize profile=profile_;
@property(nonatomic) int incomingCircleState; // @synthesize incomingCircleState=incomingCircleState_;
@property(retain, nonatomic) NSNumber *followerCount; // @synthesize followerCount=followerCount_;
@property(copy, nonatomic) NSArray *contactGroups; // @synthesize contactGroups=contactGroups_;
@property(readonly, nonatomic) NSArray *circleMembershipIds; // @synthesize circleMembershipIds=circleMembershipIds_;
@property(nonatomic) int verifiedState; // @synthesize verifiedState=verifiedState_;
@property(nonatomic) int mutedState; // @synthesize mutedState=mutedState_;
@property(nonatomic) int domain; // @synthesize domain=domain_;
@property(nonatomic) int blockedState; // @synthesize blockedState=blockedState_;
@property(copy, nonatomic) NSString *canonicalUrlString; // @synthesize canonicalUrlString=canonicalUrlString_;
@property(nonatomic) int plusPageType; // @synthesize plusPageType=plusPageType_;
@property(nonatomic) int entityType; // @synthesize entityType=entityType_;
@property(nonatomic) int userType; // @synthesize userType=userType_;
@property(nonatomic) int ageRange; // @synthesize ageRange=ageRange_;
@property(nonatomic) int gender; // @synthesize gender=gender_;
@property(retain, nonatomic) NSURL *defaultCoverPhotoUrl; // @synthesize defaultCoverPhotoUrl=defaultCoverPhotoUrl_;
@property(retain, nonatomic) NSURL *coverPhotoDisplayableUrl; // @synthesize coverPhotoDisplayableUrl=coverPhotoDisplayableUrl_;
@property(retain, nonatomic) NSURL *coverPhotoBestUrl; // @synthesize coverPhotoBestUrl=coverPhotoBestUrl_;
@property(retain, nonatomic) NSURL *avatarUrl; // @synthesize avatarUrl=avatarUrl_;
@property(copy, nonatomic) NSString *affinitySortKey; // @synthesize affinitySortKey=affinitySortKey_;
@property(nonatomic) int affinity; // @synthesize affinity=affinity_;
@property(copy, nonatomic) NSString *familyName; // @synthesize familyName=familyName_;
@property(copy, nonatomic) NSString *firstName; // @synthesize firstName=firstName_;
@property(readonly, nonatomic) GPCPersonMetadata *editMetadata; // @synthesize editMetadata=editMetadata_;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=displayName_;
@property(copy, nonatomic) NSString *gaiaId; // @synthesize gaiaId=gaiaId_;
//- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly, nonatomic) GPCPersonMetadata *writableFieldMetadata;
- (id)extensionForClass:(Class)arg1;
- (void)setExtension:(id)arg1 forClass:(Class)arg2;
- (void)setCircleMembershipIds:(id)arg1 circleCache:(id)arg2;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (id)initWithGaiaId:(id)arg1;
- (id)initForCopying;
- (id)init;
- (void)updateWithLocalContact:(id)arg1;
- (void)updateWithClientEntity:(id)arg1 defaultSuggestedType:(int)arg2;
- (void)updateWithClientEntity:(id)arg1;
- (void)raiseObservationFavoriteStateChanged:(int)arg1;
- (void)raiseObservationMetadataChanged;
- (void)raiseObservationPresenceChanged;
- (void)removeObserver:(id)arg1;
- (BOOL)containsObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)updateFavoriteState:(int)arg1;
- (id)lookupSpec;
@property(readonly, nonatomic) NSString *favoriteId;
@property(readonly, nonatomic) int favoriteState;
- (id)loadAvatar;
- (void)updateSuggestedType:(int)arg1;
- (void)updateActivityType:(int)arg1;
- (void)updateDeviceStatus:(int)arg1;
- (void)updateInCallType:(int)arg1;
- (void)updateMoodId:(id)arg1;
- (void)updateInvitedState:(int)arg1;
- (void)updatePresence:(int)arg1;
- (void)updateFallbackName:(id)arg1;
- (void)updateHasOneToOneConversation:(BOOL)arg1;
- (void)updateIsBlocked:(BOOL)arg1;
- (void)updateDisplayName:(id)arg1 personType:(int)arg2 rate:(unsigned int)arg3 rateDescription:(id)arg4;
- (void)updateWithUserAccount:(id)arg1;
- (long long)lastUpdatedTimestamp;
- (id)fallbackName;
- (BOOL)hasOneToOneConversation;
- (BOOL)hasValidFallbackName;
- (BOOL)hasLoadedConversationData;
- (id)rateDescription;
- (BOOL)isInCircles;
- (unsigned int)rate;
- (BOOL)isRateResolved;
- (id)extension;
- (void)setObserverProxy:(id)arg1;
- (id)observerProxy;
- (void)setAvatarsClient:(id)arg1;
- (id)avatarsClient;
- (void)setUserClient:(id)arg1;
- (id)userClient;
- (void)setIsDecorationComplete:(BOOL)arg1;
- (BOOL)isDecorationComplete;
- (void)loadFavoriteStatus;
- (id)loadProfileWithCompletionHandler:(id)arg1;
@property(readonly, nonatomic) NSString *circleMembershipNames;
@property(readonly, nonatomic) int suggestedType;
@property(readonly, nonatomic) int inviteState;
@property(readonly, nonatomic) int presence;
@property(readonly, nonatomic) int personType;
@property(readonly, nonatomic) NSString *moodId;
@property(readonly, nonatomic) int inCallType;
@property(readonly, nonatomic) int deviceStatus;
@property(readonly, nonatomic) int activityType;
@property(readonly, nonatomic) BOOL hasAvatar;
//@property(readonly, nonatomic) NSObject<GBMAvatar> *avatar;
@property(readonly, nonatomic) NSString *localizedFirstName;
@property(readonly, nonatomic) NSString *localizedDisplayName;
@property(readonly, nonatomic) BOOL hasValidFirstName;
@property(readonly, nonatomic) BOOL hasValidDisplayName;
@property(readonly, nonatomic) BOOL isGoogleUser;
@property(readonly, nonatomic) BOOL isSelfPerson;
@property(readonly, nonatomic) BOOL isBlocked;
- (void)updateEntityAndPlusPageTypesForSimpleProfile:(id)arg1;
- (void)setDisplayName:(id)arg1 withAvatarUrlString:(id)arg2;
- (void)updateFromPbUpdate:(id)arg1;
- (void)updateFromPbVideosData:(id)arg1 requestingGaiaId:(id)arg2;
- (void)updateFromPbReviewsData:(id)arg1 requestingGaiaId:(id)arg2;
- (void)updateFromPbPlus1data:(id)arg1;
- (void)updateFromPbSimpleProfile:(id)arg1 requestingGaiaId:(id)arg2;
- (void)updateFromPbSuggestedPerson:(id)arg1;
- (void)updateFromPbPeopleViewPerson:(id)arg1 requesterGaiaId:(id)arg2;
- (void)updateFromPbDeviceLocUserDeviceLocation:(id)arg1;
- (void)updateWithDisplayName:(id)arg1 avatarUrlString:(id)arg2;
- (void)updateFromPbUpdatePerson:(id)arg1;
- (void)updateFromPbSharingTarget:(id)arg1;
- (void)updateFromPbVisibleCirclesInfo:(id)arg1;
- (void)updateFromPbProfileCircles:(id)arg1 requestingGaiaId:(id)arg2;
- (void)updateFromPbPhotosDataUser:(id)arg1;
- (void)updateFromPbEMPersonV2:(id)arg1;
- (void)updateFromPbEMPerson:(id)arg1;
- (void)updateFromPbMergedPeoplePerson:(id)arg1;
- (void)updateFromPbCirclePerson:(id)arg1 requesterGaiaId:(id)arg2;
- (void)updateFromPbCircleMember:(id)arg1;
- (void)updateFromPbCircleMemberProperties:(id)arg1;
- (void)updateFromPbAuthorProto:(id)arg1;
- (BOOL)setAvatarUrlFromProfilePhotoUrlString:(id)arg1;

@end

