/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"

//#import "NSSecureCoding-Protocol.h"

@class FBMMessageAttachment, FBMMessageAttribution, FBMMessageLocation, FBMParticipantInfo, FBMStringWithRedactedDescription, FBMessageOutgoingAttribution, NSArray, NSDictionary, NSMutableArray, NSString;

@interface FBMMutableMessage : NSObject //<NSSecureCoding>
{
    _Bool _isIncomplete;
    _Bool _sendNonRetriable;
    _Bool _sendHasFailedBefore;
    NSString *_messageId;
    NSString *_threadFbId;
    FBMStringWithRedactedDescription *_text;
    NSString *_adminText;
    NSString *_adminSnippet;
    FBMMessageLocation *_location;
    NSArray *_DEPRECATED_attachments;
    NSDictionary *_DEPRECATED_shareMap;
    FBMMessageAttachment *_attachment;
    NSDictionary *_logMessage;
    NSArray *_tags;
    NSDictionary *_clientTags;
    FBMParticipantInfo *_DEPRECATED_senderInfo;
    NSMutableArray *_outgoingAttachments;
    long long _timestamp;
    long long _actionId;
    unsigned long long _type;
    NSString *_offlineThreadingId;
    long long _sendTimestamp;
    unsigned long long _sendState;
    NSString *_sendNonRetriableErrorText;
    FBMMessageAttribution *_attribution;
    FBMessageOutgoingAttribution *_outgoingAttribution;
}

+ (_Bool)supportsSecureCoding;
@property(copy, nonatomic) FBMessageOutgoingAttribution *outgoingAttribution; // @synthesize outgoingAttribution=_outgoingAttribution;
@property(copy, nonatomic) FBMMessageAttribution *attribution; // @synthesize attribution=_attribution;
@property(nonatomic) _Bool sendHasFailedBefore; // @synthesize sendHasFailedBefore=_sendHasFailedBefore;
@property(copy, nonatomic) NSString *sendNonRetriableErrorText; // @synthesize sendNonRetriableErrorText=_sendNonRetriableErrorText;
@property(nonatomic) _Bool sendNonRetriable; // @synthesize sendNonRetriable=_sendNonRetriable;
@property(nonatomic) unsigned long long sendState; // @synthesize sendState=_sendState;
@property(nonatomic) long long sendTimestamp; // @synthesize sendTimestamp=_sendTimestamp;
@property(nonatomic) _Bool isIncomplete; // @synthesize isIncomplete=_isIncomplete;
@property(copy, nonatomic) NSString *offlineThreadingId; // @synthesize offlineThreadingId=_offlineThreadingId;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) long long actionId; // @synthesize actionId=_actionId;
@property(nonatomic) long long timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) NSMutableArray *outgoingAttachments; // @synthesize outgoingAttachments=_outgoingAttachments;
@property(retain, nonatomic) FBMParticipantInfo *DEPRECATED_senderInfo; // @synthesize DEPRECATED_senderInfo=_DEPRECATED_senderInfo;
@property(copy, nonatomic) NSDictionary *clientTags; // @synthesize clientTags=_clientTags;
@property(copy, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(copy, nonatomic) NSDictionary *logMessage; // @synthesize logMessage=_logMessage;
@property(copy, nonatomic) FBMMessageAttachment *attachment; // @synthesize attachment=_attachment;
@property(copy, nonatomic) NSDictionary *DEPRECATED_shareMap; // @synthesize DEPRECATED_shareMap=_DEPRECATED_shareMap;
@property(copy, nonatomic) NSArray *DEPRECATED_attachments; // @synthesize DEPRECATED_attachments=_DEPRECATED_attachments;
@property(copy, nonatomic) FBMMessageLocation *location; // @synthesize location=_location;
@property(copy, nonatomic) NSString *adminSnippet; // @synthesize adminSnippet=_adminSnippet;
@property(copy, nonatomic) NSString *adminText; // @synthesize adminText=_adminText;
@property(copy, nonatomic) FBMStringWithRedactedDescription *text; // @synthesize text=_text;
@property(copy, nonatomic) NSString *threadFbId; // @synthesize threadFbId=_threadFbId;
@property(copy, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
//- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic) unsigned long long source;
@property(readonly, copy, nonatomic) NSString *senderId;
@property(readonly, nonatomic) long long rawActionId;
- (id)debugDescription;
- (id)description;
- (id)init;

@end

