/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "FBMAttachment.h"

#import "OutgoingAttachment-Protocol.h"

@class NSData;

@interface FBMShareAttachment : FBMAttachment <OutgoingAttachment>
{
    unsigned long long _FBID;
}

+ (id)mimeType;
@property(nonatomic) unsigned long long FBID; // @synthesize FBID=_FBID;
- (id)getThumbnailOfSize:(struct CGSize)arg1;
- (id)attachmentFilename;
- (id)attachmentHandle;
@property(readonly, nonatomic) NSData *attachmentData;
- (void)addAsAttachFile:(id)arg1;
- (void)addAsParamsToDictionary:(id)arg1;
- (void)addAsParamsToRequest:(id)arg1;
- (void)cancelPrepareAttachmentData;
- (BOOL)canCancelPrepareAttachmentData;
- (void)prepareAttachmentDataWithCompletedBlock:(id)arg1;
- (BOOL)isSameAttachmentAs:(id)arg1;
- (id)initWithFBID:(unsigned long long)arg1;

@end

