/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

//#import "NSObject.h"

@class NSString, UIImage;

@interface PhoneCall : NSObject
{
    struct __CTCall *_call;
    NSString *_displayName;
    NSString *_overrideName;
    unsigned int _displayNameBreakPoint;
    int _abUid;
    NSString *_abLabel;
    UIImage *_image;
    struct {
        unsigned int imageType:2;
        unsigned int abUidIsValid:1;
        unsigned int dialAssisted:1;
        unsigned int dialedFromEmergencyUI:1;
        unsigned int isEmergencyCall:1;
        unsigned int joiningConference:1;
        unsigned int leavingConference:1;
    } _phoneCallFlags;
}

+ (id)phoneCallForCall:(struct __CTCall *)arg1;
- (id)initWithCall:(struct __CTCall *)arg1;
- (void)dealloc;
- (int)_addressBookUid;
- (void)_handleIdentityChange;
- (void)_handleCallerIDChange;
- (void)_handleStatusChange;
- (struct __CTCall *)call;
- (int)status;
- (BOOL)isAlerting;
- (BOOL)isVoicemail;
- (BOOL)hold;
- (BOOL)unhold;
- (BOOL)isConferenced;
- (void)joinConference;
- (void)leaveConference;
- (void)disconnect;
- (id)number;
- (int)abUID;
- (id)_displayNameWithSeparator:(id)arg1;
- (id)displayName;
- (id)multiLineDisplayName;
- (id)localizedLabel;
- (void)setOverrideName:(id)arg1;
- (BOOL)wasDialAssisted;
- (void)setWasDialAssisted:(BOOL)arg1;
- (BOOL)wasDialedFromEmergencyUI;
- (void)setWasDialedFromEmergencyUI:(BOOL)arg1;
- (BOOL)isEmergencyCall;
- (id)_image;
- (id)desktopImage;
- (id)smallImage;
- (void)phoneApplicationAddressBookChangedNotification:(id)arg1;

@end

