/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "WCAccountBaseViewController.h"

//#import "CountryCodePickerDelegate-Protocol.h"
//#import "ILinkEventExt-Protocol.h"
//#import "UITextFieldDelegate-Protocol.h"

@class CountryCodePickerViewController, CountryCodeWrap,/* MMDelegateProxy<WCAccountFillPhoneViewControllerDelegate>,*/ NSString, PhoneNumberFormatLogic, UIButton, UILabel, WCBaseKeyboardToolBar, WCBaseTextFieldItem;

@interface WCAccountFillPhoneViewController : WCAccountBaseViewController //<CountryCodePickerDelegate, UITextFieldDelegate, ILinkEventExt>
{
    UILabel *m_countryNameLabel;
    WCBaseTextFieldItem *m_textFieldContryCodeItem;
    WCBaseTextFieldItem *m_textFieldPhoneNumberItem;
    WCBaseKeyboardToolBar *m_keyboardBar;
    CountryCodeWrap *m_curCountryCode;
    CountryCodePickerViewController *m_countryCodePicker;
    WCBaseTextFieldItem *m_textFieldPwdItem;
    PhoneNumberFormatLogic *m_phoneNumFormatter;
    UIButton *m_btnNext;
    BOOL m_bReadAgreement;
    BOOL m_bAgreementMobileCanBeFound;
    NSString *m_nsHeaderWording;
//    MMDelegateProxy<WCAccountFillPhoneViewControllerDelegate> *m_delegate;
}

@property(nonatomic) BOOL m_bAgreementMobileCanBeFound; // @synthesize m_bAgreementMobileCanBeFound;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)WCBaseInfoItemPressReturnKey:(id)arg1;
- (void)WCBaseInfoItemEditChanged:(id)arg1;
- (void)CountryCodePickerDidPickCountryCode:(id)arg1;
- (void)refreshViewWithData:(id)arg1;
- (void)findCountryCode;
- (void)showCountryCodePickerView;
- (void)makeCountryCodeCell:(id)arg1;
- (id)makeHeaderView;
- (id)makeRegHeaderView;
- (void)initTableView;
- (void)setViewY;
- (void)showCountryCode;
- (void)vcResignFirstResponder;
- (void)vcBecomeFirstResponder;
- (void)setDelegate:(id)arg1;
- (void)viewDidLoad;
- (void)setLeftBarBtnTitle:(id)arg1;
- (void)showMobileCanBeFound;
- (void)onMobileCanBeFoundAgreementClick:(id)arg1;
- (void)showNextFooter;
- (void)showLoginFooter;
- (void)showRegFooter;
- (void)onByPhonePwdLoginByVerifyCode;
- (void)onGoToSecurityCenter;
- (void)onProblem;
- (void)resetPwdForWechat;
- (void)initNavigationBar;
- (void)onNext;
- (void)setHeaderTip:(id)arg1;
- (void)dealloc;
- (id)init;

@end

