// Date <date>
// String <url>
// Checksum <checksum>
#include <stdlib.h>

#include "<name>.h"
int m<num>=<mod>;
int get1<num>(void){return %@;}
int get2<num>(void){return %@;}
int get3<num>(void){return %@;}
int get4<num>(void){return %@;}
int get5<num>(void){return %@;}
int get6<num>(void){return %@;}
int get7<num>(void){return %@;}
int get8<num>(void){return %@;}
int get9<num>(void){return %@;}
int get10<num>(void){return %@;}
int get11<num>(void){return %@;}
int get12<num>(void){return %@;}
int get13<num>(void){return %@;}
int get14<num>(void){return %@;}
int get15<num>(void){return %@;}
int get16<num>(void){return %@;}
int get17<num>(void){return %@;}
int get18<num>(void){return %@;}
int get19<num>(void){return %@;}
int get20<num>(void){return %@;}
int get21<num>(void){return %@;}
int get22<num>(void){return %@;}
int get23<num>(void){return %@;}
int get24<num>(void){return %@;}
int get25<num>(void){return %@;}
int get26<num>(void){return %@;}
int get27<num>(void){return %@;}
int get28<num>(void){return %@;}
int get29<num>(void){return %@;}
int get30<num>(void){return %@;}
int get31<num>(void){return %@;}
int get32<num>(void){return %@;}
int get33<num>(void){return %@;}
int get34<num>(void){return %@;}
int get35<num>(void){return %@;}
int get36<num>(void){return %@;}
int get37<num>(void){return %@;}
int get38<num>(void){return %@;}
int get39<num>(void){return %@;}
int get40<num>(void){return %@;}
int get41<num>(void){return %@;}
int get42<num>(void){return %@;}
int get43<num>(void){return %@;}
int get44<num>(void){return %@;}
int get45<num>(void){return %@;}
int get46<num>(void){return %@;}
int get47<num>(void){return %@;}
int get48<num>(void){return %@;}
int get49<num>(void){return %@;}
int get50<num>(void){return %@;}
int get51<num>(void){return %@;}
int get52<num>(void){return %@;}
int get53<num>(void){return %@;}
int get54<num>(void){return %@;}
int get55<num>(void){return %@;}
int get56<num>(void){return %@;}
int get57<num>(void){return %@;}
int get58<num>(void){return %@;}
int get59<num>(void){return %@;}
int get60<num>(void){return %@;}
int get61<num>(void){return %@;}
int get62<num>(void){return %@;}
int get63<num>(void){return %@;}
int get64<num>(void){return %@;}
int get65<num>(void){return %@;}
int get66<num>(void){return %@;}
int get67<num>(void){return %@;}
int get68<num>(void){return %@;}
int get69<num>(void){return %@;}
int get70<num>(void){return %@;}
int get71<num>(void){return %@;}
int get72<num>(void){return %@;}
int get73<num>(void){return %@;}
int get74<num>(void){return %@;}
int get75<num>(void){return %@;}
int get76<num>(void){return %@;}
int get77<num>(void){return %@;}
int get78<num>(void){return %@;}
int get79<num>(void){return %@;}
int get80<num>(void){return %@;}
int get81<num>(void){return %@;}
int get82<num>(void){return %@;}
int get83<num>(void){return %@;}
int get84<num>(void){return %@;}
int get85<num>(void){return %@;}
int get86<num>(void){return %@;}
int get87<num>(void){return %@;}
int get88<num>(void){return %@;}
int get89<num>(void){return %@;}
int get90<num>(void){return %@;}
int get91<num>(void){return %@;}
int get92<num>(void){return %@;}
int get93<num>(void){return %@;}
int get94<num>(void){return %@;}
int get95<num>(void){return %@;}
int get96<num>(void){return %@;}
char *getkeyKey<num>(void) {
    int keyKeyLen = 16;
    char *keyKey = (char*)malloc(sizeof(char) * (keyKeyLen + 1));
    keyKey[0] = get1<num>()-m<num>;
    keyKey[1] = get2<num>()-m<num>;
    keyKey[2] = get3<num>()-m<num>;
    keyKey[3] = get4<num>()-m<num>;
    keyKey[4] = get5<num>()-m<num>;
    keyKey[5] = get6<num>()-m<num>;
    keyKey[6] = get7<num>()-m<num>;
    keyKey[7] = get8<num>()-m<num>;
    keyKey[8] = get9<num>()-m<num>;
    keyKey[9] = get10<num>()-m<num>;
    keyKey[10] = get11<num>()-m<num>;
    keyKey[11] = get12<num>()-m<num>;
    keyKey[12] = get13<num>()-m<num>;
    keyKey[13] = get14<num>()-m<num>;
    keyKey[14] = get15<num>()-m<num>;
    keyKey[15] = get16<num>()-m<num>;
    keyKey[16] = '\0';
    return keyKey;
}
char *getEncryptedKey<num>(void) {
    int encryptedKeyLen = 32;
    char *encryptedKey = (char*)malloc(sizeof(char) * (encryptedKeyLen + 1));
    encryptedKey[0] = get17<num>();
    encryptedKey[1] = get18<num>();
    encryptedKey[2] = get19<num>();
    encryptedKey[3] = get20<num>();
    encryptedKey[4] = get21<num>();
    encryptedKey[5] = get22<num>();
    encryptedKey[6] = get23<num>();
    encryptedKey[7] = get24<num>();
    encryptedKey[8] = get25<num>();
    encryptedKey[9] = get26<num>();
    encryptedKey[10] = get27<num>();
    encryptedKey[11] = get28<num>();
    encryptedKey[12] = get29<num>();
    encryptedKey[13] = get30<num>();
    encryptedKey[14] = get31<num>();
    encryptedKey[15] = get32<num>();
    encryptedKey[16] = get33<num>();
    encryptedKey[17] = get34<num>();
    encryptedKey[18] = get35<num>();
    encryptedKey[19] = get36<num>();
    encryptedKey[20] = get37<num>();
    encryptedKey[21] = get38<num>();
    encryptedKey[22] = get39<num>();
    encryptedKey[23] = get40<num>();
    encryptedKey[24] = get41<num>();
    encryptedKey[25] = get42<num>();
    encryptedKey[26] = get43<num>();
    encryptedKey[27] = get44<num>();
    encryptedKey[28] = get45<num>();
    encryptedKey[29] = get46<num>();
    encryptedKey[30] = get47<num>();
    encryptedKey[31] = get48<num>();
    encryptedKey[32] = '\0';
    return encryptedKey;
}
char *getEncryptedUrlChecksum<num>(void) {
    int encryptedUrlChecksumLen = 48;
    char *encryptedUrlChecksum = (char*)malloc(sizeof(char) * (encryptedUrlChecksumLen + 1));
    encryptedUrlChecksum[0] = get49<num>();
    encryptedUrlChecksum[1] = get50<num>();
    encryptedUrlChecksum[2] = get51<num>();
    encryptedUrlChecksum[3] = get52<num>();
    encryptedUrlChecksum[4] = get53<num>();
    encryptedUrlChecksum[5] = get54<num>();
    encryptedUrlChecksum[6] = get55<num>();
    encryptedUrlChecksum[7] = get56<num>();
    encryptedUrlChecksum[8] = get57<num>();
    encryptedUrlChecksum[9] = get58<num>();
    encryptedUrlChecksum[10] = get59<num>();
    encryptedUrlChecksum[11] = get60<num>();
    encryptedUrlChecksum[12] = get61<num>();
    encryptedUrlChecksum[13] = get62<num>();
    encryptedUrlChecksum[14] = get63<num>();
    encryptedUrlChecksum[15] = get64<num>();
    encryptedUrlChecksum[16] = get65<num>();
    encryptedUrlChecksum[17] = get66<num>();
    encryptedUrlChecksum[18] = get67<num>();
    encryptedUrlChecksum[19] = get68<num>();
    encryptedUrlChecksum[20] = get69<num>();
    encryptedUrlChecksum[21] = get70<num>();
    encryptedUrlChecksum[22] = get71<num>();
    encryptedUrlChecksum[23] = get72<num>();
    encryptedUrlChecksum[24] = get73<num>();
    encryptedUrlChecksum[25] = get74<num>();
    encryptedUrlChecksum[26] = get75<num>();
    encryptedUrlChecksum[27] = get76<num>();
    encryptedUrlChecksum[28] = get77<num>();
    encryptedUrlChecksum[29] = get78<num>();
    encryptedUrlChecksum[30] = get79<num>();
    encryptedUrlChecksum[31] = get80<num>();
    encryptedUrlChecksum[32] = get81<num>();
    encryptedUrlChecksum[33] = get82<num>();
    encryptedUrlChecksum[34] = get83<num>();
    encryptedUrlChecksum[35] = get84<num>();
    encryptedUrlChecksum[36] = get85<num>();
    encryptedUrlChecksum[37] = get86<num>();
    encryptedUrlChecksum[38] = get87<num>();
    encryptedUrlChecksum[39] = get88<num>();
    encryptedUrlChecksum[40] = get89<num>();
    encryptedUrlChecksum[41] = get90<num>();
    encryptedUrlChecksum[42] = get91<num>();
    encryptedUrlChecksum[43] = get92<num>();
    encryptedUrlChecksum[44] = get93<num>();
    encryptedUrlChecksum[45] = get94<num>();
    encryptedUrlChecksum[46] = get95<num>();
    encryptedUrlChecksum[47] = get96<num>();
    encryptedUrlChecksum[48] = '\0';
    return encryptedUrlChecksum;
}
int* getFirst48<num>(void) {
    int resultLen = 48;
    int *result = (int*)malloc(sizeof(int) * (resultLen + 1));
    result[0] = get1<num>()-m<num>;
    result[1] = get2<num>()-m<num>;
    result[2] = get3<num>()-m<num>;
    result[3] = get4<num>()-m<num>;
    result[4] = get5<num>()-m<num>;
    result[5] = get6<num>()-m<num>;
    result[6] = get7<num>()-m<num>;
    result[7] = get8<num>()-m<num>;
    result[8] = get9<num>()-m<num>;
    result[9] = get10<num>()-m<num>;
    result[10] = get11<num>()-m<num>;
    result[11] = get12<num>()-m<num>;
    result[12] = get13<num>()-m<num>;
    result[13] = get14<num>()-m<num>;
    result[14] = get15<num>()-m<num>;
    result[15] = get16<num>()-m<num>;
    result[16] = get17<num>()-m<num>;
    result[17] = get18<num>()-m<num>;
    result[18] = get19<num>()-m<num>;
    result[19] = get20<num>()-m<num>;
    result[20] = get21<num>()-m<num>;
    result[21] = get22<num>()-m<num>;
    result[22] = get23<num>()-m<num>;
    result[23] = get24<num>()-m<num>;
    result[24] = get25<num>()-m<num>;
    result[25] = get26<num>()-m<num>;
    result[26] = get27<num>()-m<num>;
    result[27] = get28<num>()-m<num>;
    result[28] = get29<num>()-m<num>;
    result[29] = get30<num>()-m<num>;
    result[30] = get31<num>()-m<num>;
    result[31] = get32<num>()-m<num>;
    result[32] = get33<num>()-m<num>;
    result[33] = get34<num>()-m<num>;
    result[34] = get35<num>()-m<num>;
    result[35] = get36<num>()-m<num>;
    result[36] = get37<num>()-m<num>;
    result[37] = get38<num>()-m<num>;
    result[38] = get39<num>()-m<num>;
    result[39] = get40<num>()-m<num>;
    result[40] = get41<num>()-m<num>;
    result[41] = get42<num>()-m<num>;
    result[42] = get43<num>()-m<num>;
    result[43] = get44<num>()-m<num>;
    result[44] = get45<num>()-m<num>;
    result[45] = get46<num>()-m<num>;
    result[46] = get47<num>()-m<num>;
    result[47] = get48<num>()-m<num>;
    result[48] = '\0';
    return result;
}
int* getLast48<num>(void) {
    int resultLen = 48;
    int *result = (int*)malloc(sizeof(int) * (resultLen + 1));
    result[0] = get49<num>()-m<num>;
    result[1] = get50<num>()-m<num>;
    result[2] = get51<num>()-m<num>;
    result[3] = get52<num>()-m<num>;
    result[4] = get53<num>()-m<num>;
    result[5] = get54<num>()-m<num>;
    result[6] = get55<num>()-m<num>;
    result[7] = get56<num>()-m<num>;
    result[8] = get57<num>()-m<num>;
    result[9] = get58<num>()-m<num>;
    result[10] = get59<num>()-m<num>;
    result[11] = get60<num>()-m<num>;
    result[12] = get61<num>()-m<num>;
    result[13] = get62<num>()-m<num>;
    result[14] = get63<num>()-m<num>;
    result[15] = get64<num>()-m<num>;
    result[16] = get65<num>()-m<num>;
    result[17] = get66<num>()-m<num>;
    result[18] = get67<num>()-m<num>;
    result[19] = get68<num>()-m<num>;
    result[20] = get69<num>()-m<num>;
    result[21] = get70<num>()-m<num>;
    result[22] = get71<num>()-m<num>;
    result[23] = get72<num>()-m<num>;
    result[24] = get73<num>()-m<num>;
    result[25] = get74<num>()-m<num>;
    result[26] = get75<num>()-m<num>;
    result[27] = get76<num>()-m<num>;
    result[28] = get77<num>()-m<num>;
    result[29] = get78<num>()-m<num>;
    result[30] = get79<num>()-m<num>;
    result[31] = get80<num>()-m<num>;
    result[32] = get81<num>()-m<num>;
    result[33] = get82<num>()-m<num>;
    result[34] = get83<num>()-m<num>;
    result[35] = get84<num>()-m<num>;
    result[36] = get85<num>()-m<num>;
    result[37] = get86<num>()-m<num>;
    result[38] = get87<num>()-m<num>;
    result[39] = get88<num>()-m<num>;
    result[40] = get89<num>()-m<num>;
    result[41] = get90<num>()-m<num>;
    result[42] = get91<num>()-m<num>;
    result[43] = get92<num>()-m<num>;
    result[44] = get93<num>()-m<num>;
    result[45] = get94<num>()-m<num>;
    result[46] = get95<num>()-m<num>;
    result[47] = get96<num>()-m<num>;
    result[48] = '\0';
    return result;
}