/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "DataElement.h"

@class GBMPhoto, NSString, NSURL, UIImage;

@interface GBMPhotoLoader : NSObject //DataElement
{
    int photoWidth_;
    int photoHeight_;
    NSURL *sourceAssetURL_;
    UIImage *sourceImage_;
    NSString *sourceUrl_;
    NSURL *externalUrl_;
    int sourceType_;
    //id <GBMPhotosClient> photosClient_;
    GBMPhoto *localPhoto_;
    //id <GPCImageFetcherAsyncRequest> imageFetcherRequest_;
    int width_;
    int height_;
    NSString *ownerId_;
    NSString *photoId_;
}

+ (void)initialize;
@property(readonly, nonatomic) int sourceType; // @synthesize sourceType=sourceType_;
@property(readonly, nonatomic) NSString *photoId; // @synthesize photoId=photoId_;
@property(readonly, nonatomic) NSString *ownerId; // @synthesize ownerId=ownerId_;
@property(readonly, nonatomic) GBMPhoto *localPhoto; // @synthesize localPhoto=localPhoto_;
@property(retain, nonatomic) NSString *sourceUrl; // @synthesize sourceUrl=sourceUrl_;
@property(readonly, nonatomic) int photoHeight; // @synthesize photoHeight=height_;
@property(readonly, nonatomic) int photoWidth; // @synthesize photoWidth=width_;
//- (void).cxx_destruct;
- (id)dataForAssetRepresentation:(id)arg1;
- (void)loadUrlForWidth:(int)arg1 completionHandler:(id)arg2;
- (void)loadImageForWidth:(int)arg1 completionHandler:(id)arg2;
- (void)loadExternalUrlWithCompletionHandler:(id)arg1;
- (void)loadAssetForWidth:(int)arg1 completionHandler:(id)arg2;
- (void)loadPhotoForWidth:(int)arg1 completionHandler:(id)arg2;
- (id)photoForWidth:(int)arg1 completionHandler:(id)arg2;
- (id)cachedPhotoForWidth:(int)arg1;
- (int)height;
- (int)width;
- (id)tableType;
- (id)elementId;
- (id)initWithPhotoId:(id)arg1 ownerId:(id)arg2 url:(id)arg3 width:(int)arg4 height:(int)arg5;
- (id)initWithPhotosClient:(id)arg1 url:(id)arg2 width:(int)arg3 height:(int)arg4;
- (id)initWithImage:(id)arg1;
- (id)initWithExternalUrl:(id)arg1 size:(struct CGSize)arg2;
- (id)initWithAsset:(id)arg1;
- (void)updateChatMessage:(id)arg1;

@end

