/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SKPMessage.h"

@class SKPVideoMessage;

__attribute__((visibility("hidden")))
@interface SKPVideoMessageMessage : SKPMessage {
	SKPVideoMessage* _videoMessage;
}
@property(retain, nonatomic) SKPVideoMessage* videoMessage;
+(id)lazyLoadedPropertiesKeypaths;
//-(void).cxx_destruct;
-(id)fetchVideoMessageOperation;
-(BOOL)flushLazyProperty:(id)property;
-(id)fetchOperationForLazyProperty:(id)lazyProperty fetchQueueIdentifier:(id*)identifier;
-(id)attributedSummary;
-(int)type;
@end

