/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "CKMessage.h"

@class CKSMSMessageDelivery, NSMutableArray;

@interface CKSMSMessage : CKMessage
{
    NSMutableArray *_messages;
    int _associationID;
    int _rowID;
    CKSMSMessageDelivery *_delivery;
}

@property(retain, nonatomic) CKSMSMessageDelivery *delivery; // @synthesize delivery=_delivery;
- (void)dealloc;
- (void)_loadFailedSendCount;
- (BOOL)isPlaceholder;
- (BOOL)hasBeenRead;
- (int)totalMessageCount;
- (int)sentCount;
- (void)_storeUIFlags:(unsigned long)arg1;
- (void)_loadUIFlags;
- (void)_loadSubject;
- (void)_loadText;
- (BOOL)_loadOutgoing;
- (id)_newParts;
- (void)addMessage:(struct __CKSMSRecord *)arg1;
- (void)setMessages:(id)arg1;
- (void)markAsRead;
- (double)_loadDate;
- (void)permanentlyRemoveMessage;
- (id)messages;
- (id)initWithCTMessage:(struct __CKSMSRecord *)arg1 messageParts:(id)arg2;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)initWithCTMessages:(id)arg1 messageParts:(id)arg2;
- (id)initWithRowID:(int)arg1;
- (int)messageCount;
- (BOOL)isForward;
- (void)prepareToResend;
- (id)sender;
- (id)address;
- (id)alertImageData;
- (BOOL)isOnlyDisplayableMessagePart:(id)arg1;
- (BOOL)containsDisplayableMessageParts;
- (void)deleteMessagePart:(id)arg1;
- (void)_setupDeliveryIfPending;
- (void)deliveredSubpart:(int)arg1 totalSubparts:(int)arg2 success:(BOOL)arg3;
- (void)deliveryCompletedForMessage:(id)arg1;
- (void)deliveryFailedForMessage:(id)arg1;
- (void)deliveryPartiallyFailedForMessage:(id)arg1;
@property(readonly, nonatomic) int rowID; // @synthesize rowID=_rowID;
@property(readonly, nonatomic) int associationID; // @synthesize associationID=_associationID;

@end

