/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "UIResponder.h"
//
//#import "UIApplicationDelegate-Protocol.h"

@class LaunchManager, UIWindow;

//@interface AppDelegate //: UIResponder <UIApplicationDelegate>
//{
//    BOOL _didRegisterForPushNotifications;
//    UIWindow *_window;
//    LaunchManager *_launchManager;
//}

@interface AppDelegate (Vimeo)
@property(nonatomic) BOOL didRegisterForPushNotifications; // @synthesize didRegisterForPushNotifications=_didRegisterForPushNotifications;
@property(retain, nonatomic) LaunchManager *launchManager; // @synthesize launchManager=_launchManager;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
//- (void).cxx_destruct;
- (BOOL)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(id)arg3;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)application:(id)arg1 handleEventsForBackgroundURLSession:(id)arg2 completionHandler:(id)arg3;
- (BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;

@end

