/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"
//
//#import "VIMNetworkingAuth-Protocol.h"

@class NSString, User;

@interface SMKVimeoAuthentication : NSObject //<VIMNetworkingAuth>
{
    BOOL _isLoggedIn;
    User *_loggedInUser;
}

+ (id)sharedHelper;
@property(retain, nonatomic) User *loggedInUser; // @synthesize loggedInUser=_loggedInUser;
@property(nonatomic) BOOL isLoggedIn; // @synthesize isLoggedIn=_isLoggedIn;
//- (void).cxx_destruct;
//@property(nonatomic) __weak NSString *userAccessToken;
- (id)tokenUnavailableError;
- (id)defaultLogInError;
- (id)defaultRegistrationError;
- (id)basicAuthHeaderString;
- (id)xAuthHeaderString;
- (void)clearUserDetails;
- (void)facebookTokenWithCompletionBlock:(id)arg1;
- (id)ephemeralSessionConfiguration;
- (id)backgroundSessionConfiguration;
- (id)defaultSessionConfiguration;
- (id)acceptHeaderString;
- (id)authenticationHeaderString;
- (void)handleAuthenticationSuccess:(id)arg1;
- (id)validateAuthenticationResponse:(id)arg1 withClass:(Class)arg2;
- (id)requestForFBRegisterWithToken:(id)arg1 delegate:(id)arg2;
- (id)requestForVimeoRegisterWithName:(id)arg1 userName:(id)arg2 password:(id)arg3 delegate:(id)arg4;
- (id)requestForFBLogInWithToken:(id)arg1 delegate:(id)arg2;
- (id)requestForVimeoLogInWithUserName:(id)arg1 password:(id)arg2 delegate:(id)arg3;
- (void)attemptRegistrationForRequest:(id)arg1 withCompletionBlock:(id)arg2;
- (void)attemptLogInForRequest:(id)arg1 withCompletionBlock:(id)arg2;
- (void)registerWithSocialTokenForDelegate:(id)arg1 andCompletionBlock:(id)arg2;
- (void)logInWithSocialTokenForDelegate:(id)arg1 andCompletionBlock:(id)arg2;
- (void)registerWithName:(id)arg1 userName:(id)arg2 password:(id)arg3 delegate:(id)arg4 andCompletionBlock:(id)arg5;
- (void)logInWithUsername:(id)arg1 password:(id)arg2 delegate:(id)arg3 andCompletionBlock:(id)arg4;
- (void)cancelLogInForDelegate:(id)arg1;
- (void)logOut;
- (void)loadUserFromCacheWithCompletionBlock:(id)arg1;

@end

