//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  4 2016 10:44:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class IGDirectCache, IGDirectInboxNetworker;

@interface IGDirectRefreshService : NSObject
{
    IGDirectInboxNetworker *_inboxNetworker;
    IGDirectCache *_cache;
}

@property(readonly, nonatomic) IGDirectCache *cache; // @synthesize cache=_cache;
@property(readonly, nonatomic) IGDirectInboxNetworker *inboxNetworker; // @synthesize inboxNetworker=_inboxNetworker;

- (void)appDidFinishLaunchingNotification:(id)arg1;
- (void)appWillEnterForegroundNotification:(id)arg1;
- (void)didLoginSuccessfulNotification:(id)arg1;
- (void)setupNotifications;
- (void)forceRefreshInboxData;
- (void)dealloc;
- (id)init;

@end

