/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "UIScrollView.h"

@class IGCoreTextView, IGProfilePictureImageView, IGRetroRegistrationNextButton, IGRetroRegistrationSignUpViewController, IGRetroRegistrationTextField, IGRetroRegistrationUsernameField, UILabel;

@interface IGRetroRegistrationSignUpScrollView : UIScrollView
{
    IGRetroRegistrationSignUpViewController *_vcDelegate;
    IGRetroRegistrationUsernameField *_usernameField;
    IGRetroRegistrationTextField *_passwordField;
    IGRetroRegistrationTextField *_fullnameField;
    IGRetroRegistrationNextButton *_nextButton;
    IGCoreTextView *_termView;
    IGProfilePictureImageView *_profilePictureView;
    UILabel *_photoLabel;
}

@property(retain, nonatomic) UILabel *photoLabel; // @synthesize photoLabel=_photoLabel;
@property(retain, nonatomic) IGProfilePictureImageView *profilePictureView; // @synthesize profilePictureView=_profilePictureView;
@property(retain, nonatomic) IGCoreTextView *termView; // @synthesize termView=_termView;
@property(retain, nonatomic) IGRetroRegistrationNextButton *nextButton; // @synthesize nextButton=_nextButton;
@property(retain, nonatomic) IGRetroRegistrationTextField *fullnameField; // @synthesize fullnameField=_fullnameField;
@property(retain, nonatomic) IGRetroRegistrationTextField *passwordField; // @synthesize passwordField=_passwordField;
@property(retain, nonatomic) IGRetroRegistrationUsernameField *usernameField; // @synthesize usernameField=_usernameField;
//@property(nonatomic) __weak IGRetroRegistrationSignUpViewController *vcDelegate; // @synthesize vcDelegate=_vcDelegate;
//- (void).cxx_destruct;
- (id)pictureView;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

