/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "UIView.h"

@interface TPBottomBar : UIView
{
    int _orientation;
    int _style;
}

+ (id)_backgroundImage;
+ (void)preloadImages;
+ (float)defaultHeightForStyle:(int)arg1 orientation:(int)arg2;
+ (float)defaultHeightForStyle:(int)arg1;
+ (float)defaultHeightForOrientation:(int)arg1;
+ (float)defaultHeight;
+ (int)fullscreenStyle;
+ (int)overlayStyle;
- (id)initWithDefaultSize;
- (id)initWithDefaultSizeForOrientation:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 style:(int)arg2;
- (id)init;
- (void)setOrientation:(int)arg1 updateFrame:(BOOL)arg2;
- (void)setOrientation:(int)arg1;
- (int)orientation;
- (void)drawRect:(struct CGRect)arg1;

@end

