/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "Attachment.h"
//
//#import "OutgoingAttachment-Protocol.h"

@class Photo;

@interface PhotoAttachment //: Attachment //<OutgoingAttachment>
{
    Photo *_photo;
    long long _attachedTimestamp;
}

+ (id)mimeType;
@property(retain, nonatomic) Photo *photo; // @synthesize photo=_photo;
- (id)attachmentData;
- (id)attachmentFilename;
- (id)attachmentHandle;
- (void)addAsAttachFile:(id)arg1;
- (void)addAsParamsToDictionary:(id)arg1;
- (void)addAsParamsToRequest:(id)arg1;
- (id)getThumbnailOfSize:(struct CGSize)arg1;
- (void)dealloc;
- (id)init;

@end

