/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:45 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@interface LSApplicationWorkspace : NSObject
+(id)defaultWorkspace;
-(char)establishConnection;
-(id)remoteObserver;
-(id)pluginsWithIdentifiers:(id)arg1 protocols:(id)arg2 version:(id)arg3 applyFilter:(/*^block*/id)arg4 ;
-(id)operationToOpenResource:(id)arg1 usingApplication:(id)arg2 uniqueDocumentIdentifier:(id)arg3 userInfo:(id)arg4 delegate:(id)arg5 ;
-(id)operationToOpenResource:(id)arg1 usingApplication:(id)arg2 uniqueDocumentIdentifier:(id)arg3 userInfo:(id)arg4 ;
-(char)installApplication:(id)arg1 withOptions:(id)arg2 error:(id*)arg3 usingBlock:(/*^block*/id)arg4 ;
-(id)installProgressForApplication:(id)arg1 withPhase:(unsigned)arg2 ;
-(char)uninstallApplication:(id)arg1 withOptions:(id)arg2 usingBlock:(/*^block*/id)arg3 ;
-(char)registerApplicationDictionary:(id)arg1 withObserverNotification:(unsigned)arg2 ;
-(char)installPhaseFinishedForProgress:(id)arg1 ;
-(void)clearCreatedProgressForBundleID:(id)arg1 ;
-(void)removeInstallProgressForBundleID:(id)arg1 ;
-(void)getKnowledgeUUID:(id*)arg1 andSequenceNumber:(id*)arg2 ;
-(id)delegateProxy;
-(id)applicationForOpeningResource:(id)arg1 ;
-(id)directionsApplications;
-(id)applicationsWithUIBackgroundModes;
-(id)applicationsWithAudioComponents;
-(id)applicationsWithSettingsBundle;
-(id)applicationsWithVPNPlugins;
-(id)applicationsWithExternalAccessoryProtocols;
-(id)applicationForUserActivityType:(id)arg1 ;
-(id)applicationForUserActivityDomainName:(id)arg1 ;
-(id)applicationsOfType:(unsigned)arg1 ;
-(id)pluginsWithIdentifiers:(id)arg1 protocols:(id)arg2 version:(id)arg3 withFilter:(/*^block*/id)arg4 ;
-(id)pluginsWithIdentifiers:(id)arg1 protocols:(id)arg2 version:(id)arg3 ;
-(char)openApplicationWithBundleID:(id)arg1 ;
-(id)installedVPNPlugins;
-(id)placeholderApplications;
-(id)unrestrictedApplications;
-(id)allApplications;
-(id)publicURLSchemes;
-(char)getClaimedActivityTypes:(id*)arg1 domains:(id*)arg2 ;
-(char)installApplication:(id)arg1 withOptions:(id)arg2 ;
-(char)installApplication:(id)arg1 withOptions:(id)arg2 error:(id*)arg3 ;
-(char)uninstallApplication:(id)arg1 withOptions:(id)arg2 ;
-(char)registerApplication:(id)arg1 ;
-(char)registerPlugin:(id)arg1 ;
-(char)unregisterPlugin:(id)arg1 ;
-(char)updateSINFWithData:(id)arg1 forApplication:(id)arg2 options:(id)arg3 error:(id*)arg4 ;
-(char)invalidateIconCache:(id)arg1 ;
-(void)clearAdvertisingIdentifier;
-(void)_clearCachedAdvertisingIdentifier;
-(id)deviceIdentifierForAdvertising;
-(id)installProgressForBundleID:(id)arg1 makeSynchronous:(unsigned char)arg2 ;
-(char)_LSPrivateRebuildApplicationDatabasesForSystemApps:(char)arg1 internal:(char)arg2 user:(char)arg3 ;
-(id)applicationsAvailableForHandlingURLScheme:(id)arg1 ;
-(id)privateURLSchemes;
-(id)URLOverrideForURL:(id)arg1 ;
-(char)openURL:(id)arg1 ;
-(void)removeObserver:(id)arg1 ;
-(id)deviceIdentifierForVendor;
-(id)applicationsAvailableForOpeningDocument:(id)arg1 ;
-(id)operationToOpenResource:(id)arg1 usingApplication:(id)arg2 uniqueDocumentIdentifier:(id)arg3 sourceIsManaged:(char)arg4 userInfo:(id)arg5 delegate:(id)arg6 ;
-(char)openURL:(id)arg1 withOptions:(id)arg2 ;
-(char)openSensitiveURL:(id)arg1 withOptions:(id)arg2 ;
-(id)allInstalledApplications;
-(void)addObserver:(id)arg1 ;
-(id)operationToOpenResource:(id)arg1 usingApplication:(id)arg2 userInfo:(id)arg3 ;
-(char)registerApplicationDictionary:(id)arg1 ;
-(char)unregisterApplication:(id)arg1 ;
-(char)applicationIsInstalled:(id)arg1 ;
-(void)enumerateBundlesOfType:(unsigned)arg1 usingBlock:(/*^block*/id)arg2 ;
-(id)installedPlugins;
-(void)_LSClearSchemaCaches;
@end

