/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import "UITableViewDelegate.h"
//#import "UITableViewDataSource.h"
//#import "FSRootWelcomeController.h"
//#import "UIScrollViewDelegate.h"
//#import "Foursquare-Structs.h"
//#import "UITextFieldDelegate.h"

@class SignupTextInputCell, UILabel, UIActivityIndicatorView;

@interface SigninViewController : NSObject { //FSRootWelcomeController <UITextFieldDelegate, UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource> {
	SignupTextInputCell* usernameCell;
	SignupTextInputCell* passwordCell;
	UIActivityIndicatorView* activity;
	UILabel* errorLabel;
}
@property(retain, nonatomic) UILabel* errorLabel;
@property(retain, nonatomic) UIActivityIndicatorView* activity;
@property(retain, nonatomic) SignupTextInputCell* passwordCell;
@property(retain, nonatomic) SignupTextInputCell* usernameCell;
//-(void).cxx_destruct;
-(BOOL)initializedWithEmail;
-(void)setupCells;
-(void)refreshFail;
-(void)refresh;
-(void)openForgotPasswordURL;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)bottom;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)authenticate;
-(void)cancel;
-(id)metricsName;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)initWithEmail:(id)email;
@end

