//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  4 2016 10:44:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class IRCollation, NSString, Schema;

@interface UserPrivate : NSObject
{
    Schema *_schema;
    id _peer;
}

+ (id)userPrivateForKey:(id)arg1;
- (id)proxy;

@property(readonly, nonatomic) IRCollation *devices;
@property(readonly, nonatomic) IRCollation *accounts;
@property(readonly, nonatomic) _Bool reverseLookupEnabled;
@property(readonly, nonatomic) IRCollation *discoverableAccounts;
@property(readonly, nonatomic) _Bool hasMobileApp;
@property(readonly, nonatomic) long long homeLastViewedItemId;
@property(readonly, nonatomic) NSString *familyName;
@property(readonly, nonatomic) NSString *givenName;
@property(readonly, nonatomic) NSString *userId;
- (id)peer;
- (void)dealloc;
- (id)initWithSchema:(id)arg1 peer:(id)arg2;

@end

