/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:09 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface IMAttachment : NSObject {

	NSString* _guid;
	NSString* _path;

}
-(void)dealloc;
-(id)description;
-(id)path;
-(id)guid;
-(id)fileTransfer;
-(id)initWithPath:(id)arg1 guid:(id)arg2 ;
@end

