/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"
#import <Foundation/Foundation.h>

//#import "BBObserverDelegate-Protocol.h"
//#import "SBBulletinBusyClient-Protocol.h"
//#import "SBBulletinWindowClient-Protocol.h"
//#import "UIGestureRecognizerDelegate-Protocol.h"

@class BBObserver, NSMutableArray, NSMutableSet, SBBannerAndShadowView, UIView;

@interface SBBulletinBannerController : NSObject //<BBObserverDelegate, SBBulletinWindowClient, SBBulletinBusyClient, UIGestureRecognizerDelegate>
{
    BBObserver *_observer;
    NSMutableArray *_incomingBulletinQueue;
    SBBannerAndShadowView *_bannerAndShadowView;
    UIView *_snapshotView;
    BOOL _dismissalOverdue;
    BOOL _replaceDelayIsActive;
    BOOL _soundIsPlaying;
    BOOL _assistantIsVisible;
    BOOL _inhospitableDisplayIsFrontmost;
    BOOL _deviceIsLocked;
    NSMutableSet *_sectionIDsToPend;
    float _showcaseHeight;
}

+ (id)_sharedInstanceCreateIfNecessary:(BOOL)arg1;
+ (id)sharedInstance;
+ (id)sharedInstanceIfExists;
- (id)init;
- (void)dealloc;
- (BOOL)isShowingBanner;
- (void)showTestBanner;
- (void)dismissBanner;
- (void)dismissBannerWithAnimation:(int)arg1;
- (void)setBannerAlpha:(float)arg1;
- (id)newBannerSnapshotViewRotatedForOrientation:(int)arg1;
- (void)adjustLayoutForShowcaseHeight:(float)arg1;
- (unsigned int)_indexOfIncomingBulletinID:(id)arg1;
- (void)_removeEnqueuedBulletin:(id)arg1;
- (BOOL)_replaceEnqueuedBulletin:(id)arg1;
- (void)_enqueueBulletin:(id)arg1;
- (void)_dequeueBulletinIfPossible;
- (void)_presentBannerForItem:(id)arg1;
- (void)_setBannerTranslation:(float)arg1 progress:(float)arg2;
- (float)_progressForBannerTranslation:(float)arg1 maxTranslation:(float)arg2;
- (void)_adjustShadowAlphasForProgress:(float)arg1;
- (void)_handleBannerPanGesture:(id)arg1;
- (void)_handleBannerTapGesture:(id)arg1;
- (void)_tryToDismissBannerWithAnimation:(int)arg1;
- (void)_dismissIntervalElapsed;
- (void)_replaceIntervalElapsed;
- (void)_bulletinSoundCompleted:(id)arg1;
- (void)_stopCurrentSound;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)bulletinWindowWillRotateToOrientation:(int)arg1;
- (void)bulletinWindowIsAnimatingRotationToOrientation:(int)arg1;
- (void)bulletinWindowDidRotateFromOrientation:(int)arg1;
- (void)bulletinWindowStoppedBeingBusy;
- (void)observer:(id)arg1 addBulletin:(id)arg2 forFeed:(unsigned int)arg3;
- (void)observer:(id)arg1 modifyBulletin:(id)arg2;
- (void)observer:(id)arg1 removeBulletin:(id)arg2;
- (void)observer:(id)arg1 updateSectionInfo:(id)arg2;
- (BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)arg1;
- (id)observer:(id)arg1 thumbnailSizeConstraintsForAttachmentType:(int)arg2;
- (id)observer:(id)arg1 composedAttachmentImageForType:(int)arg2 thumbnailData:(id)arg3 key:(id)arg4;
- (id)_dequeueNextBulletinItem;
- (struct CGRect)_normalBannerFrameForOrientation:(int)arg1;
- (struct CGRect)_currentBannerFrameForOrientation:(int)arg1;
- (struct CGRect)_calculateFlipRectAndCreateSnapshotViewForBannerFrame:(struct CGRect)arg1 orientation:(int)arg2;
- (void)_setUpPerspectiveForNormalFlipRect:(struct CGRect)arg1;
- (void)_removePerspective;
- (void)_tearDownView;
- (void)_flipToBanner:(id)arg1 animation:(int)arg2;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (id)_meshTransformForDegreesOfRotation:(float)arg1 flipInsets:(struct UIEdgeInsets)arg2 orientation:(int)arg3 topIsLive:(BOOL)arg4;

// for iOS 6.1.2
-(void)_queueBulletin:(id)bulletin;

@end

