/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSURL, NSDate;

@interface OCStatusMessage : NSObject { // XXUnknownSuperclass {
	NSString* _text;
	NSURL* _url;
	NSDate* _date;
	float _contactTextHeight;
}
@property(retain, nonatomic) NSString* text;
@property(retain, nonatomic) NSURL* url;
@property(retain, nonatomic) NSDate* date;
@property(assign, nonatomic) float contactTextHeight;
@property(readonly, retain, nonatomic) NSString* uneditedText;
@property(readonly, retain, nonatomic) NSString* fullText;
-(id)initWithText:(id)text;
-(id)initWithText:(id)text andDate:(id)date;
-(id)initWithText:(id)text andURL:(id)url;
-(id)initWithText:(id)text URL:(id)url andDate:(id)date;
-(oneway void)dealloc;
-(unsigned)hash;
-(id)description;
@end

