/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"
//
//#import "BBMConnectionDelegate-Protocol.h"
//#import "BBMDSMessageConsumer-Protocol.h"

@class BBGDSGeneratedModel, BBMCoreAccessGroup, BBMDSGeneratedModel, BBMUser, NSArray, NSMutableDictionary, NSString;

@interface BBMCoreAccess : NSObject //<BBMConnectionDelegate, BBMDSMessageConsumer>
{
    //NSObject<BBMCoreAccessDelegate> *_delegate;
    BBGDSGeneratedModel *_groupModel;
    BBMCoreAccessGroup *_groupService;
    NSMutableDictionary *_typingNotificationDelegates;
    BBMDSGeneratedModel *_coreModel;
    NSString *_setupError;
}

+ (id)keyPathsForValuesAffectingAllConversations;
+ (id)keyPathsForValuesAffectingCurrentUser;
+ (id)keyPathsForValuesAffectingCurrentUserURI;
+ (id)sharedInstance;
@property(retain, nonatomic) NSString *setupError; // @synthesize setupError=_setupError;
@property(readonly, nonatomic) BBMDSGeneratedModel *coreModel; // @synthesize coreModel=_coreModel;
//- (void).cxx_destruct;
- (void)handleJSONMessage:(id)arg1;
- (void)handleOverflow;
- (void)cleanupTypingDelegates;
- (id)sortUpdates:(id)arg1;
- (id)nonEmptyChatFilter;
- (id)getAvatarFilename;
- (BOOL)isPINCurrentUser:(id)arg1;
- (BOOL)comparePins:(id)arg1 andPin2:(id)arg2;
- (id)savePicToTmpTransferDir:(id)arg1;
- (id)copyFileForUserAvatar:(id)arg1;
- (id)saveAvatarToFileSystem:(id)arg1;
- (id)getFileTransferWithTransferId:(id)arg1;
- (void)fileTransferCancel:(id)arg1;
- (void)fileTransferAccept:(id)arg1 atPath:(id)arg2;
- (void)fileTransferTo:(id)arg1 withDescription:(id)arg2 path:(id)arg3;
- (id)getPictureWithTransferId:(id)arg1;
- (void)resendChatMessageWithConversationUri:(id)arg1 andID:(long long)arg2;
- (void)pictureTransferAcceptWithId:(id)arg1;
- (void)pictureCancel:(id)arg1;
- (void)pictureAcceptHigherQuality:(id)arg1;
- (void)requestHigherQualityForPicture:(id)arg1;
- (void)pictureTransferTo:(id)arg1 withDescription:(id)arg2 path:(id)arg3;
- (void)closeQRCode:(id)arg1;
- (id)openQRCode:(id)arg1;
- (void)deleteChatHistory;
- (void)updateDraftMessageForConversationURI:(id)arg1 withMessage:(id)arg2;
- (void)clearChatSplat;
- (BOOL)hasBBMConversations;
- (void)markInviteRead:(id)arg1;
- (void)sendTypingNotificationForConversationURI:(id)arg1 isTyping:(BOOL)arg2;
- (void)removeTypingNotificationDelegateForConversationURI:(id)arg1;
- (void)addTypingNotificationDelegateForConversationURI:(id)arg1 delegate:(id)arg2;
- (id)generateConversationURI;
- (void)addParticipantsToConversation:(id)arg1 participants:(id)arg2;
- (void)createConference:(id)arg1 participants:(id)arg2;
- (void)endChatForconversationURI:(id)arg1;
- (void)startChatForConversationURI:(id)arg1 withInviteeURI:(id)arg2;
- (void)sendMessage:(id)arg1 toConversationURI:(id)arg2;
- (void)markMessageRead:(id)arg1 withConversationURI:(id)arg2;
- (void)sendStatusMessageForConversationURI:(id)arg1 identifier:(long long)arg2 status:(int)arg3;
- (id)allMessagesForConversationURI:(id)arg1;
- (void)removeConversationForURI:(id)arg1;
- (id)uriForConversationWithIdentifier:(id)arg1;
- (BOOL)isGroupConversationsStateCurrent;
- (BOOL)isConversationsStateCurrent;
- (id)getGroupConversations;
- (id)getConversations;
- (id)getConversationForURI:(id)arg1;
- (id)getLocations;
- (id)getConversationsIncludingGroupConversations:(BOOL)arg1;
- (BOOL)isAllConversationListsStateCurrent;
- (void)removeUserAvatar;
- (void)changeUserAvatar:(id)arg1;
- (id)globalUpdatesFilter;
- (id)globalUpdatesSorter;
- (id)getGlobalUpdates;
- (id)getGroups;
- (id)getFileTransfers;
- (id)getPictures;
- (id)updatesForOtherUsersSorted:(BOOL)arg1;
- (id)updatesForCurrentUser:(BOOL)arg1;
- (id)updatesForUser:(id)arg1 sort:(BOOL)arg2;
- (void)removeUserStatus:(id)arg1;
- (void)updateUserStatus:(id)arg1 showBusy:(BOOL)arg2;
- (void)updateUserStatus:(id)arg1 withText:(id)arg2;
- (void)addUserStatusWithText:(id)arg1;
- (void)contactAcceptInviteId:(id)arg1 securityAnswer:(id)arg2;
- (id)contactsSorter;
- (void)setBlockUpdates:(BOOL)arg1 forContact:(id)arg2;
- (void)removeFromBlockedListContactURI:(id)arg1;
- (void)contactDeletePendingContactInviteId:(id)arg1;
- (void)contactDeleteInviteId:(id)arg1 ignore:(BOOL)arg2 sendResponse:(BOOL)arg3;
- (void)removeContactWithURI:(id)arg1 ignoreFutureInvitation:(BOOL)arg2;
- (void)contactSendInviteWithPin:(id)arg1 greeting:(id)arg2 securityQuestion:(id)arg3 securityAnswer:(id)arg4;
- (void)contactSendInviteWithPin:(id)arg1 qrcodeHash:(id)arg2;
- (id)getPendingContacts;
- (id)getFollowedUsers;
- (id)getIgnoreBlockedContacts;
- (id)getUpdatesBlockedContacts;
- (BOOL)isContactsListCurrent;
- (id)getContacts;
- (void)sendBarcodeScreenStateMessageWithHash:(id)arg1 screenState:(int)arg2;
- (void)sendListChangeMessageWithElements:(id)arg1 fortype:(id)arg2;
- (void)sendListChangeRequestForUserStatus:(id)arg1;
- (void)sendBroadcastMessage:(id)arg1 to:(id)arg2;
- (void)sendListChangeRequestForUserHasNoNewUpdate;
- (void)sendPingMessage:(id)arg1;
- (void)sendWindowStateUpdate:(int)arg1;
@property(nonatomic) BOOL hasNewUpdate;
@property(nonatomic) BOOL hasNewMessage;
- (id)getUserDefinedStatus;
- (id)getPredefinedStatus;
- (void)setIsKeepingChatHistory:(BOOL)arg1;
- (BOOL)isKeepingChatHistory;
- (id)getTempTransferDirectory;
- (BOOL)hasNewInvite;
- (id)localBbid;
- (id)localPin;
- (id)currentUserStatusMessageAsGlobal;
- (id)currentUserStatusFromGlobal;
- (void)changeCurrentUserKey:(id)arg1 toValue:(id)arg2;
@property(readonly) NSArray *currentUserPins;
@property(readonly) BBMUser *currentUser;
@property(readonly) NSString *currentUserURI;
- (void)sendMarkRecentUpdatesReadMessage:(id)arg1;
- (id)getSetupState;
- (id)getCredentialsState;
- (void)sendBBIDCredentials:(id)arg1 token:(id)arg2 pin:(id)arg3;
- (void)sendChangeUsername:(id)arg1;
- (void)sendSetupDeviceSwitch;
- (void)clearSetupErrors;
@property(readonly, nonatomic) BBMCoreAccessGroup *groupService;
- (void)connection:(id)arg1 didSendJSON:(id)arg2;
- (void)connection:(id)arg1 didReceiveJSON:(id)arg2;
- (void)connectionDidConnect:(id)arg1;
- (void)connectionDidDisconnect:(id)arg1;
- (void)closeConnection;
- (void)startConnectionWithDelegate:(id)arg1;
- (id)bbgModel;


// BBM 2.5.0

-(void)pictureTransferTo:(id)to withDescription:(id)description path:(id)path timeLimit:(unsigned)limit;
-(void)sendMessage:(id)message toConversationURI:(id)conversationURI withTimeLimit:(unsigned)timeLimit;
@end

