/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import "CBLTwitterAccountSelectorViewControllerDelegate.h"
//#import "CBLTextInputViewControllerDelegate.h"
//#import "CBLLoginView_Delegate.h"
//#import "CBLBaseViewController.h"
//#import "CBLOAuthServiceWebViewControllerDelegate.h"

@class CBLLoginView;
@protocol CBLAccountSetupDelegate;

__attribute__((visibility("hidden")))
@interface CBLLoginViewController : NSObject { //CBLBaseViewController <CBLLoginView_Delegate, CBLOAuthServiceWebViewControllerDelegate, CBLTextInputViewControllerDelegate, CBLTwitterAccountSelectorViewControllerDelegate> {
	CBLLoginView* _loginView;
	BOOL _isShowingKeyboard;
	id<CBLAccountSetupDelegate> _setupDelegate;
	//id<CBLPresentedViewControllerDelegate> _presentationDelegate;
}
@property(assign, nonatomic) BOOL isShowingKeyboard;
//@property(assign, nonatomic)  id<CBLPresentedViewControllerDelegate> presentationDelegate;
@property(assign, nonatomic)  id<CBLAccountSetupDelegate> setupDelegate;
//-(void).cxx_destruct;
-(void)presentedViewControllerShouldBeDismissed:(id)presentedViewController;
-(void)CBLOAuthServiceWebViewControllerDidFailToGetUserInfo:(id)cbloauthServiceWebViewController error:(id)error;
-(void)CBLOAuthServiceWebViewController:(id)controller didGetUserInfo:(id)info;
-(void)CBLOAuthServiceWebViewControllerDidFailToAuthorize:(id)cbloauthServiceWebViewController error:(id)error;
-(void)CBLOAuthServiceWebViewController:(id)controller didAuthorizeSuccessfullyWithToken:(id)token;
-(id)CBLOAuthServiceURLForOAuthServiceWebViewController:(id)oauthServiceWebViewController;
-(void)showTypoAlertWithSuggestedEmail:(id)suggestedEmail;
-(void)keyboardWillHide:(id)keyboard;
-(void)keyboardWillShow:(id)keyboard;
-(void)CBLTextInputViewControllerDidSaveText:(id)cbltextInputViewController;
-(void)CBLTextInputViewControllerDidCancel;
-(void)forgotPasswordFailure:(id)failure;
-(void)forgotPasswordSuccess;
-(void)loginFailure:(id)failure;
-(void)loginSuccess;
-(void)doneLoggingIn;
-(void)loggingIn;
-(void)CBLTwitterAccountSelectorViewControllerDidSelectAccount:(id)cbltwitterAccountSelectorViewController;
-(void)CBLLoginViewCheckUsername:(id)username;
-(void)CBLLoginViewBackButtonPressed;
-(void)CBLLoginViewForgotPasswordButtonPressed;
-(void)CBLLoginViewCheckEmail:(id)email;
-(void)CBLLoginViewSignInWithEmail:(id)email andPassword:(id)password;
-(void)CBLLoginViewSignupButtonPressed;
-(void)CBLLoginViewRakutenButtonPressed;
-(void)CBLLoginViewTwitterButtonPressed;
-(void)CBLLoginViewFacebookButtonPressed;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)didTapClose:(id)close;
-(void)viewDidLoad;
-(void)viewWillAppear:(BOOL)view;
-(void)dealloc;
@end

