/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:43:23 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/WebUI.framework/WebUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class WBSHistoryItem, NSString;

@interface WBSHistoryVisit : NSObject {

	char _loadSuccessful;
	char _httpNonGet;
	char _synthesized;
	int _databaseID;
	int _redirectSourceDatabaseID;
	int _redirectDestinationDatabaseID;
	WBSHistoryItem* _item;
	int _origin;
	NSString* _title;
	WBSHistoryVisit* _redirectSource;
	WBSHistoryVisit* _redirectDestination;
	long long _generation;
	double _visitTime;

}

@property (assign,nonatomic) int databaseID;                                            //@synthesize databaseID=_databaseID - In the implementation block
@property (assign,nonatomic) int redirectSourceDatabaseID;                              //@synthesize redirectSourceDatabaseID=_redirectSourceDatabaseID - In the implementation block
@property (assign,nonatomic) int redirectDestinationDatabaseID;                         //@synthesize redirectDestinationDatabaseID=_redirectDestinationDatabaseID - In the implementation block
@property (assign,nonatomic) long long generation;                                      //@synthesize generation=_generation - In the implementation block
@property (assign,nonatomic) WBSHistoryItem * item;                              //@synthesize item=_item - In the implementation block
@property (assign,nonatomic) int origin;                                                //@synthesize origin=_origin - In the implementation block
@property (nonatomic,readonly) double visitTime;                                        //@synthesize visitTime=_visitTime - In the implementation block
@property (nonatomic,copy) NSString * title;                                            //@synthesize title=_title - In the implementation block
@property (assign,getter=loadWasSuccessful,nonatomic) char loadSuccessful;              //@synthesize loadSuccessful=_loadSuccessful - In the implementation block
@property (getter=wasHTTPNonGet,nonatomic,readonly) char httpNonGet;                    //@synthesize httpNonGet=_httpNonGet - In the implementation block
@property (getter=isSynthesized,nonatomic,readonly) char synthesized;                   //@synthesize synthesized=_synthesized - In the implementation block
@property (nonatomic,retain) WBSHistoryVisit * redirectSource;                          //@synthesize redirectSource=_redirectSource - In the implementation block
@property (nonatomic,retain) WBSHistoryVisit * redirectDestination;                     //@synthesize redirectDestination=_redirectDestination - In the implementation block
@property (nonatomic,readonly) WBSHistoryVisit * endOfRedirectChain; 
@property (nonatomic,readonly) unsigned redirectSourceChainLength; 
+(id)synthesizedVisitWithHistoryItem:(id)arg1 visitTime:(double)arg2 ;
-(int)databaseID;
-(void)setGeneration:(long long)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(WBSHistoryItem *)item;
-(NSString *)title;
-(int)origin;
-(void)setOrigin:(int)arg1 ;
-(void)setItem:(WBSHistoryItem *)arg1 ;
-(long long)generation;
-(void)setDatabaseID:(int)arg1 ;
-(double)visitTime;
-(char)wasHTTPNonGet;
-(char)loadWasSuccessful;
-(WBSHistoryVisit *)redirectSource;
-(WBSHistoryVisit *)redirectDestination;
-(void)setLoadSuccessful:(char)arg1 ;
-(id)initWithHistoryItem:(id)arg1 visitTime:(double)arg2 loadWasSuccesful:(char)arg3 wasHTTPNonGet:(char)arg4 origin:(int)arg5 ;
-(unsigned)redirectSourceChainLength;
-(id)initWithHistoryItem:(id)arg1 sqliteRow:(id)arg2 baseColumnIndex:(unsigned)arg3 ;
-(WBSHistoryVisit *)endOfRedirectChain;
-(void)setRedirectSource:(WBSHistoryVisit *)arg1 ;
-(void)setRedirectDestination:(WBSHistoryVisit *)arg1 ;
-(int)redirectSourceDatabaseID;
-(int)redirectDestinationDatabaseID;
-(id)initWithHistoryItem:(id)arg1 sqliteRow:(id)arg2 ;
-(char)isSynthesized;
-(id)initWithHistoryItem:(id)arg1 visitTime:(double)arg2 ;
-(void)setRedirectDestinationDatabaseID:(int)arg1 ;
-(void)setRedirectSourceDatabaseID:(int)arg1 ;
@end

