//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  4 2016 10:44:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class FBMSecureThreadKey, MNSecureMessageContent, MNSecureMessageReportableContent, NSString;

@interface MNSecureMessage : NSObject
{
    NSString *_messageId;
    FBMSecureThreadKey *_secureThreadKey;
    NSString *_senderId;
    unsigned long long _timestamp;
    long long _messageLifetime;
    MNSecureMessageContent *_content;
    MNSecureMessageReportableContent *_reportableContent;
}

@property(readonly, copy, nonatomic) MNSecureMessageReportableContent *reportableContent; // @synthesize reportableContent=_reportableContent;
@property(readonly, copy, nonatomic) MNSecureMessageContent *content; // @synthesize content=_content;
@property(readonly, nonatomic) long long messageLifetime; // @synthesize messageLifetime=_messageLifetime;
@property(readonly, nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, copy, nonatomic) NSString *senderId; // @synthesize senderId=_senderId;
@property(readonly, copy, nonatomic) FBMSecureThreadKey *secureThreadKey; // @synthesize secureThreadKey=_secureThreadKey;
@property(readonly, copy, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;

- (void)encodeWithCoder:(id)arg1;
- (id)initWithMessageId:(id)arg1 secureThreadKey:(id)arg2 senderId:(id)arg3 timestamp:(unsigned long long)arg4 messageLifetime:(long long)arg5 content:(id)arg6 reportableContent:(id)arg7;
- (id)initWithCoder:(id)arg1;

@end

