/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import <XXUnknownSuperclass.h> // Unknown library
//#import "LINE-Structs.h"
//#import "TalkFileManagerDelegate.h"

@class UIImage, NSCache;

__attribute__((visibility("hidden")))
@interface TalkImageCacheManager : NSObject /*XXUnknownSuperclass <TalkFileManagerDelegate> */{
	NSCache* cache_;
	UIImage* cachedSkinImage;
}
@property(retain, nonatomic) UIImage* cachedSkinImage;
+(id)allocWithZone:(NSZone*)zone;
+(id)sharedManager;
-(void)clearSkinImageCache;
-(id)backgroundSkinImage;
-(id)backgroundSkinImageWithName:(id)name;
-(void)talkFileManager:(id)manager didFailLoadingWithError:(id)error;
-(void)talkFileManager:(id)manager didFinishLoadingWithData:(id)data url:(id)url scope:(id)scope;
-(void)clearImageCache;
-(void)removeImageForURL:(id)url;
-(void)setImage:(id)image forURL:(id)url dataSize:(unsigned)size;
-(id)imageForURL:(id)url;
-(void)dealloc;
-(id)init;
-(id)autorelease;
-(oneway void)release;
-(unsigned)retainCount;
-(id)retain;
-(id)copyWithZone:(NSZone*)zone;
@end

