/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSManagedObject.h"

@class NSDate, NSNumber, NSSet, NSString;
/*
@interface ABContact : NSManagedObject
{
}*/
@interface ABContact (Viber_5_0_0)
- (void)markAllPhoneNumbersAsBlocked:(BOOL)arg1;
@property(readonly, nonatomic) BOOL isBlocked;
@property(readonly, nonatomic) id iconCacheEntity;
@property(readonly, nonatomic) BOOL isViber;
@property(readonly, nonatomic) NSString *firstName;
- (id)viberIconIndex;
@property(readonly, nonatomic) NSString *viberIconId;
@property(readonly, nonatomic) NSString *iconPath;

// Remaining properties
@property(retain, nonatomic) NSString *companyKind; // @dynamic companyKind;
@property(retain, nonatomic) NSNumber *isIcon; // @dynamic isIcon;
@property(retain, nonatomic) NSNumber *isViberIcon; // @dynamic isViberIcon;
@property(retain, nonatomic) NSString *mainName; // @dynamic mainName;
@property(retain, nonatomic) NSDate *modifcationDate; // @dynamic modifcationDate;
@property(retain, nonatomic) NSSet *phoneNumbers; // @dynamic phoneNumbers;
@property(retain, nonatomic) NSString *phoneticName; // @dynamic phoneticName;
@property(retain, nonatomic) NSString *prefixName; // @dynamic prefixName;
@property(retain, nonatomic) NSNumber *recordID; // @dynamic recordID;
@property(retain, nonatomic) NSNumber *sortOrder; // @dynamic sortOrder;
@property(retain, nonatomic) NSSet *sources; // @dynamic sources;
@property(retain, nonatomic) NSString *suffixName; // @dynamic suffixName;

@end

