/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */
//
//#import <XXUnknownSuperclass.h> // Unknown library
//#import "MediaDataSource.h"
//#import "MediaDelegate.h"
//#import "MediaUploadDelegate.h"
//#import "MediaImageProcessingDelegate.h"
//#import "NSCoding.h"
//#import "SnapVideoFilterDelegate.h"

@class Media, NSMutableDictionary, SnapVideoFilter, NSMutableArray, NSString, NSDate;

__attribute__((visibility("hidden")))
@interface EphemeralMedia : NSObject { // XXUnknownSuperclass <SnapVideoFilterDelegate, MediaDataSource, MediaDelegate, MediaUploadDelegate, MediaImageProcessingDelegate, NSCoding> {
	Media* _media;
	NSString* __id;
	NSString* _captionText;
	NSString* _clientId;
	EphemeralMedia* _doublePostParent;
	int _ephemeralMediaState;
	unsigned _numberOfTimesReloaded;
	Media* _thumbnailMedia;
	float _time;
	float _timeLeft;
	int _type;
	SnapVideoFilter* _videoFilter;
	float _videoTimeSoFar;
	NSDate* _viewedTimestamp;
	NSMutableDictionary* _secretShareLoggingParams;
	NSMutableDictionary* _shareLoggingParams;
	NSMutableArray* _targets;
	NSMutableArray* _viewingTimestamps;
	double _timeStartedViewing;
}
@property(retain, nonatomic) NSMutableArray* viewingTimestamps;
@property(retain, nonatomic) NSMutableArray* targets;
@property(retain, nonatomic) NSMutableDictionary* shareLoggingParams;
@property(retain, nonatomic) NSMutableDictionary* secretShareLoggingParams;
@property(retain, nonatomic) NSDate* viewedTimestamp;
@property(assign, nonatomic) float videoTimeSoFar;
@property(retain, nonatomic) SnapVideoFilter* videoFilter;
@property(assign, nonatomic) int type;
@property(assign, nonatomic) double timeStartedViewing;
@property(assign, nonatomic) float timeLeft;
@property(assign, nonatomic) float time;
@property(retain, nonatomic) Media* thumbnailMedia;
@property(assign, nonatomic) unsigned numberOfTimesReloaded;
@property(retain, nonatomic) Media* media;
@property(assign, nonatomic) int ephemeralMediaState;
@property(retain, nonatomic) EphemeralMedia* doublePostParent;
@property(retain, nonatomic) NSString* clientId;
@property(retain, nonatomic) NSString* captionText;
@property(retain, nonatomic) NSString* _id;
//-(void).cxx_destruct;
-(void)markViewingTimestamp;
-(id)logId;
-(void)reprocessVideo;
-(id)uploadFailureBlock;
-(id)uploadSuccessBlock;
-(id)uploadParameters;
-(void)setUploading;
-(void)doublePost;
-(void)addTarget:(id)target;
-(void)imageProcessingDidSucceedForMedia:(id)imageProcessing;
-(void)uploadMedia;
-(id)username;
-(void)imageProcessingDone;
-(void)mediaUploadDidFailForMedia:(id)mediaUpload;
-(void)mediaUploadDidSucceedForMedia:(id)mediaUpload;
-(int)uploadMediaTypeForMedia:(id)media;
-(id)uploadMediaIdForMedia:(id)media;
-(BOOL)isImage;
-(BOOL)isVideoWithSound;
-(BOOL)isVideoWithNoSound;
-(BOOL)isVideo;
-(BOOL)encrypt;
-(BOOL)persist;
-(BOOL)isSelfEncrypted;
-(id)encryptionDictionaryForMedia:(id)media;
-(id)decryptData:(id)data forMedia:(id)media;
-(id)mediaIdForMedia:(id)media;
-(id)endpointParamsForMedia:(id)media;
-(id)endpointForMedia:(id)media;
-(void)targetSetVideoFilter:(id)filter;
-(void)targetSetMedia:(id)media;
-(void)copyDataFromEphemeralMedia:(id)ephemeralMedia;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)secretShareLoggingParameters;
-(void)addSecretShareLoggingParameters:(id)parameters;
-(id)shareLoggingParameters;
-(void)addShareLoggingParameters:(id)parameters;
-(id)typeParams;
-(id)initWithJSONDictionary:(id)jsondictionary;
-(id)initWithClientId;
-(void)videoProcessingDidFailForSnapVideoFilter:(id)videoProcessing;
-(void)videoProcessingDidSucceedForSnapVideoFilter:(id)videoProcessing data:(id)data;
@end

