/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PHCallViewController.h"

//#import "MFMessageComposeViewControllerDelegate-Protocol.h"
//#import "PHAudioCallControlsViewControllerDelegate-Protocol.h"
//#import "PHAudioRoutingAlertDelegate-Protocol.h"
//#import "TPSuperBottomBarDelegateProtocol-Protocol.h"
//#import "UIPopoverPresentationControllerDelegate-Protocol.h"

@class CALayer, NSLayoutConstraint, NSString, PHAudioCallControlsViewController, PHCallParticipantsViewController, PHInCallKeypadViewController, TPSuperBottomBar, TUCall, UIImageView, UIView, UIVisualEffectView;

@interface PHAudioCallViewController : PHCallViewController //<MFMessageComposeViewControllerDelegate, PHAudioRoutingAlertDelegate, UIPopoverPresentationControllerDelegate, TPSuperBottomBarDelegateProtocol, PHAudioCallControlsViewControllerDelegate>
{
    unsigned short _currentState;
    unsigned short _middleViewState;
    TUCall *_disconnectedCallToMessage;
    TPSuperBottomBar *_bottomBar;
    UIView *_currentMiddleView;
    PHCallParticipantsViewController *_callParticipantsViewController;
    PHCallParticipantsViewController *_callWaitingParticipantsViewController;
    NSLayoutConstraint *_participantsViewYAdjustmentConstraint;
    PHAudioCallControlsViewController *_buttonsViewController;
    PHInCallKeypadViewController *_keypadViewController;
    TUCall *_callForBackgroundImage;
    UIImageView *_backgroundImageView;
    UIVisualEffectView *_backgroundEffectView;
    CALayer *_backgroundImageFilterLayer;
}

@property(retain, nonatomic) CALayer *backgroundImageFilterLayer; // @synthesize backgroundImageFilterLayer=_backgroundImageFilterLayer;
@property(retain, nonatomic) UIVisualEffectView *backgroundEffectView; // @synthesize backgroundEffectView=_backgroundEffectView;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(retain, nonatomic) TUCall *callForBackgroundImage; // @synthesize callForBackgroundImage=_callForBackgroundImage;
@property(retain, nonatomic) PHInCallKeypadViewController *keypadViewController; // @synthesize keypadViewController=_keypadViewController;
@property(retain, nonatomic) PHAudioCallControlsViewController *buttonsViewController; // @synthesize buttonsViewController=_buttonsViewController;
@property(retain) NSLayoutConstraint *participantsViewYAdjustmentConstraint; // @synthesize participantsViewYAdjustmentConstraint=_participantsViewYAdjustmentConstraint;
@property(retain) PHCallParticipantsViewController *callWaitingParticipantsViewController; // @synthesize callWaitingParticipantsViewController=_callWaitingParticipantsViewController;
@property(retain) PHCallParticipantsViewController *callParticipantsViewController; // @synthesize callParticipantsViewController=_callParticipantsViewController;
@property(nonatomic) unsigned short middleViewState; // @synthesize middleViewState=_middleViewState;
@property(retain) UIView *currentMiddleView; // @synthesize currentMiddleView=_currentMiddleView;
@property(retain) TPSuperBottomBar *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(retain) TUCall *disconnectedCallToMessage; // @synthesize disconnectedCallToMessage=_disconnectedCallToMessage;
@property(nonatomic) unsigned short currentState; // @synthesize currentState=_currentState;
//- (void).cxx_destruct;
- (void)stopSuppressionOfSTKAlerts;
- (void)startSuppressionOfSTKAlerts;
- (void)setupDeviceController;
- (id)hideActionTitleForAudioRoutingAlertController:(id)arg1;
- (void)popoverPresentationControllerDidDismissPopover:(id)arg1;
- (void)audioRoutingAlertControllerDidDismiss:(id)arg1;
- (void)audioRoutingAlertController:(id)arg1 didSelectAction:(id)arg2;
- (void)revealAudioRoutingDeviceListAnimated:(BOOL)arg1;
- (void)_sheetCancel;
- (void)_autodismissAudioMenu;
- (void)setupAutodismissRoutingTimer;
- (void)resetAutodismissTimer;
- (void)handleProximityChangedNotification:(id)arg1;
- (void)hardwareButtonEventNotification:(id)arg1;
- (int)desiredButtonEvents;
- (BOOL)allowsBanners;
- (BOOL)allowsMenuButtonDismissal;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2;
- (void)_leaveMessage;
- (id)customizedTitleForItemInBar:(id)arg1 withActionType:(int)arg2;
- (BOOL)shouldShowHardPauseNumbers;
- (void)bottomBarActionPerformed:(int)arg1 fromBar:(id)arg2;
- (void)sliderActionFromBar:(id)arg1 slidToProportion:(float)arg2;
- (void)setMiddleViewState:(unsigned short)arg1 animated:(BOOL)arg2 completion:(id)arg3;
- (void)setMiddleViewState:(unsigned short)arg1 animated:(BOOL)arg2;
- (void)audioCallControlsViewControllerRequestedAudioRoutesPresentation:(id)arg1;
- (void)audioCallControlsViewControllerRequestedAddCallPresentation:(id)arg1;
- (void)audioCallControlsViewControllerRequestedContactsPresentation:(id)arg1;
- (void)audioCallControlsViewControllerRequestedKeypadPresentationForFieldMode:(id)arg1;
- (void)audioCallControlsViewControllerRequestedKeypadPresentation:(id)arg1;
- (int)bottomBarStateForCallWaitingCall;
- (void)setShowsCallWaitingParticipantView:(BOOL)arg1;
- (id)isolatedCall;
- (void)setBackgroundImage:(id)arg1;
- (BOOL)setCallForBackgroundImage:(id)arg1 animated:(BOOL)arg2 blurred:(BOOL)arg3;
@property(readonly, nonatomic, getter=isShowingBackgroundImage) BOOL showingBackgroundImage;
@property(readonly, nonatomic) BOOL canShowBackgroundImage;
- (void)setCurrentState:(unsigned short)arg1 animated:(BOOL)arg2;
- (void)updateCurrentState;
- (void)callContinuityStateChangedNotification:(id)arg1;
- (void)hardPauseControllerChangedNotification:(id)arg1;
- (void)callCenterCallStatusChangedNotification:(id)arg1;
- (void)wantsHoldMusicChangedNotification:(id)arg1;
- (id)dismissalAssertionReason;
- (BOOL)needsDismissalAssertion;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (unsigned int)supportedInterfaceOrientations;
- (void)_testing_didTransitionToIncomingRingingCallState:(id)arg1;
- (void)_testing_didTransitionToEndedCallState;
- (void)_testing_didTransitionToEndingCallState;
- (void)_testing_didTransitionToActiveCallState:(id)arg1;
- (void)_testing_finishedAnimatingToActiveCallState;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

