/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"
//
//#import "SBBulletinAlertHandler-Protocol.h"
//#import "SBPluginBundleController-Protocol.h"

@class AVController, BBBulletin, NSMutableArray, PCPersistentTimer;

@interface SMSPluginManager : NSObject //<SBPluginBundleController, SBBulletinAlertHandler>
{
    PCPersistentTimer *_smsSoundWakeTimers[10];
    BOOL _displayExtraAlerts;
    BBBulletin *_lastBulletin;
    NSMutableArray *_cmasMessages;
    BOOL _displayingCMASAlert;
    AVController *_alertToneController;
    PCPersistentTimer *_cmasSoundTimer;
}

+ (void)awakeFromBundle;
+ (BOOL)carrierSMSReceiveOnlyEnabled;
+ (id)sharedInstance;
+ (double)_downgradeServerStartupDelay;
- (id)init;
- (void)dealloc;
- (void)_addCMASMessage:(id)arg1;
- (void)_removeCMASMessage:(id)arg1;
- (void)_cellBroadcastMessageReceived:(id)arg1;
- (void)_cellBroadcastMessageAlertDismissed:(id)arg1;
- (void)_displayNextCMASAlert;
- (void)applicationLaunched:(id)arg1;
- (void)messageReceived:(id)arg1;
- (void)volumeChanged:(id)arg1;
- (void)cancelScheduledSMSSounds:(id)arg1;
- (void)preferencesChanged:(id)arg1;
- (void)postAlertForMessageWithDictionary:(id)arg1;
- (BOOL)isAlertCountValid:(int)arg1;
- (void)cancelScheduledSMSSounds;
- (void)redisplayAllMessagesForCarrierSMSReceiveOnlyMode;
- (BOOL)bindBulletin:(id)arg1 forRegistry:(id)arg2;
- (void)handleEvent:(int)arg1 withBulletin:(id)arg2 forRegistry:(id)arg3;
- (void)markMessageAsRead:(id)arg1;
- (void)deleteMessage:(id)arg1 deleteConversationIfEmpty:(BOOL)arg2;
- (void)_cleanupIfNecessary;
- (void)_deleteUnusedPlaceholdersIfNecessary;
- (void)_deleteUnusedGroupsIfNecessary;
- (void)cancelCMASSound;
- (void)cancelCMASSoundFromTimer:(id)arg1;
- (void)_playCMASAlertSound;
- (id)_lookupAlertToneInCarrierBundle;

@end

