/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:37:45 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


#import "MobileCoreServices-Structs.h"
@class NSString, NSURL, NSDictionary, NSArray, LSApplicationProxy;

@interface LSResourceProxy : NSObject {

	NSString* _localizedName;
	NSString* _boundApplicationIdentifier;
	NSURL* _boundContainerURL;
	NSURL* _boundDataContainerURL;
	NSURL* _boundResourcesDirURL;
	NSDictionary* _boundIconsDictionary;
	NSString* _boundIconCacheKey;
	NSArray* _boundIconFileNames;
	LSApplicationProxy* _typeOwner;
	char _boundIconIsPrerendered;
	char _boundIconIsBadge;

}

@property (nonatomic,readonly) NSString * localizedName;                    //@synthesize localizedName=_localizedName - In the implementation block
@property (nonatomic,readonly) char boundIconIsBadge; 
@property (nonatomic,readonly) NSDictionary * iconsDictionary; 
+(int)_compareApplicationIconCanvasSize:(CGSize)arg1 withSize:(CGSize)arg2 ;
+(CGSize)_applicationIconCanvasSize;
-(SCD_Struct_LS2*)_iconDefinitionForSize:(CGSize)arg1 style:(id)arg2 ;
-(SCD_Struct_LS2*)_iconVariantDefinitions:(id)arg1 ;
-(CGSize)_largestImageSize:(id)arg1 ;
-(CGSize)_defaultStyleSize:(id)arg1 ;
-(id)_iconForStyle:(id)arg1 size:(CGSize)arg2 ;
-(id)_iconForStyle:(id)arg1 ;
-(void)setBoundApplicationIdentifier:(id)arg1 ;
-(void)setBoundContainerURL:(id)arg1 ;
-(void)setBoundDataContainerURL:(id)arg1 ;
-(void)setBoundResourcesDirectoryURL:(id)arg1 ;
-(void)setBoundIconsDictionary:(id)arg1 ;
-(void)setBoundIconCacheKey:(id)arg1 ;
-(void)setBoundIconFileNames:(id)arg1 ;
-(void)setTypeOwner:(id)arg1 ;
-(void)setBoundIconIsPrerendered:(char)arg1 ;
-(void)setBoundIconIsBadge:(char)arg1 ;
-(id)_initWithLocalizedName:(id)arg1 boundApplicationIdentifier:(id)arg2 boundContainerURL:(id)arg3 dataContainerURL:(id)arg4 boundResourcesDirectoryURL:(id)arg5 boundIconsDictionary:(id)arg6 boundIconCacheKey:(id)arg7 boundIconFileNames:(id)arg8 typeOwner:(id)arg9 boundIconIsPrerendered:(char)arg10 boundIconIsBadge:(char)arg11 ;
-(id)boundIconsDictionary;
-(id)typeOwner;
-(id)boundResourcesDirectoryURL;
-(id)boundApplicationIdentifier;
-(id)boundContainerURL;
-(id)iconStyleDomain;
-(id)boundIconCacheKey;
-(char)boundIconIsPrerendered;
-(id)boundIconFileNames;
-(id)boundDataContainerURL;
-(id)_initWithLocalizedName:(id)arg1 ;
-(void)setLocalizedName:(NSString *)arg1 ;
-(NSDictionary *)iconsDictionary;
-(void)dealloc;
-(id)iconDataForVariant:(int)arg1 ;
-(NSString *)localizedName;
-(char)boundIconIsBadge;
-(id)iconDataForStyle:(id)arg1 width:(int)arg2 height:(int)arg3 options:(unsigned)arg4 ;
@end

