//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  4 2016 10:44:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSUserDefaults;

@interface IGUserDefaults : NSObject
{
    NSUserDefaults *_appGroupUserDefaults;
}

+ (id)sharedIGUserDefaults;
@property(readonly, nonatomic) NSUserDefaults *appGroupUserDefaults; // @synthesize appGroupUserDefaults=_appGroupUserDefaults;

- (void)removeObjectForKey:(id)arg1 inUserInfoForService:(id)arg2;
- (void)deleteUserInfoForService:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2 andService:(id)arg3;
- (void)setUserInfo:(id)arg1 forService:(id)arg2;
- (id)objectForKey:(id)arg1 andService:(id)arg2;
- (id)userInfoForService:(id)arg1;
- (_Bool)hasAccessTokenExpiredForService:(id)arg1;
- (void)deleteAccessTokenForService:(id)arg1;
- (void)setRefreshToken:(id)arg1 forService:(id)arg2;
- (void)setAccessToken:(id)arg1 forService:(id)arg2;
- (void)setAccessTokenExpiration:(int)arg1 forService:(id)arg2;
- (void)expireAccessTokenForService:(id)arg1;
- (void)setAccessTokenWithExpiration:(id)arg1 expirationInSeconds:(int)arg2 forService:(id)arg3;
- (id)refreshTokenForService:(id)arg1;
- (id)accessTokenForService:(id)arg1;
- (void)deletePasswordForUsername:(id)arg1 andService:(id)arg2;
- (void)setUsername:(id)arg1 andPassword:(id)arg2 forService:(id)arg3;
- (id)passwordForUsername:(id)arg1 andService:(id)arg2;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (void)setDouble:(double)arg1 forkey:(id)arg2;
- (double)doubleForKey:(id)arg1;
- (void)setInteger:(long long)arg1 forKey:(id)arg2;
- (long long)integerForKey:(id)arg1;
- (void)setBool:(_Bool)arg1 forKey:(id)arg2;
- (_Bool)boolForKey:(id)arg1;
- (id)currentUserPK;
- (id)userInfoKeyForService:(id)arg1;
- (id)userPrefixedKey:(id)arg1;
- (void)migrateToSharedStorage;
- (id)init;

@end

