/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSManagedObject.h"

@class NSData, NSDate, NSNumber, NSString, WAMediaItemMetadata;
/*
@interface WAMediaItem : NSManagedObject
{
    WAMediaItemMetadata *_decodedMetadata;
    _Bool _mediaSaved;
    int _httpRetryCount;
    NSString *_mediaHostIp;
}*/
@interface WAMediaItem (WhatsApp_2_16_2)
@property(nonatomic) int httpRetryCount; // @synthesize httpRetryCount=_httpRetryCount;
@property(retain, nonatomic) NSString *mediaHostIp; // @synthesize mediaHostIp=_mediaHostIp;
@property(nonatomic, getter=isMediaSaved) _Bool mediaSaved; // @synthesize mediaSaved=_mediaSaved;
//- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *matchedText;
@property(readonly, nonatomic) NSString *canonicalURL;
@property(readonly, nonatomic) NSString *snippet;
@property(copy, nonatomic) WAMediaItemMetadata *decodedMetadata;
@property(readonly, nonatomic) struct CGSize mediaSize;

// Remaining properties
@property(retain, nonatomic) NSString *authorName; // @dynamic authorName;
@property(retain, nonatomic) NSString *collectionName; // @dynamic collectionName;
@property(retain, nonatomic) NSNumber *fileSize; // @dynamic fileSize;
//@property(retain, nonatomic) NSNumber *latitude; // @dynamic latitude;
//@property(retain, nonatomic) NSNumber *longitude; // @dynamic longitude;
@property(retain, nonatomic) NSData *mediaKey; // @dynamic mediaKey;
@property(retain, nonatomic) NSString *mediaLocalPath; // @dynamic mediaLocalPath;
@property(retain, nonatomic) NSNumber *mediaOrigin; // @dynamic mediaOrigin;
@property(retain, nonatomic) NSString *mediaURL; // @dynamic mediaURL;
@property(retain, nonatomic) NSDate *mediaUrlDate; // @dynamic mediaUrlDate;
@property(retain, nonatomic) NSData *metadata; // @dynamic metadata;
@property(retain, nonatomic) NSNumber *movieDuration; // @dynamic movieDuration;
@property(retain, nonatomic) NSString *thumbnailLocalPath; // @dynamic thumbnailLocalPath;
@property(retain, nonatomic) NSString *title; // @dynamic title;
@property(retain, nonatomic) NSString *vCardName; // @dynamic vCardName;
@property(retain, nonatomic) NSString *vCardString; // @dynamic vCardString;
@property(retain, nonatomic) NSString *xmppThumbPath; // @dynamic xmppThumbPath;

@end

