/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"

@class TMAPIClient, TMDataHelper, TMPreferences;

@interface TMUserAuthenticationController : NSObject
{
    BOOL _userWasLoggedIn;
    TMPreferences *_preferences;
    TMDataHelper *_dataHelper;
    TMAPIClient *_APIClient;
}

@property(nonatomic) BOOL userWasLoggedIn; // @synthesize userWasLoggedIn=_userWasLoggedIn;
@property(retain, nonatomic) TMAPIClient *APIClient; // @synthesize APIClient=_APIClient;
@property(retain, nonatomic) TMDataHelper *dataHelper; // @synthesize dataHelper=_dataHelper;
@property(retain, nonatomic) TMPreferences *preferences; // @synthesize preferences=_preferences;
//- (void).cxx_destruct;
- (void)checkForLoginStateChange:(id)arg1;
- (void)captureLoginState;
- (void)logout;
- (id)init;
- (id)initWithPreferences:(id)arg1 APIClient:(id)arg2 dataHelper:(id)arg3;

@end

