/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import "LIMetrics2Provider.h"
//#import "LICommonViewController.h"
//#import "LIOnboardingViewControllerDelegate.h"
//#import "LinkedIn-Structs.h"
//#import "UITextFieldDelegate.h"

@class UILabel, UIView, LISpinnerView, LIAuthSSOSessionInfo, UITextField, UIButton, UIImageView;
@protocol LILoginV2ViewControllerDelegate;

@interface LILoginV2ViewController : NSObject { //LICommonViewController <LIOnboardingViewControllerDelegate, UITextFieldDelegate, LIMetrics2Provider> {
	BOOL _signInVisible;
	BOOL _forceSignIn;
	BOOL _finishedFirstAnimations;
	BOOL _firstTimeBlink;
	BOOL _isOnFirstPage;
	BOOL _didAutomaticAnimation;
	id<LILoginV2ViewControllerDelegate> _delegate;
	int _currentScreen;
	UIView* _ssoScreen;
	UIView* _signInScreen;
	UIView* _usernamePasswordScreen;
	UIImageView* _logo;
	UIImageView* _signInBackground;
	UIImageView* _signBluredInBackground;
	UIImageView* _textFieldBG;
	UIButton* _fakeSignInButton;
	UIButton* _realSignInButton;
	UIButton* _signUpButton;
	UITextField* _usernameField;
	UITextField* _passwordField;
	UIView* _fieldsView;
	UIButton* _forgotPasswordButton;
	UIButton* _showUnshowPasswordMaskButton;
	UIView* _whiteAlphaView;
	UILabel* _forProfesionals;
	UIView* _greyNextToText;
	LISpinnerView* _progressSpinner;
	int _numLoginAttempts;
	UILabel* _ssoLoggedInUserLabel;
	UIButton* _ssoContinueButton;
	UIButton* _ssoNotYouButton;
	UIButton* _ssoSignUpButton;
	LIAuthSSOSessionInfo* _ssoSessionToUse;
}
@property(retain, nonatomic) LIAuthSSOSessionInfo* ssoSessionToUse;
@property(assign, nonatomic) BOOL didAutomaticAnimation;
@property(assign, nonatomic) BOOL isOnFirstPage;
@property(assign, nonatomic)  UIButton* ssoSignUpButton;
@property(assign, nonatomic)  UIButton* ssoNotYouButton;
@property(assign, nonatomic)  UIButton* ssoContinueButton;
@property(assign, nonatomic)  UILabel* ssoLoggedInUserLabel;
@property(assign, nonatomic) int numLoginAttempts;
@property(assign, nonatomic) BOOL firstTimeBlink;
@property(assign, nonatomic) BOOL finishedFirstAnimations;
@property(retain, nonatomic) LISpinnerView* progressSpinner;
@property(assign, nonatomic)  UIView* greyNextToText;
@property(assign, nonatomic)  UILabel* forProfesionals;
@property(assign, nonatomic)  UIView* whiteAlphaView;
@property(assign, nonatomic)  UIButton* showUnshowPasswordMaskButton;
@property(assign, nonatomic)  UIButton* forgotPasswordButton;
@property(assign, nonatomic)  UIView* fieldsView;
@property(assign, nonatomic)  UITextField* passwordField;
@property(assign, nonatomic)  UITextField* usernameField;
@property(assign, nonatomic)  UIButton* signUpButton;
@property(assign, nonatomic)  UIButton* realSignInButton;
@property(assign, nonatomic)  UIButton* fakeSignInButton;
@property(assign, nonatomic)  UIImageView* textFieldBG;
@property(assign, nonatomic)  UIImageView* signBluredInBackground;
@property(assign, nonatomic)  UIImageView* signInBackground;
@property(assign, nonatomic)  UIImageView* logo;
@property(retain, nonatomic) UIView* usernamePasswordScreen;
@property(retain, nonatomic) UIView* signInScreen;
@property(retain, nonatomic) UIView* ssoScreen;
@property(assign, nonatomic) BOOL forceSignIn;
@property(readonly, assign, nonatomic) BOOL isSSOAvailable;
@property(assign, nonatomic) BOOL signInVisible;
@property(assign, nonatomic) int currentScreen;
@property(assign, nonatomic)  id<LILoginV2ViewControllerDelegate> delegate;
+(id)loginViewController;
//-(void).cxx_destruct;
-(id)metricsPageKey;
-(void)dismissKeyboard;
-(void)alertView:(id)view willDismissWithButtonIndex:(int)buttonIndex;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)didPresentAlertView:(id)view;
-(void)onboardingViewControllerFinished:(id)finished withChangesMade:(BOOL)changesMade;
-(void)askLIXForAuthenticationType;
-(void)onLongPress:(id)press;
-(void)swipeLeftToAdvance:(id)advance;
-(void)swipeRightToReturn:(id)aReturn;
-(void)onLoginFailedWithUserMessage:(id)userMessage invalidCredentials:(BOOL)credentials;
-(void)onLibraryLoginFailedWithError:(id)error wasSSOLogin:(BOOL)login;
-(void)onDirectLoginFailedWithError:(id)error httpStatus:(int)status;
-(void)onLoginSucceeded:(id)succeeded;
-(id)pageKeyCustomInfo;
-(void)togglePasswordMask;
-(void)openForgotPasswordSafari;
-(void)showForgotPasswordAlert;
-(void)showErrorAlertWithText:(id)text;
-(void)loginSucceeded:(id)succeeded;
-(void)performSignIn;
-(void)enableInputs:(BOOL)inputs;
-(void)realSignIn;
-(void)fakeSignIn;
-(void)signUp;
-(void)forgotPassword;
-(void)updateSSOUI;
-(void)updateSSOState;
-(void)updateKeyboardState;
-(void)onSSOSignUpTapped:(id)tapped;
-(void)onSSOContinueTapped;
-(void)onNotYouButtonTapped;
-(void)onForeground;
-(void)textFieldDidBeginEditing:(id)textField;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)stepBackAnimations;
-(void)stepTwoAnimations;
-(void)stepOneAnimations;
-(void)setupSubviews;
-(void)setupScreens;
-(void)setupGestures;
-(void)dealloc;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
@end

