/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"

@class NSDate, NSString;

@interface PHRecentCall : NSObject
{
    int _category;
    int _type;
    NSString *_destination;
    //struct __CFPhoneNumber *_destinationPhoneNumber;
    NSDate *_date;
    double _duration;
    NSString *_compositeName;
    NSString *_destinationLabel;
    NSString *_destinationLocation;
    NSString *_mobileCountryCode;
    NSString *_mobileNetworkCode;
    NSString *_isoCountryCode;
    NSString *_CNAPFirstName;
    NSString *_CNAPSecondNames;
    int _uid;
    void *_addressBookRecord;
    int _identifier;
    unsigned int _destinationIsFormatted:1;
    unsigned int _destinationIsBlocked:1;
    struct __CTCall *_underlyingCTCall;
    int _unreadCount;
    double _bytesOfDataUsed;
}

+ (int)callCategoryForCall:(struct __CTCall *)arg1;
+ (int)callStatusForCall:(struct __CTCall *)arg1;
@property int unreadCount; // @synthesize unreadCount=_unreadCount;
@property double bytesOfDataUsed; // @synthesize bytesOfDataUsed=_bytesOfDataUsed;
@property(retain) NSString *isoCountryCode; // @synthesize isoCountryCode=_isoCountryCode;
@property(retain) NSString *mobileNetworkCode; // @synthesize mobileNetworkCode=_mobileNetworkCode;
@property(retain) NSString *mobileCountryCode; // @synthesize mobileCountryCode=_mobileCountryCode;
@property(copy) NSString *_CNAPSecondNames; // @synthesize _CNAPSecondNames;
@property(copy) NSString *_CNAPFirstName; // @synthesize _CNAPFirstName;
- (int)numberOfOccurrences;
- (id)callerDisplayName;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)underlyingCTCalls;
- (void)deleteUnderlyingCTCall;
@property struct __CFPhoneNumber *destinationPhoneNumber;
- (void)uncacheIdentity;
@property int destinationIdentifier;
@property void *addressBookRecord;
@property(readonly) int uid;
- (id)compositeName;
- (BOOL)representsCallAtDate:(id)arg1;
- (id)callOccurrences;
- (id)date;
- (void)setDate:(id)arg1;
- (double)duration;
- (void)setDuration:(double)arg1;
- (void)setDestinationLocation:(id)arg1;
- (id)destinationStringForDisplay;
- (id)destinationLocation;
- (id)destinationLabel;
- (BOOL)destinationIsEmailAddress;
- (void)setDestinationIsBlocked:(BOOL)arg1;
- (BOOL)destinationIsBlocked;
- (id)formattedDestination;
- (id)destinationToDialAssisted:(char *)arg1;
- (id)addressBookDestination;
- (id)destination;
- (void)setDestination:(id)arg1;
- (int)type;
- (void)setType:(int)arg1;
- (void)setCategory:(int)arg1;
- (int)category;
- (BOOL)canCoalesceWithCall:(id)arg1;
- (void)setCNAPFirstNameAndSecondNamesFromString:(id)arg1;
- (void)dealloc;
- (id)initWithCTCall:(struct __CTCall *)arg1;
- (id)init;

@end

