/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"
//
//#import "CrashlyticsDelegate-Protocol.h"
//#import "UIAlertViewDelegate-Protocol.h"
//#import "UIApplicationDelegate-Protocol.h"

@class NSDictionary, NSMutableDictionary, NSString, NSURL, TFNRunLoopObserver, TFNTwitterComposition, UIAlertView, UIWindow;

@interface T1AppDelegate //: NSObject <CrashlyticsDelegate, UIAlertViewDelegate, UIApplicationDelegate>
{
    UIWindow *_window;
    UIAlertView *_voiceOverAlert;
    unsigned int _saveStateBackgroundTaskIdentifier;
    int _appState;
    NSString *_initialPanelID;
    double _timelineStreamLocationRequestInterval;
    BOOL _handledPushNotificationOrURLOnLaunch;
    BOOL _showedComposerOnLaunch;
    NSDictionary *_pushPayload;
    int _pushContext;
    NSURL *_launchURL;
    NSMutableDictionary *_clockSkewNotificationDates;
    NSMutableDictionary *_passwordNotificationDates;
    int _inflightOutboundTweetCount;
    int _inflightOutboundMessageCount;
    BOOL _waitToSetupHostViewControllerTillSyncingAccountsFinishes;
    BOOL _loadedAccounts;
    BOOL _didResetCanary;
    BOOL _freshInstall;
    BOOL _watchdogDisabledInPreviousLaunch;
    BOOL _disableWatchdog;
    double _didFinishLaunchingTime;
    double _appDidBecomeActiveTime;
    unsigned long long _sessionLengthTime;
    TFNRunLoopObserver *_runLoopObserver;
    TFNTwitterComposition *_currentComposition;
    NSString *_lastComposeAccountUsername;
}

+ (id)buildTime;
+ (double)willEnterForegroundTime;
+ (void)load;
@property(copy, nonatomic) NSString *lastComposeAccountUsername; // @synthesize lastComposeAccountUsername=_lastComposeAccountUsername;
@property(retain, nonatomic) TFNTwitterComposition *currentComposition; // @synthesize currentComposition=_currentComposition;
@property(nonatomic) int appState; // @synthesize appState=_appState;
//- (void).cxx_destruct;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)voiceOverStatusChanged;
- (BOOL)_purgeDirectory:(id)arg1;
- (void)_purgeLocalArchives;
- (void)crashlytics:(id)arg1 didDetectCrashDuringPreviousExecution:(id)arg2;
- (void)_scribeLocationEnabledStatusAccount:(id)arg1;
- (BOOL)scribeIfStartingToPanel:(id)arg1 scribe:(id)arg2;
- (id)_eventNameFromNamespace:(id)arg1;
- (void)ambientCompositionSent:(id)arg1;
- (void)ambientCompositionSendFailure:(id)arg1;
- (void)ambientCompositionSending:(id)arg1;
- (void)_twitterTimelineStreamLocationRequestDidFinish:(id)arg1;
- (void)_locationManagerDidChangeAuthorizationStatus:(id)arg1;
- (void)_reauthAccount:(id)arg1;
- (void)_twitterAccountDidFailAuthorizationDueToPassword:(id)arg1;
- (void)_twitterAccountDidFailAuthorizationDueToClockSkew:(id)arg1;
- (void)_twitterAccountDidUpdate:(id)arg1;
- (void)_appAccountsDidChange:(id)arg1;
- (void)_appAccountsDidFinishLoading:(id)arg1;
- (void)_endBackgroundTask;
- (void)_saveState;
- (void)_saveViewControllerState;
- (void)_saveApplicationGlobalState;
- (id)_applicationGlobalStateFromArchive;
- (id)_applicationGlobalStateFile;
- (void)_currentLocaleDidChange:(id)arg1;
- (void)_fetchDeviceOperatorAvailability;
- (void)_tryToRegisterDeviceToken;
- (id)_warmStartPerformanceEventForPanel:(id)arg1;
- (id)_coldStartPerformanceEventForPanel:(id)arg1;
- (void)_notifyUserOfPasswordAuthorizationFailure:(id)arg1;
- (void)_notifyUserOfClockSkewAuthorizationFailure:(id)arg1;
- (void)_presentErrorViewControllerWithAccount:(id)arg1 message:(id)arg2 subtext:(id)arg3 cancelButtonTitle:(id)arg4 passwordReset:(BOOL)arg5 inputItem:(id)arg6;
- (void)_purgeCaches;
- (void)_handleLaunchOptions:(id)arg1;
- (void)_startCanary;
- (void)_checkFirstLaunch;
- (id)_duckieScribeForError;
- (id)_duckieScribe;
- (id)rootViewController;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (BOOL)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)_receiveNotificationContext:(int)arg1 info:(id)arg2;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)_startTwitterAsynchronously:(id)arg1;
- (void)_startupGeoDataProvider;
- (void)_startupStork:(unsigned int)arg1 completion:(id)arg2;
- (BOOL)_mustRunStorkForAccount:(id)arg1;
- (void)_startupCompleted:(id)arg1;
- (void)_twitterDidLaunch;
- (id)_accountForStartUp;
- (void)_startUI;
- (void)_startFeatureSwitches;
- (void)_showBugReportButton;
- (void)_recreateDBIfNecessary;
- (void)_purgeArchivesIfNecessary;
- (void)_updateDefaultsIfNecessary;
- (void)_setUpAudioSession;
- (void)_setupHostViewControllerWithAccount:(id)arg1;
- (void)_startSPDY;
- (void)_registerSPDY;
- (void)_startCrashlytics;
- (void)_startDemo;
- (void)_startWatchdog;
- (void)_startSentinelManager;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(retain, nonatomic) UIWindow *window;

@end

