/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import <ChatKit/CKMessage.h>

@class CKSMSMessageDelivery, NSArray, NSMutableArray, NSString;

//@interface CKSMSMessage : CKMessage
//{
//    NSMutableArray *_messages;
//    int _associationID;
//    int _rowID;
//    CKSMSMessageDelivery *_delivery;
//    unsigned int _messagePartsLoaded:1;
//    unsigned int _subjectLoaded:1;
//    NSArray *_messageParts;
//    NSString *_subject;
//}
//
//@property(retain, nonatomic) CKSMSMessageDelivery *delivery; // @synthesize delivery=_delivery;

@interface CKSMSMessage (IOS5)
- (void)dealloc;
- (void)_loadFailedSendCount;
- (BOOL)isPlaceholder;
- (BOOL)_loadIsFromDowngrading;
- (void)setIsFromDowngrading:(BOOL)arg1;
- (BOOL)isFromMe;
- (BOOL)_loadIsRead;
- (int)totalMessageCount;
- (int)sentCount;
- (void)_loadUIFlags;
- (void)_loadSubject;
- (id)subject;
- (void)_loadText;
- (BOOL)_loadOutgoing;
- (id)_newParts;
- (void)addMessage:(void *)arg1;
- (void)setMessages:(id)arg1;
- (void)markAsRead;
- (double)_loadDate;
- (id)messages;
- (unsigned int)messagePartCount;
- (id)messagePartAtIndex:(unsigned int)arg1;
- (void)_setParts:(id)arg1;
- (void)loadParts;
- (id)initWithCTMessage:(void *)arg1 messageParts:(id)arg2;
- (id)parts;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)initWithCTMessages:(id)arg1 messageParts:(id)arg2;
- (id)initWithRowID:(int)arg1;
- (int)messageCount;
- (BOOL)isForward;
- (void)prepareToResend;
- (id)sender;
- (id)address;
- (BOOL)containsDisplayableMessageParts;
- (void)deleteMessagePart:(id)arg1;
- (void)_setupDeliveryIfPending;
- (void)deliveredSubpart:(int)arg1 totalSubparts:(int)arg2 success:(BOOL)arg3;
- (void)deliveryCompletedForMessage:(id)arg1;
- (void)deliveryFailedForMessage:(id)arg1;
- (void)deliveryPartiallyFailedForMessage:(id)arg1;
- (id)guid;
- (id)sequenceNumber;
- (int)rowID;
@property(readonly, nonatomic) int associationID; // @synthesize associationID=_associationID;

@end

