//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  4 2016 10:44:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//


@interface SCChatRenderableChatMedia : NSObject
{
    long long _mediaPixelWidth;
    long long _mediaPixelHeight;
}

@property(nonatomic) long long mediaPixelHeight; // @synthesize mediaPixelHeight=_mediaPixelHeight;
@property(nonatomic) long long mediaPixelWidth; // @synthesize mediaPixelWidth=_mediaPixelWidth;
- (id)uploadParameters;
- (void)thumbnailMediaData:(id)arg1;
- (void)mediaData:(id)arg1;
- (long long)mediaHeight;
- (long long)mediaWidth;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;

@end

