/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"

@class MessageLibrary, NSString;

@interface MessageDetails : NSObject
{
    MessageLibrary *library;
    unsigned int libraryID;
    unsigned long long messageFlags;
    unsigned int uid;
    unsigned int encoding;
    BOOL isInvalid;
    int mailboxID;
    unsigned int conversationHash;
    unsigned int dateReceived;
    NSString *externalID;
}

- (void)dealloc;
- (id)description;
- (unsigned long)uid;
- (id)init;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)remoteID;
- (unsigned int)libraryID;
- (unsigned int)mailboxID;
- (unsigned long long)messageFlags;
- (id)messageID;
- (id)mailbox;
- (double)dateReceivedAsTimeIntervalSince1970;
- (id)copyMessageInfo;
- (id)externalID;

@end

