/* Generated by RuntimeBrowser
Image: /System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices
*/

@interface SBUIEmergencyCallHostViewController : NSObject {//_UIRemoteViewController <SBUIEmergencyCallHostInterface> {
}

+ (id)exportedInterface;
+ (void)requestEmergencyCallControllerWithCompletion:(id)arg1;
+ (id)serviceViewControllerInterface;

- (void)dismiss;

- (void)_scrollToTopFromTouchAtViewLocation:(CGPoint)arg1 resultHandler:(id)arg2;

@end