/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"
//
//#import "SUManagerClientDelegate-Protocol.h"
//#import "SUNetworkObserver-Protocol.h"

@class SUDownload, SUManagerClient;

@interface SBSoftwareUpdateController //: NSObject <SUManagerClientDelegate, SUNetworkObserver>
{
    SUManagerClient *_client;
    SUDownload *_updateToInstall;
    int _currentNetworkType;
    int _iCloudRestoreToken;
    BOOL _showOrScheduleForcedInstallAlertAfterNextUnlock;
    BOOL _scheduleForcedInstallAlertAfterNextUnlock;
    BOOL _scheduleForcedInstallAlertWhenAble;
    BOOL _settingsResetPrefsBadgedFlag;
}

+ (id)stringFromReasons:(int)arg1;
+ (id)sharedInstance;
- (void)_toggleSettingsBadge:(BOOL)arg1;
- (BOOL)_isSettingsBadgedForSoftwareUpdate;
- (void)_clearLegacyBadgeIfNecessary:(id)arg1;
- (void)_migrateForNewOSVersionIfNecessary;
- (void)_saveLastKnownVersionPreference:(id)arg1;
- (id)_stringForCurrentVersionPreference;
- (void)_savePreferencesBadgeFlag:(id)arg1;
- (void)_autoDownloadUnknownToUserFailedForDescriptor:(id)arg1 error:(id)arg2;
- (void)_resetState;
- (BOOL)_isSettingsActive;
- (void)_handleInstallError:(id)arg1;
- (BOOL)_forceInstallAfterDownload;
- (void)_scheduleForcedInstallRepeatAlert:(double)arg1;
- (void)_showForcedInstallAlert;
- (void)_isUpdateInstallable:(id)arg1;
- (void)_showOrScheduleNextForcedInstallAlertWithReasons:(int)arg1;
- (void)_showOrScheduleNextForcedInstallAlert;
- (void)_resetAndCancelExistingScheduledForcedInstallAlerts;
- (void)_setUpdateToInstall:(id)arg1;
- (void)_registerForInstallRelatedNotifications;
- (void)_unregisterForInstallRelatedNotifications;
- (void)client:(id)arg1 installDidFinish:(id)arg2;
- (void)client:(id)arg1 installDidFail:(id)arg2 withError:(id)arg3;
- (void)client:(id)arg1 installDidStart:(id)arg2;
- (void)client:(id)arg1 downloadDidFinish:(id)arg2;
- (void)client:(id)arg1 downloadDidFail:(id)arg2 withError:(id)arg3;
- (void)client:(id)arg1 downloadDidStart:(id)arg2;
- (void)client:(id)arg1 automaticDownloadDidFailToStartForNewUpdateAvailable:(id)arg2 withError:(id)arg3;
- (void)client:(id)arg1 downloadWasInvalidatedForNewUpdateAvailable:(id)arg2;
- (void)_iTunesRestoreStateChanged:(id)arg1;
- (void)_iCloudStatusChanged;
- (void)_lockStateChanged:(id)arg1;
- (void)_callCountChanged:(id)arg1;
- (void)_syncDidEnd:(id)arg1;
- (void)_syncWillStart:(id)arg1;
- (void)_completeMigrationForSettingsReset;
- (void)_prepareMigrationForSettingsReset;
- (void)delayForcedInstallWithDefaultDurationAfterNextUnlock;
- (void)delayForcedInstallWithDefaultDurationFromNow;
- (void)delayForcedInstallUntilAble;
- (void)installUpdate;
- (void)isDownloading:(id)arg1;
- (void)dealloc;
- (id)init;

@end

