/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <ChatKit/CKMediaObject.h>

@interface CKVCardMediaObject : CKMediaObject
{
}

+ (id)mimeTypesToFileExtensions;
- (int)mediaType;
- (BOOL)shouldTranscodeForMMS;
- (Class)balloonPreviewClassWithPreviewData:(id)arg1;
- (void)configureBalloon:(id)arg1 withPreviewData:(id)arg2;

@end

