/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBCallFailureAlertDisplay : SBSlidingAlertDisplay
{
}

+ (id)newTopBarForInstance:(id)arg1;
+ (id)newBottomBarForInstance:(id)arg1;
- (void)ignore:(id)arg1;
- (void)callBack:(id)arg1;
- (void)setAlert:(id)arg1;

@end

