/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"

//#import "BKSWorkspaceDelegate-Protocol.h"
//#import "SBAlertManagerDelegate-Protocol.h"
//#import "SBAlertManagerObserver-Protocol.h"
//#import "SBStarkScreenControllerDelegate-Protocol.h"
//#import "SBStarkScreenManagerDelegate-Protocol.h"
//#import "SBWorkspaceTransactionGroupDelegate-Protocol.h"

@class BKSWorkspace, NSMutableArray, /*NSObject<OS_dispatch_source>,*/ NSTimer, SBAlertManager, SBScreenTimeTrackingController, SBWorkspaceEventQueueLockAssertion, SBWorkspaceTransaction;

@interface SBWorkspace : NSObject //<BKSWorkspaceDelegate, SBAlertManagerDelegate, SBAlertManagerObserver, SBWorkspaceTransactionGroupDelegate, SBStarkScreenManagerDelegate, SBStarkScreenControllerDelegate>
{
    BKSWorkspace *_bksWorkspace;
    SBAlertManager *_alertManager;
    _Bool _alertManagerIsDeactivatingAlert;
    SBScreenTimeTrackingController *_screenTimeTrackingController;
    SBWorkspaceTransaction *_currentTransaction;
    SBWorkspaceEventQueueLockAssertion *_eventQueueLock;
//    NSObject<OS_dispatch_source> *_transactionWatchdog;
    NSTimer *_relaunchTimer;
    NSMutableArray *_applicationsToRelaunch;
}

@property(readonly, nonatomic) SBAlertManager *alertManager; // @synthesize alertManager=_alertManager;
@property(readonly, nonatomic) BKSWorkspace *bksWorkspace; // @synthesize bksWorkspace=_bksWorkspace;
@property(retain, nonatomic) SBWorkspaceTransaction *currentTransaction; // @synthesize currentTransaction=_currentTransaction;
- (void)starkScreenController:(id)arg1 didChangeStateFromState:(long long)arg2;
- (void)starkScreenManagerDidChangeActiveController:(id)arg1;
- (void)starkScreenManagerWillChangeActiveController:(id)arg1;
- (void)transactionGroup:(id)arg1 childTransactionDidFinish:(id)arg2 success:(_Bool)arg3;
- (void)transactionDidFinish:(id)arg1 success:(_Bool)arg2;
- (void)alertManager:(id)arg1 didRemoveAlert:(id)arg2 fromWindow:(id)arg3;
- (void)alertManager:(id)arg1 didTearDownAlertWindow:(id)arg2;
- (void)alertManager:(id)arg1 willTearDownAlertWindow:(id)arg2;
- (void)alertManager:(id)arg1 topAlert:(id)arg2 requestsWallpaperStyleChangeWithAnimationFactory:(id)arg3;
- (void)alertManagerDidChangeTopAlert:(id)arg1;
- (void)alertManager:(id)arg1 didDeactivateAlert:(id)arg2 top:(_Bool)arg3;
- (void)alertManager:(id)arg1 willDeactivateAlert:(id)arg2 top:(_Bool)arg3;
- (void)alertManager:(id)arg1 didActivateAlert:(id)arg2 overAlerts:(id)arg3;
- (void)alertManager:(id)arg1 willActivateAlert:(id)arg2 overAlerts:(id)arg3;
- (id)alertManager:(id)arg1 newAlertWindowForLockAlerts:(_Bool)arg2;
- (_Bool)alertManager:(id)arg1 shouldDeactivateDismissedAlert:(id)arg2;
- (void)_updateStatusBarTimeItemEnabled;
- (void)workspace:(id)arg1 applicationDebugStateChanged:(id)arg2 newState:(_Bool)arg3;
- (void)workspace:(id)arg1 handleStatusBarReturnActionFromApplication:(id)arg2 statusBarStyle:(id)arg3;
- (void)workspace:(id)arg1 applicationFinishedBackgroundContentFetching:(id)arg2 withInfo:(id)arg3;
- (void)workspace:(id)arg1 applicationSuspensionSettingsUpdated:(id)arg2 withSettings:(id)arg3;
- (void)workspace:(id)arg1 applicationSuspended:(id)arg2 withSettings:(id)arg3;
- (void)workspace:(id)arg1 applicationExited:(id)arg2 withInfo:(id)arg3;
- (void)workspace:(id)arg1 applicationDidFailToLaunch:(id)arg2;
- (void)workspace:(id)arg1 applicationActivated:(id)arg2;
- (void)workspace:(id)arg1 applicationDidFinishLaunching:(id)arg2 withInfo:(id)arg3;
- (void)workspace:(id)arg1 applicationDidStartLaunching:(id)arg2;
- (void)workspace:(id)arg1 handleOpenURLRequest:(id)arg2 application:(id)arg3 withOptions:(id)arg4 origin:(id)arg5 withResult:(id)arg6;
- (void)workspace:(id)arg1 handleOpenApplicationRequest:(id)arg2 withOptions:(id)arg3 origin:(id)arg4 withResult:(id)arg5;
- (int)workspace:(id)arg1 canOpenApplication:(id)arg2;
- (void)workspaceDidResume:(id)arg1;
- (void)workspaceWillResume:(id)arg1;
- (void)workspaceDidSuspend:(id)arg1;
- (void)workspaceWillSuspend:(id)arg1;
- (void)workspace:(id)arg1 applicationDidBecomeReceiver:(id)arg2 fromApplication:(id)arg3;
- (id)workspace:(id)arg1 applicationWillBecomeReceiver:(id)arg2 fromApplication:(id)arg3;
- (void)updateInterruptedByCallSettingsFrom:(id)arg1 to:(id)arg2;
- (_Bool)_applicationExited:(id)arg1 withInfo:(id)arg2;
- (_Bool)_handleSetupExited:(id)arg1;
- (void)_invalidateRelaunchTimer;
- (void)_memoryPressureRelieved:(id)arg1;
- (void)_memoryPressureWarn:(id)arg1;
- (void)_launchNextPendedAutoLaunchApp;
- (void)_scheduleRelaunchTimerIfNecessary;
- (void)_handleBuddyLaunchFinished;
- (id)_applicationForBundleIdentifier:(id)arg1 frontmost:(_Bool)arg2;
- (void)_noteCurrentTransactionFailed:(const char *)arg1;
- (id)_selectTransactionForAppActivationToApp:(id)arg1 activationHandler:(id)arg2 canDeactivateAlerts:(void)arg3;
- (id)_selectTransactionForAppActivationToApp:(id)arg1 activationHandler:(id)arg2;
- (id)_selectTransactionForAppExited:(id)arg1;
- (id)_selectTransactionForAppRelaunch:(id)arg1;
- (id)_selectTransactionForAppActivationUnderMainScreenLock:(id)arg1;
- (id)_selectTransactionForReturningToTheLockScreenFromApp:(id)arg1 forceToBuddy:(_Bool)arg2 withActivationHandler:(id)arg3;
- (id)_selectTransactionForReturningToTheLockScreenWithActivationHandler:(id)arg1;
- (id)debugDescription;
- (void)dealloc;
- (id)init;

@end

