//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  4 2016 10:44:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//#import <objc/NSObject.h>

@class VIMAccount;

@interface _TtC5Vimeo16ObjC_VimeoClient : NSObject
{
    // Error parsing type: , name: swiftSurrogate
}

+ (id)sharedClient;
- (id)init;
@property(nonatomic, readonly) VIMAccount *currentAccount;

@end

