//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  4 2016 10:44:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC5Vimeo29ObjC_AuthenticationController.h"

@interface _TtC5Vimeo29ObjC_AuthenticationController (Vimeo)
- (void)logOut;
- (void)clientCredentialsGrant:(id)arg1;
- (id)loadUserAccount;
- (id)loadClientCredentialsAccount;
@end

