/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "BasicAccount.h"
//
//#import "ASDynamicAccountClassLoader-Protocol.h"
//#import "AccountCreationProtocol-Protocol.h"

@interface Account : NSObject //BasicAccount <ASDynamicAccountClassLoader, AccountCreationProtocol>
{
    unsigned int _isActive:2;
}

+ (id)saslProfileName;
+ (BOOL)isSSLEditable;
+ (id)hostname;
+ (id)accountPropertiesValueForKey:(id)arg1 value:(id)arg2;
+ (id)myFullName;
+ (void *)keychainProtocol;
+ (id)displayedShortAccountTypeString;
+ (id)displayedAccountTypeString;
+ (id)accountTypeString;
+ (void)saveAccountInfoToDefaults;
+ (void)saveAccounts:(id)arg1 usingKey:(id)arg2;
+ (id)readAccountsUsingKey:(id)arg1;
+ (id)propertiesWhichRequireValidation;
+ (id)supportedDataclasses;
+ (id)predefinedValueForKey:(id)arg1;
+ (BOOL)isPredefinedAccountType;
+ (id)accountWithBasicAccount:(id)arg1;
+ (id)existingAccountForUniqueID:(id)arg1;
+ (BOOL)_shouldUpdateAccountsInPlace;
+ (BOOL)loadBundleForAccountWithProperties:(id)arg1;
+ (void)loadBundleForAccountClass:(id)arg1;
+ (id)newAccountWithDictionary:(id)arg1;
+ (id)basicAccountProperties;
- (id)copyDiagnosticInformation;
- (id)missingPasswordErrorWithTitle:(id)arg1;
- (BOOL)shouldDisplayHostnameInErrorMessages;
- (BOOL)enableAccount;
- (BOOL)shouldEnableAfterError:(id)arg1;
- (id)nameForMailboxUid:(id)arg1;
- (id)syncStoreIdentifier;
- (id)uniqueId;
- (BOOL)_connectAndAuthenticate:(id)arg1;
- (void)reportAuthenticationError:(id)arg1 authScheme:(id)arg2;
- (BOOL)isPasswordMissing;
- (id)customDescriptionForError:(id)arg1 authScheme:(id)arg2 defaultDescription:(id)arg3;
- (id)customTitleForAuthenticationError:(id)arg1 authScheme:(id)arg2 defaultTitle:(id)arg3;
- (id)customTitleForError:(id)arg1 authScheme:(id)arg2 defaultTitle:(id)arg3;
- (BOOL)_shouldTryDirectSSLConnectionOnPort:(unsigned int)arg1;
- (id)secureConnectionSettings;
- (id)insecureConnectionSettings;
- (id)alternateConnectionSettings;
- (void)applySettingsAsDefault:(id)arg1;
- (id)defaultConnectionSettings;
- (id)certUIService;
- (id)authenticatedConnection;
- (BOOL)requiresAuthentication;
- (Class)connectionClass;
- (id)_newConnection;
- (void)setPreferredAuthScheme:(id)arg1;
- (id)preferredAuthScheme;
- (void)accountInfoDidChange;
- (void)setDomain:(id)arg1;
- (id)domain;
- (void)setTryDirectSSL:(BOOL)arg1;
- (BOOL)allowsTrustPrompt;
- (void)setUsesSSL:(BOOL)arg1;
- (BOOL)usesSSL;
- (void)validateConnections;
- (void)releaseAllForcedConnections;
- (void)releaseAllConnections;
- (struct __CFString *)connectionServiceType;
- (id)secureServiceName;
- (id)serviceName;
- (BOOL)isCommonPortNumber:(unsigned int)arg1;
- (void)setPortNumber:(unsigned int)arg1;
- (unsigned int)keychainPortNumber;
- (unsigned int)defaultSecurePortNumber;
- (unsigned int)defaultPortNumber;
- (unsigned int)portNumber;
- (id)managedTag;
- (BOOL)acquireCredentialsWithPassword:(id)arg1;
- (BOOL)needsCredentials;
- (BOOL)storesPassword;
- (BOOL)promptUserForPasswordWithTitle:(id)arg1 message:(id)arg2 completionHandler:(id)arg3;
- (id)password;
- (id)passwordFromKeychain;
- (id)passwordFromStoredUserInfo;
- (void)setPassword:(id)arg1;
- (void)_removePasswordInKeychain;
- (void)setPasswordInKeychain:(id)arg1;
- (void *)keychainAccessibility;
- (void)setHostname:(id)arg1;
- (id)hostname;
- (void)setUsername:(id)arg1;
- (id)username;
- (void)setDisplayName:(id)arg1;
- (id)displayName;
- (BOOL)canGoOffline;
- (void)setIsActive:(BOOL)arg1;
- (BOOL)isActive;
- (id)valueInAccountPropertiesForKey:(id)arg1;
- (void)removeValueInAccountPropertiesForKey:(id)arg1;
- (void)setValueInAccountProperties:(id)arg1 forKey:(id)arg2;
- (void)_setAccountProperties:(id)arg1;
- (void)_resetAccountProperties:(id)arg1;
- (id)propertiesToSave;
- (void)_queueAccountInfoDidChange;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithProperties:(id)arg1;
- (id)init;

@end

