/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Foundation/Foundation.h>

//#import "WebUIController.h"

//#import "BrowserPanel-Protocol.h"
//#import "FindOnPageToolbarDelegate-Protocol.h"
//#import "MFMailComposeViewControllerDelegate-Protocol.h"
//#import "QuickLookBannerDelegate-Protocol.h"
//#import "UIActionSheetDelegate-Protocol.h"
//#import "UIDocumentInteractionControllerDelegate-Protocol.h"
//#import "UIScrollViewDelegate-Protocol.h"

//@class AddressView, BannerView, BrowserButtonBar, ConsoleView, NSLock, NSMutableArray, NSString, NSTimer, NSURL, QuickLookBanner, RotatablePopoverController, TabController, TabDocument, TabSnapshotContext, UICheckeredPatternView, UIDocumentInteractionController, UIFrameAnimation, UIScrollView, UITapGestureRecognizer, UITransitionView, UIView, UIViewController, UIWebBrowserView, UIWindow, WebInspectorView, WebUIAuthenticationManager;

@interface BrowserController : NSObject //WebUIController <BrowserPanel, MFMailComposeViewControllerDelegate, QuickLookBannerDelegate, UIActionSheetDelegate, UIDocumentInteractionControllerDelegate, UIScrollViewDelegate, FindOnPageToolbarDelegate>
{
//    UIWindow *_window;
//    TabController *_tabController;
//    BrowserButtonBar *_buttonBar;
//    int _pushedRunLoops;
//    UIViewController *_modalViewController;
//    AddressView *_addressView;
//    UICheckeredPatternView *_checkeredPatternView;
//    UIScrollView *_scrollView;
//    UIWebBrowserView *_browserView;
//    UITransitionView *_transitionView;
//    UIView *_pageView;
//    id _modalAlert;
//    ConsoleView *_consoleView;
//    WebInspectorView *_webInspectorView;
//    QuickLookBanner *_quickLookBanner;
//    UITapGestureRecognizer *_quickLookTapRecognizer;
//    UIDocumentInteractionController *_documentInteractionController;
//    BOOL _isShowingQuickLookOpenInMenu;
//    BannerView *_bannerView;
//    BOOL _bannerViewIsAnimating;
//    BOOL _debuggingEnabled;
//    UIView *_titleAndLockContainerView;
//    SEL _scrollToTopDidEndSelector;
//    id <BrowserPanel> _browserPanel;
//    id <BrowserPanel> _nextBrowserPanel;
//    RotatablePopoverController *_currentPopoverController;
//    BOOL _isShowingCurrentPanel;
//    NSURL *_mailToURL;
//    NSMutableArray *_documentsPendingClose;
//    BOOL _isRotating;
//    int _orientation;
//    int _previousOrientation;
//    struct CGRect _rotationRect;
//    unsigned int _rotationEdgePin;
//    float _startScale;
//    float _endScale;
//    BOOL _isZooming;
//    BOOL _isProgressEnabled;
//    float _progress;
//    BOOL _resourcesLoading;
//    BOOL _showingProgressIndicator;
//    TabDocument *_documentWhoseProgressIsShown;
//    NSTimer *_hideAddressViewTimer;
//    NSTimer *_idleTimerDurationTimer;
//    double _idleTimerDuration;
//    int _currentlyLoadingResourcesCount;
//    unsigned int _coalescedUpdateMask;
//    NSTimer *_zoomTimer;
//    unsigned int _zoomTestCount;
//    BOOL _isZoomingIn;
//    BOOL _isRunningZoomTest;
//    BOOL _isRunningTabExposeTest;
//    unsigned int _tabExposeTestLoadCount;
//    unsigned int _tabExposeTestIterationsRemaining;
//    NSString *_currentLocaleIdentifier;
//    BOOL _geolocationDialogAllowed;
//    BOOL _antiPhishingServiceInitialized;
//    BOOL _processingIsSuspended;
//    NSTimer *_resumeUpdatesTimer;
//    int _notifyLockStateToken;
//    unsigned long long _phoneIsLocked;
//    UIFrameAnimation *_addressViewSlideAnimation;
//    WebUIAuthenticationManager *_authenticationManager;
//    TabSnapshotContext *_asynchronousTabSnapshotContext;
//    NSLock *_asynchronousTabSnapshotContextLock;
//    int _currentFindOnPageResultNumber;
//    BOOL _zoomToHighlightSelection;
//    struct CGRect _inputViewScreenBounds;
//    struct CGRect _inputViewScreenBoundsAfterRotation;
//    float _lastAdjustmentForKeyboard;
//    struct __CFDateFormatter *_dateFormatter;
}

+ (id)sharedBrowserController;
+ (void)releaseSharedBrowserController;
+ (id)contentBackgroundColor;
- (int)orientation;
- (int)buttonBarSize;
- (void)setCheckerColor:(id)arg1;
- (id)window;
- (void)updateViewsAfterStatusBarChange;
- (void)willSuspend;
- (void)suspendForEventsOnly:(BOOL)arg1;
- (int)nonBlankDocumentCount;
- (BOOL)isAnyPageLoaded;
- (void)resume;
- (void)_setIdleTimerDuration:(double)arg1;
- (void)_resetIdleTimer;
- (void)updateIdleTimerDuration;
- (void)dealloc;
- (void)loadURL:(id)arg1 userDriven:(BOOL)arg2;
- (Class)buttonBarClass;
- (void)showPrintingDuringLoadAlert;
- (BOOL)_showingAModalAlertWillHang;
- (void)webView:(id)arg1 runJavaScriptAlertPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3;
- (BOOL)webView:(id)arg1 runJavaScriptConfirmPanelWithMessage:(id)arg2 initiatedByFrame:(id)arg3;
- (id)webView:(id)arg1 runJavaScriptTextInputPanelWithPrompt:(id)arg2 defaultText:(id)arg3 initiatedByFrame:(id)arg4;
- (BOOL)webViewShouldInterruptJavaScript:(id)arg1;
- (void)webView:(id)arg1 printFrameView:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForGeolocationRequestFromOrigin:(id)arg2 frame:(id)arg3 listener:(id)arg4;
- (id)browserView;
- (id)browserPanel;
- (void)setDocumentView:(id)arg1;
- (void)document:(id)arg1 changedView:(id)arg2;
- (id)tabController;
- (struct CGRect)_addressViewFrameScrollViewCoords;
- (struct CGRect)_addressViewFrame;
- (void)updateAddressViewFrame;
- (id)_savedPDF;
- (void)openInApplication:(id)arg1;
- (void)openInOtherApplications:(id)arg1;
- (void)_removeQuickLookTimer;
- (void)_installOrContinueQuickLookTimer;
- (void)documentInteractionControllerWillPresentOpenInMenu:(id)arg1;
- (void)documentInteractionControllerDidDismissOpenInMenu:(id)arg1;
- (void)documentInteractionController:(id)arg1 willBeginSendingToApplication:(id)arg2;
- (id)documentInteractionControllerURLOfDirectoryForUnzippedDocument:(id)arg1;
- (float)buttonBarHeightForBarSize:(int)arg1;
- (void)updateButtonBarFrame;
- (struct CGRect)defaultWebLayerFrame;
- (void)updateWebViewSizeAttributes:(id)arg1;
- (void)updateWebViewSizeAttributes;
- (void)updateCheckeredPatternFrame;
- (void)updateScrollIndicatorTopInset;
- (void)updateScrollViewFrame;
- (struct CGSize)scrollViewContentSize;
- (void)updateScrollViewContentSize;
- (void)view:(id)arg1 didSetFrame:(struct CGRect)arg2 oldFrame:(struct CGRect)arg3 asResultOfZoom:(BOOL)arg4;
- (void)view:(id)arg1 didDrawInRect:(struct CGRect)arg2 duration:(double)arg3;
- (void)webView:(id)arg1 didDrawRect:(struct CGRect)arg2;
- (void)webViewDidDrawTiles:(id)arg1;
- (void)webView:(id)arg1 willClickElement:(id)arg2;
- (void)webViewDidClick:(id)arg1;
- (void)webView:(id)arg1 willAssistFormNode:(id)arg2;
- (void)webViewWillHideFullScreenPlugInUI:(id)arg1;
- (id)buttonBarContainer;
- (id)addressView;
- (id)asynchronousTabSnapshotContext;
- (id)asynchronousTabSnapshotContextLock;
- (void)_initSubviews;
- (void)saveRecentSearches:(id)arg1;
- (id)recentSearches;
- (id)recentSearchesMatchingPrefix:(id)arg1;
- (void)addRecentSearch:(id)arg1;
- (void)clearRecentSearches;
- (void)setupWithURL:(id)arg1;
- (void)localeChanged:(struct __CFLocale *)arg1;
- (void)carrierBundledChanged;
- (void)didReadDefaults;
- (void)updateButtons;
- (void)_updateEVOrganizationName;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)didCompleteGesturesOrScrolling;
- (void)didCompleteGestures;
- (void)didCompleteScrolling;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)goBack;
- (void)backFromButtonBar;
- (void)_goForward;
- (void)forwardFromButtonBar;
- (void)goToAddress:(id)arg1 fromAddressView:(id)arg2;
- (void)setProgressEnabled:(BOOL)arg1;
- (void)setInitialZoomScaleForPPT:(float)arg1;
- (void)updateAddress:(BOOL)arg1 forTabDocument:(id)arg2;
- (void)updateTitle:(BOOL)arg1 forTabDocument:(id)arg2;
- (void)updateProgress:(BOOL)arg1 forTabDocument:(id)arg2;
- (struct CGRect)_quickLookFrame;
- (void)_hideQuickLookBanner;
- (void)_showQuickLookBanner;
- (void)removeQuickLookBanner;
- (void)updateBanners:(BOOL)arg1 forTabDocument:(id)arg2;
- (void)updateInterface:(BOOL)arg1;
- (id)keyboardSuperview;
- (struct CGRect)frameForDisplayingAddressView:(id)arg1;
- (struct CGRect)frameForAddressViewEditing;
- (id)buttonBar;
- (int)panelType;
- (int)panelState;
- (int)pausesPages;
- (BOOL)disablesStatusBarPress;
- (void)scrollToTopWithDidEndSelector:(SEL)arg1;
- (void)statusBarPressed;
- (void)scrollDown;
- (BOOL)isAtEndOfPage;
- (id)transitionView;
- (void)_restoreStateFromSnapshotContext:(id)arg1;
- (void)_didFinishTakingSnapshotOnWebThread;
- (void)prepareToTakeSnapshotOfTabDocument:(id)arg1 context:(id)arg2;
- (void)_takeSnapshotOnWebThread;
- (id)snapshotForTabDocument:(id)arg1;
- (id)productVersion;
- (id)bundleVersion;
- (id)userAgentForURL:(id)arg1;
- (void)clearAutoFillMessageReceived;
- (void)clearHistoryMessageReceived;
- (void)userEmptiedCachesMessageReceived;
- (void)setCookiePolicyMessageReceived;
- (void)tabDocumentSecureContentStatusHasChanged:(id)arg1;
- (void)toggleAlwaysShowBookmarksBarMessageReceived;
- (void)logInFromAuthenticationManager:(id)arg1 withCredential:(id)arg2 forChallenge:(id)arg3;
- (void)cancelFromAuthenticationManager:(id)arg1 forChallenge:(id)arg2;
- (id)containerViewForAuthenticationPanel;
- (BOOL)updateHighlightBubbleWobble:(BOOL)arg1;
- (BOOL)_highlightSelection;
- (void)_updateCurrentResultLabel;
- (void)_highlightNextMatch;
- (struct __CFDateFormatter *)dateFormatter;
- (void)_bannerAnimationDidStop:(id)arg1 finished:(id)arg2;
- (void)_bannerAnimationDidStopAndShouldRemove:(id)arg1 finished:(id)arg2;
- (void)showBanner:(id)arg1;
- (void)hideBanner:(id)arg1 removeView:(BOOL)arg2;
- (id)bannerView;
- (float)_pdfPageNumberLabelYOffset;
- (struct CGRect)bannerViewFrame;
- (void)updateBannerViewFrame;
- (id)textForCurrentResultLabel;
- (void)next;
- (void)done;
- (void)updateSearchText:(id)arg1;
//@property(retain, nonatomic) NSURL *mailToURL; // @synthesize mailToURL=_mailToURL;
//@property(retain, nonatomic) RotatablePopoverController *currentPopoverController; // @synthesize currentPopoverController=_currentPopoverController;

@end

