//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  4 2016 10:44:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IGStorableObject.h"

@class CLLocation, NSArray, NSDictionary, NSNumber, NSString, NSURL;

@interface IGUser : IGStorableObject
{
    NSArray *_searchTerms;
    _Bool _staff;
    _Bool _blocking;
    _Bool _directShareBlocked;
    _Bool _onDirectBlacklist;
    _Bool _favorited;
    _Bool _incomingRequestPending;
    _Bool _profileActionNeeded;
    _Bool _rejects_staff_privileges;
    _Bool _hasChainingUsers;
    _Bool _hasAnonymousProfilePicture;
    _Bool _unpublished;
    _Bool _isActive;
    _Bool _geoIPBlocked;
    _Bool _followRestricted;
    _Bool _verified;
    _Bool _needy;
    _Bool _adRater;
    _Bool _canBoostPost;
    _Bool _canSeeOrganicInsights;
    _Bool _shouldShowInsightsTerms;
    _Bool _isBusiness;
    _Bool _canConvertToBusiness;
    _Bool _hasBiographyTranslation;
    NSString *_publicEmail;
    unsigned long long _contactPreference;
    NSString *_publicPhoneNumber;
    NSString *_publicPhoneNumberCountryCode;
    NSString *_pageCategory;
    NSString *_publicLocationName;
    NSString *_publicCityName;
    NSString *_publicCityID;
    CLLocation *_publicLocationCoordinates;
    NSString *_publicZipCode;
    NSString *_pageID;
    NSString *_pageName;
    long long _followStatus;
    long long _privacyStatus;
    NSString *_biography;
    NSString *_byline;
    NSString *_displayName;
    NSString *_fullName;
    NSString *_geoIPBlockedExtraInfo;
    NSString *_searchSocialContext;
    NSString *_socialContext;
    NSString *_trackingToken;
    NSString *_username;
    NSNumber *_friendScore;
    NSString *_profileContext;
    unsigned long long _geoMediaCount;
    unsigned long long _usertagsCount;
    NSNumber *_followerCount;
    NSNumber *_followingCount;
    NSNumber *_mediaCount;
    NSURL *_externalURL;
    NSURL *_externalLynxURL;
    NSURL *_profilePicURL;
    NSDictionary *_HDProfilePicURLInfo;
    NSString *_profilePicID;
    NSArray *_similarUsers;
    NSNumber *_mutualFollowersCount;
    NSNumber *_unseenCount;
    NSString *_biographyTranslation;
    long long _lastFollowStatus;
}

+ (id)stringForfollowStatus:(long long)arg1;
+ (id)cleanedBiography:(id)arg1;
+ (id)centralizedStore;
@property long long lastFollowStatus; // @synthesize lastFollowStatus=_lastFollowStatus;
@property(retain) NSString *biographyTranslation; // @synthesize biographyTranslation=_biographyTranslation;
@property _Bool hasBiographyTranslation; // @synthesize hasBiographyTranslation=_hasBiographyTranslation;
@property(retain) NSNumber *unseenCount; // @synthesize unseenCount=_unseenCount;
@property(retain) NSNumber *mutualFollowersCount; // @synthesize mutualFollowersCount=_mutualFollowersCount;
@property(retain) NSArray *similarUsers; // @synthesize similarUsers=_similarUsers;
@property(retain) NSString *profilePicID; // @synthesize profilePicID=_profilePicID;
@property(retain) NSDictionary *HDProfilePicURLInfo; // @synthesize HDProfilePicURLInfo=_HDProfilePicURLInfo;
@property(retain) NSURL *profilePicURL; // @synthesize profilePicURL=_profilePicURL;
@property(retain) NSURL *externalLynxURL; // @synthesize externalLynxURL=_externalLynxURL;
@property(retain) NSURL *externalURL; // @synthesize externalURL=_externalURL;
@property(retain) NSNumber *mediaCount; // @synthesize mediaCount=_mediaCount;
@property(readonly) NSNumber *followingCount; // @synthesize followingCount=_followingCount;
@property(readonly) NSNumber *followerCount; // @synthesize followerCount=_followerCount;
@property unsigned long long usertagsCount; // @synthesize usertagsCount=_usertagsCount;
@property unsigned long long geoMediaCount; // @synthesize geoMediaCount=_geoMediaCount;
@property(copy) NSString *profileContext; // @synthesize profileContext=_profileContext;
@property(copy) NSNumber *friendScore; // @synthesize friendScore=_friendScore;
@property(copy) NSString *username; // @synthesize username=_username;
@property(copy) NSString *trackingToken; // @synthesize trackingToken=_trackingToken;
@property(copy) NSString *socialContext; // @synthesize socialContext=_socialContext;
@property(copy) NSString *searchSocialContext; // @synthesize searchSocialContext=_searchSocialContext;
@property(copy) NSString *geoIPBlockedExtraInfo; // @synthesize geoIPBlockedExtraInfo=_geoIPBlockedExtraInfo;
@property(copy) NSString *fullName; // @synthesize fullName=_fullName;
@property(copy) NSString *displayName; // @synthesize displayName=_displayName;
@property(copy) NSString *byline; // @synthesize byline=_byline;
@property(copy) NSString *biography; // @synthesize biography=_biography;
@property long long privacyStatus; // @synthesize privacyStatus=_privacyStatus;
@property long long followStatus; // @synthesize followStatus=_followStatus;
@property(copy) NSString *pageName; // @synthesize pageName=_pageName;
@property(copy) NSString *pageID; // @synthesize pageID=_pageID;
@property(retain) NSString *publicZipCode; // @synthesize publicZipCode=_publicZipCode;
@property(retain) CLLocation *publicLocationCoordinates; // @synthesize publicLocationCoordinates=_publicLocationCoordinates;
@property(copy) NSString *publicCityID; // @synthesize publicCityID=_publicCityID;
@property(copy) NSString *publicCityName; // @synthesize publicCityName=_publicCityName;
@property(copy) NSString *publicLocationName; // @synthesize publicLocationName=_publicLocationName;
@property(copy) NSString *pageCategory; // @synthesize pageCategory=_pageCategory;
@property(copy) NSString *publicPhoneNumberCountryCode; // @synthesize publicPhoneNumberCountryCode=_publicPhoneNumberCountryCode;
@property(copy) NSString *publicPhoneNumber; // @synthesize publicPhoneNumber=_publicPhoneNumber;
@property _Bool canConvertToBusiness; // @synthesize canConvertToBusiness=_canConvertToBusiness;
@property unsigned long long contactPreference; // @synthesize contactPreference=_contactPreference;
@property(copy) NSString *publicEmail; // @synthesize publicEmail=_publicEmail;
@property _Bool isBusiness; // @synthesize isBusiness=_isBusiness;
@property _Bool shouldShowInsightsTerms; // @synthesize shouldShowInsightsTerms=_shouldShowInsightsTerms;
@property _Bool canSeeOrganicInsights; // @synthesize canSeeOrganicInsights=_canSeeOrganicInsights;
@property _Bool canBoostPost; // @synthesize canBoostPost=_canBoostPost;
@property(getter=isAdRater) _Bool adRater; // @synthesize adRater=_adRater;
@property(getter=isNeedy) _Bool needy; // @synthesize needy=_needy;
@property(getter=isVerified) _Bool verified; // @synthesize verified=_verified;
@property(getter=isFollowRestricted) _Bool followRestricted; // @synthesize followRestricted=_followRestricted;
@property(getter=isGeoIPBlocked) _Bool geoIPBlocked; // @synthesize geoIPBlocked=_geoIPBlocked;
@property(getter=isActive) _Bool isActive; // @synthesize isActive=_isActive;
@property(getter=isUnpublished) _Bool unpublished; // @synthesize unpublished=_unpublished;
@property _Bool hasAnonymousProfilePicture; // @synthesize hasAnonymousProfilePicture=_hasAnonymousProfilePicture;
@property _Bool hasChainingUsers; // @synthesize hasChainingUsers=_hasChainingUsers;
@property _Bool rejects_staff_privileges; // @synthesize rejects_staff_privileges=_rejects_staff_privileges;
@property _Bool profileActionNeeded; // @synthesize profileActionNeeded=_profileActionNeeded;
@property _Bool incomingRequestPending; // @synthesize incomingRequestPending=_incomingRequestPending;
@property _Bool favorited; // @synthesize favorited=_favorited;
@property _Bool onDirectBlacklist; // @synthesize onDirectBlacklist=_onDirectBlacklist;
@property _Bool directShareBlocked; // @synthesize directShareBlocked=_directShareBlocked;
@property _Bool blocking; // @synthesize blocking=_blocking;

- (void)removeSimilarUsers:(id)arg1;
- (_Bool)hasContactOptions;
- (id)formattedLocationName;
@property(readonly) _Bool hasLocation;
@property(readonly) _Bool hasSimilarUsers;
- (void)updateFollowingCount:(long long)arg1;
- (void)updateFollowerCount:(long long)arg1;
- (_Bool)staff;
- (_Bool)friendshipStatusPending;
- (void)resetBiographyTranslation;
- (void)removeBusinessFunctionality;
- (void)convertBusinessBackToUser;
- (void)updateFriendshipStatusWithResponse:(id)arg1;
- (void)configureFollowStatus:(id)arg1;
@property(readonly, copy) NSString *searchString;
- (id)searchTerms;
- (struct CGSize)HDProfilePicSize;
- (id)HDProfilePicURL;
- (id)secondaryName;
- (id)primaryName;
- (id)fullOrDisplayName;
- (id)description;
- (id)similarUserInfoDict;
- (id)userInfoDict;
- (id)toDict;
- (void)parseBusinessInfo:(id)arg1 withDict:(id)arg2;
- (_Bool)updateWithDictionary:(id)arg1;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

