/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"

@class BBGGroup, BBGGroupConversation, BBMConversation, BBMMessage, BBMUser, NSArray, NSString;

@interface BBMCommonConversation : NSObject
{
    NSString *_latestMessageText;
    NSString *_title;
    BBMUser *_changedParticipant;
    NSArray *_participants;
    NSArray *_resolvedInitialParticipants;
    BBGGroupConversation *_groupConversation;
    NSArray *_resolvedParticipants;
    BBGGroup *_group;
    NSString *_conversationUri;
    BOOL _isConference;
    BBMMessage *_resolvedLastMessage;
    BBMConversation *_conversation;
    long long _latestTimestamp;
    NSArray *_initialParticipants;
    unsigned long long _numMessages;
    int _latestMessageStatus;
    BBMUser *_resolvedOwnerUri;
}

+ (id)keyPathsForValuesAffectingIsEmpty;
+ (id)keyPathsForValuesAffectingTitle;
+ (id)keyPathsForValuesAffectingConversationId;
+ (id)keyPathsForValuesAffectingConversationAge;
+ (id)conversationWithURI:(id)arg1;
+ (id)conversationWithGroupConversation:(id)arg1;
+ (id)conversationWithConversation:(id)arg1;
@property(retain, nonatomic) BBMUser *resolvedOwnerUri; // @synthesize resolvedOwnerUri=_resolvedOwnerUri;
@property(nonatomic) int latestMessageStatus; // @synthesize latestMessageStatus=_latestMessageStatus;
@property(nonatomic) unsigned long long numMessages; // @synthesize numMessages=_numMessages;
@property(retain, nonatomic) NSArray *initialParticipants; // @synthesize initialParticipants=_initialParticipants;
@property(nonatomic) long long latestTimestamp; // @synthesize latestTimestamp=_latestTimestamp;
@property(retain, nonatomic) BBMConversation *conversation; // @synthesize conversation=_conversation;
@property(retain, nonatomic) BBMMessage *resolvedLastMessage; // @synthesize resolvedLastMessage=_resolvedLastMessage;
@property(nonatomic) BOOL isConference; // @synthesize isConference=_isConference;
@property(retain, nonatomic) NSString *conversationUri; // @synthesize conversationUri=_conversationUri;
@property(retain, nonatomic) BBGGroup *group; // @synthesize group=_group;
@property(retain, nonatomic) NSArray *resolvedParticipants; // @synthesize resolvedParticipants=_resolvedParticipants;
@property(retain, nonatomic) BBGGroupConversation *groupConversation; // @synthesize groupConversation=_groupConversation;
@property(retain, nonatomic) NSArray *resolvedInitialParticipants; // @synthesize resolvedInitialParticipants=_resolvedInitialParticipants;
@property(retain, nonatomic) NSArray *participants; // @synthesize participants=_participants;
@property(retain, nonatomic) BBMUser *changedParticipant; // @synthesize changedParticipant=_changedParticipant;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *latestMessageText; // @synthesize latestMessageText=_latestMessageText;
//- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL isEmpty;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)getNonGroupChatTitle;
@property(readonly, nonatomic) NSString *conversationId;
@property(readonly, nonatomic) double conversationAge;
@property(readonly, nonatomic) BOOL isGroupConversation;
- (id)keyPathListForGroupConversation;
- (id)keyPathListForConversation;
- (void)dealloc;

@end

