/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import "SKSingleObject.h"

@class NSMutableArray, Dispatcher, NSNotificationCenter;
@protocol StatsLogger;

//__attribute__((visibility("hidden")))
//@interface SKFileTransferManager : NSObject {//SKSingleObject {
//	Dispatcher* _dispatcher;
//	NSNotificationCenter* _notificationCenter;
//	NSMutableArray* _cachedConversations;
//	NSMutableArray* _cachedTransferMessages;
//	id<StatsLogger> _statsLogger;
//}
@interface SKFileTransferManager (Skype48)
@property(retain, nonatomic) NSMutableArray* cachedConversations;
@property(retain, nonatomic) NSMutableArray* cachedTransferMessages;
@property(retain, nonatomic) Dispatcher* dispatcher;
@property(retain, nonatomic) NSNotificationCenter* notificationCenter;
@property(retain, nonatomic) id<StatsLogger> statsLogger;
//-(void).cxx_destruct;
-(void)dealloc;
-(void)awakeFromAutowire;
-(id)init;
-(void)removeCachedConversationsAndMessages;
-(void)addMessage:(id)message;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
@end

