//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class FBMSecureThreadKey, MNSecureAttachmentRetrievalInfo, NSData, NSString;

//@interface MNSecurePhotoSource : FBValueObject <NSCopying>
//{
//    FBMSecureThreadKey *_threadKey;
//    NSString *_messageId;
//    MNSecureAttachmentRetrievalInfo *_retrievalInfo;
//    NSData *_thumbnailData;
//}

@interface MNSecurePhotoSource (Messenger_96_0)

@property(readonly, copy, nonatomic) NSData *thumbnailData; // @synthesize thumbnailData=_thumbnailData;
@property(readonly, copy, nonatomic) MNSecureAttachmentRetrievalInfo *retrievalInfo; // @synthesize retrievalInfo=_retrievalInfo;
@property(readonly, copy, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
@property(readonly, copy, nonatomic) FBMSecureThreadKey *threadKey; // @synthesize threadKey=_threadKey;

- (id)initWithThreadKey:(id)arg1 messageId:(id)arg2 retrievalInfo:(id)arg3 thumbnailData:(id)arg4;

@end

