//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  4 2016 10:44:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IGPost.h"

@class IGCommentModel, IGDirectResponseInfo, IGSponsoredPostInfo, IGUsertagGroup, NSArray, NSNumber, NSString;

@interface IGFeedItem : IGPost
{
    IGUsertagGroup *_usertags;
    NSArray *_previewCommentsInFeed;
    _Bool _inPhotosOfYou;
    _Bool _isHidden;
    _Bool _carouselLinkButtonOverride;
    _Bool _expanded;
    NSString *_permalink;
    NSString *_exploreAlgorithm;
    NSString *_exploreImpressionToken;
    NSString *_mediaId;
    long long _directResponseStyle;
    long long _directResponseHeaderStyle;
    NSNumber *_iTunesItemIdentifier;
    IGSponsoredPostInfo *_sponsoredPostInfo;
    NSString *_organicTrackingToken;
    long long _promotionState;
    long long _translationState;
}

+ (id)centralizedStore;
@property _Bool expanded; // @synthesize expanded=_expanded;
@property long long translationState; // @synthesize translationState=_translationState;
@property _Bool carouselLinkButtonOverride; // @synthesize carouselLinkButtonOverride=_carouselLinkButtonOverride;
@property(readonly) long long promotionState; // @synthesize promotionState=_promotionState;
@property(copy) NSString *organicTrackingToken; // @synthesize organicTrackingToken=_organicTrackingToken;
@property(readonly) IGSponsoredPostInfo *sponsoredPostInfo; // @synthesize sponsoredPostInfo=_sponsoredPostInfo;
@property(readonly) NSNumber *iTunesItemIdentifier; // @synthesize iTunesItemIdentifier=_iTunesItemIdentifier;
@property(readonly) long long directResponseHeaderStyle; // @synthesize directResponseHeaderStyle=_directResponseHeaderStyle;
@property(readonly) long long directResponseStyle; // @synthesize directResponseStyle=_directResponseStyle;
@property(readonly) NSString *mediaId; // @synthesize mediaId=_mediaId;
@property _Bool isHidden; // @synthesize isHidden=_isHidden;
@property(readonly) NSString *exploreImpressionToken; // @synthesize exploreImpressionToken=_exploreImpressionToken;
@property(readonly) NSString *exploreAlgorithm; // @synthesize exploreAlgorithm=_exploreAlgorithm;
@property(readonly) _Bool inPhotosOfYou; // @synthesize inPhotosOfYou=_inPhotosOfYou;
@property(readonly, copy) NSString *permalink; // @synthesize permalink=_permalink;

- (id)likeActionSourceInfoUserDidDoubleTap:(_Bool)arg1;
- (void)performLike:(_Bool)arg1 withUser:(id)arg2 userDidDoubleTap:(_Bool)arg3 userInfo:(id)arg4 index:(long long)arg5 analyticsMetadata:(id)arg6 analyticsModule:(id)arg7 requestSourceParams:(id)arg8 completion:(id)arg9;
- (void)performLike:(_Bool)arg1 withUser:(id)arg2 userDidDoubleTap:(_Bool)arg3 index:(long long)arg4 analyticsMetadata:(id)arg5 completion:(id)arg6;
- (void)deletePostItemFromItem:(id)arg1;
- (void)deleteItem;
- (id)previewCommentsInFeed;
- (void)setSponsoredPostInfoFromEntry:(id)arg1;
- (void)markAsExpanded;
- (_Bool)isExpanded;
- (void)setMediaIdWithPk:(id)arg1;
- (id)mediaIdFromPK:(id)arg1;
- (void)setPromotedState:(long long)arg1;
@property(readonly) _Bool isAdsCarousel;
@property(readonly) _Bool isDirectResponse;
- (_Bool)isSponsoredApp;
@property(readonly) IGCommentModel *headline;
@property(readonly) IGDirectResponseInfo *directResponseInfo;
- (void)setInPhotosOfYou:(_Bool)arg1;
- (void)setUsertagsFromEntry:(id)arg1;
- (id)usertags;
- (void)invalidateActiveComments;
- (long long)promotionStateFromString:(id)arg1;
@property(readonly) _Bool hasBeenPromoted;
- (_Bool)updateWithDictionary:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly, copy) NSString *description;

@end

