//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  4 2016 10:44:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class IGNonCurrentUserDefaults, IGUser, NSString;

@interface IGUserSession : NSObject
{
    IGUser *_user;
    IGNonCurrentUserDefaults *_nonCurrentUserDefaults;
    unsigned long long _backgroundTask;
}

+ (void)clearForUserPK:(id)arg1;
+ (id)classesWhereWillSwitchUsersShouldRunInForeground;
+ (id)inMemoryStoresThatCacheUserData;
+ (id)storesToClearAfterApplicationCrash;
+ (id)storesThatCacheUserData;
@property(nonatomic) unsigned long long backgroundTask; // @synthesize backgroundTask=_backgroundTask;
@property(retain, nonatomic) IGNonCurrentUserDefaults *nonCurrentUserDefaults; // @synthesize nonCurrentUserDefaults=_nonCurrentUserDefaults;
@property(retain, nonatomic) IGUser *user; // @synthesize user=_user;

- (id)initForTesting;
- (void)archiveInBackground;
- (void)willLogOutPrivate:(id)arg1;
- (void)checkIfStillAliveAfterDelay;
- (void)willLogOut;
- (void)willSwitchUsers;
- (id)valueForClass:(id)arg1 withInitializer:(id)arg2;
- (id)initWithUser:(id)arg1;
- (void)dealloc;

@end

