/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"
//
#import "CKMessage-Protocol.h"

@class CKConversation, IMMessage, NSArray, NSAttributedString, NSCalendarDate, NSDate;

@interface CKIMMessage : NSObject //<CKMessage>
{
    IMMessage *_imMessage;
    NSArray *_parts;
    NSArray *_incompleteParts;
    NSDate *_placeHolderDate;
    BOOL _hasPostedComplete;
    int _partCount;
    int _incompletePartCount;
    float _cachedPercentComplete;
    unsigned int _dateLoaded:1;
    unsigned int _observingFileTransferNotifications:1;
    unsigned int _shouldPlayReceivedTone:1;
    NSAttributedString *_text;
    double _date;
    NSCalendarDate *_calendarDate;
    int _failedSendCount;
    CKConversation *_conversation;
}

- (id)conversation;
- (BOOL)shouldPlayReceivedTone;
- (BOOL)wantsSendStatus;
- (int)outgoingBubbleColor;
- (BOOL)containsAllDisplayableMessageParts:(id)arg1;
- (BOOL)isFirstDisplayablePart:(id)arg1;
- (id)service;
- (BOOL)isSMS;
- (BOOL)isiMessage;
- (void)_fileTransferUpdated:(id)arg1;
- (BOOL)postMessageReceivedIfNecessary;
- (void)updateMessageCompleteQuietly;
- (BOOL)messageIsComplete;
- (void)setConversation:(id)arg1;
@property(retain, nonatomic) IMMessage *IMMessage;
- (int)sequenceNumber;
- (int)rowID;
- (id)guid;
- (BOOL)isTypingIndicator;
- (BOOL)isPlaceholder;
- (BOOL)isFromDowngrading;
- (void)setIsFromDowngrading:(BOOL)arg1;
- (id)description;
- (void)deleteMessageParts:(id)arg1;
- (void)resetParts;
- (void)loadParts;
- (BOOL)hasAttachments;
- (id)parts;
- (id)messagePartAtIndex:(unsigned int)arg1;
- (unsigned int)messagePartCount;
- (id)previewText;
- (id)attachmentText:(BOOL)arg1;
- (id)_rawPreviewText;
- (int)compare:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (BOOL)supportsDeliveryReceipts;
- (id)timeDelivered;
- (BOOL)isDelivered;
- (BOOL)isFromFilteredSender;
- (BOOL)isWaitingForDelivery;
- (BOOL)isFromMe;
- (int)failedSendCount;
- (int)pendingCount;
- (BOOL)pending;
- (int)sentCount;
- (BOOL)partiallyFailedSend;
- (BOOL)failedSend;
- (void)markAsRead;
- (BOOL)isToEmailAddress;
- (BOOL)isOutgoing;
- (id)timeRead;
- (BOOL)isRead;
- (BOOL)hasBeenSent;
- (id)error;
- (id)subject;
- (id)sender;
- (id)address;
- (int)messageCount;
- (id)recipients;
- (id)calendarDate;
- (float)percentComplete;
- (int)totalMessageCount;
- (void)_loadCounts;
- (void)_parseIMMessagePartsWithTextProcessingBlock:(id)arg1 fileTransferProcessingBlock:(void)arg2;
- (double)_loadDate;
- (void)_resetData;
- (void)dealloc;
- (id)initPlaceholderWithDate:(id)arg1;
- (id)initWithIMMessage:(id)arg1;
- (void)_observeFileTransfersIfNecessary;

@end

