/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"

@class NSArray, NSMutableArray, NSString;

@interface FBMStickerPack : NSObject
{
    NSMutableArray *_stickers;
    unsigned long long _fbId;
    double _price;
    BOOL _featured;
    NSString *_profileImageUrl;
    NSString *_name;
    NSString *_thumbnailImageUrl;
    NSString *_details;
    NSString *_previewImageUrl;
}

+ (id)stickerPackFromJsonObject:(id)arg1;
+ (id)stickerPackFromDictionary:(id)arg1;
@property(copy, nonatomic) NSString *previewImageUrl; // @synthesize previewImageUrl=_previewImageUrl;
@property(copy, nonatomic) NSString *details; // @synthesize details=_details;
@property(copy, nonatomic) NSString *thumbnailImageUrl; // @synthesize thumbnailImageUrl=_thumbnailImageUrl;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *profileImageUrl; // @synthesize profileImageUrl=_profileImageUrl;
@property(nonatomic, getter=isFeatured) BOOL featured; // @synthesize featured=_featured;
@property(nonatomic) double price; // @synthesize price=_price;
@property(nonatomic) unsigned long long fbId; // @synthesize fbId=_fbId;
- (BOOL)isEqual:(id)arg1;
- (id)_stickerDictionaries;
- (id)generateDictionaryObject;
@property(readonly, nonatomic) NSArray *stickers;
- (void)addSticker:(id)arg1;
- (void)dealloc;
- (id)initWithFbId:(unsigned long long)arg1;

@end

