#!/bin/bash

declare -a cydia
cydia=($CYDIA)

if [[ ${CYDIA+@} ]]; then
	SSMP_CYDIA_REMOVE="YES"
else
	SSMP_CYDIA_REMOVE="NO"
fi

if [[ $1 == remove ]]; then
	. /Applications/ssmp.app/Uninstall.sh $SSMP_CYDIA_REMOVE
fi

#echo "*********************************************************"
#echo "*********************************************************"
#echo "TO COMPLETE UNINSTALL RESTART SPRINGBOARD NOW!"
#echo "*********************************************************"
#echo "*********************************************************"
#echo ""
#echo ""

sleep 3

exit 0
