/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PLTBaseType.h"

#import "NSCoding-Protocol.h"

@class NSNumber;

@interface PLTMessageInfo : PLTBaseType <NSCoding>
{
    NSNumber *_token;
    NSNumber *_seq;
}

@property(retain, nonatomic) NSNumber *seq; // @synthesize seq=_seq;
@property(retain, nonatomic) NSNumber *token; // @synthesize token=_token;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithToken:(unsigned long long)arg1 seq:(unsigned int)arg2;

@end

