/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import "SKObject.h"

@class NSNumber, DomainObjectPool, ALESkyLib, GenericFactory, NSNotificationCenter;

__attribute__((visibility("hidden")))
@interface ConversationCenter : NSObject {//SKObject {
	DomainObjectPool* _domainObjectPool;
	NSNumber* _lastLiveConversationObjectID;
	GenericFactory* _genericFactory;
	ALESkyLib* _skylib;
	NSNotificationCenter* _notificationCenter;
}
@property(retain, nonatomic) NSNumber* lastLiveConversationObjectID;
@property(retain, nonatomic) NSNotificationCenter* notificationCenter;
@property(retain, nonatomic) GenericFactory* genericFactory;
@property(retain, nonatomic) DomainObjectPool* domainObjectPool;
@property(retain, nonatomic) ALESkyLib* skylib;
//-(void).cxx_destruct;
-(void)conversationDidGoLive:(id)conversation;
-(BOOL)joinConversationWithHostingIdentity:(id)hostingIdentity token:(id)token;
-(id)joinConversationWithBlob:(id)blob;
-(id)conversationCurrentParticipantWasLastLiveIn;
-(id)conversationWithContact:(id)contact;
-(id)conversationWithConversationIdentity:(id)conversationIdentity;
-(id)conversationWithConversationID:(unsigned)conversationID;
-(id)conversationWithIdentities:(id)identities;
-(id)conversation;
-(void)dealloc;
-(void)awakeFromAutowire;
@end

