//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  4 2016 10:44:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, Schema, User;

//@interface Media : FLEntityValue
//{
//    Schema *_schema;
//    shared_ptr_5b22ea76 _peer;
//}

@interface Media (YahooMessengerIris_1_4)

+ (id)mediaForKey:(id)arg1;

@property(readonly, nonatomic) NSString *importContentUri;
@property(readonly, nonatomic) NSString *downloadMediaType;
@property(readonly, nonatomic) NSString *downloadUrl;
@property(readonly, nonatomic) NSString *originalUrl;
@property(readonly, nonatomic) int duration;
@property(readonly, nonatomic) int height;
@property(readonly, nonatomic) int width;
@property(readonly, nonatomic) NSString *kind;
@property(readonly, nonatomic) _Bool complete;
@property(readonly, nonatomic) User *user;
- (id)peer;
- (id)initWithSchema:(id)arg1 peer:(id)arg2;

@end

