/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"

@interface CKCarrierReceiveController : NSObject
{
}

+ (id)sharedInstance;
- (void)dealloc;
- (id)init;
- (void)_unregisterForCTNotifications;
- (void)_registerForCTNotifications;
- (void)_clearPendingIncomingMessageQueue;
- (void)_processReceivedMessage:(id)arg1;

@end

