/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "SBAwayViewPluginController.h"

//#import "PHCallParticipantsViewDelegate-Protocol.h"
//#import "SBLockScreenBundleController-Protocol.h"

@class CNContact, NSString, PHCallParticipantsView, PHContactsClient, TUCall;
/*
@interface InCallLockScreenController : SBAwayViewPluginController <PHCallParticipantsViewDelegate, SBLockScreenBundleController>
{
    _Bool _shouldShowInCallInfo;
    _Bool _showingInCallInfo;
    PHContactsClient *_contactsClient;
    PHCallParticipantsView *_callParticipantsView;
    CNContact *_contact;
    TUCall *_displayedCall;
    NSString *_labelDisplayString;
    NSString *_localizedLabel;
    NSString *_nameDisplayString;
}*/
@interface InCallLockScreenController (iOS9)
+ (id)rootViewController;
@property(nonatomic) _Bool showingInCallInfo; // @synthesize showingInCallInfo=_showingInCallInfo;
@property(nonatomic) _Bool shouldShowInCallInfo; // @synthesize shouldShowInCallInfo=_shouldShowInCallInfo;
@property(copy, nonatomic) NSString *nameDisplayString; // @synthesize nameDisplayString=_nameDisplayString;
@property(copy, nonatomic) NSString *localizedLabel; // @synthesize localizedLabel=_localizedLabel;
@property(copy, nonatomic) NSString *labelDisplayString; // @synthesize labelDisplayString=_labelDisplayString;
@property(retain, nonatomic) TUCall *displayedCall; // @synthesize displayedCall=_displayedCall;
@property(retain, nonatomic) CNContact *contact; // @synthesize contact=_contact;
@property(retain, nonatomic) PHCallParticipantsView *callParticipantsView; // @synthesize callParticipantsView=_callParticipantsView;
//- (void).cxx_destruct;
- (void)contactStoreDidChange:(id)arg1;
- (void)callStatusChanged:(id)arg1;
- (void)backlightLevelChanged:(id)arg1;
- (void)secondTickTimerFired;
- (void)_removeObservers;
- (void)_addObservers;
- (id)overrideStringForParticipantsView:(id)arg1;
- (_Bool)shouldShowSingleDurationLabelInParticipantsView:(id)arg1;
- (_Bool)shouldShowInfoButtonForParticipantAtIndex:(unsigned long long)arg1 inParticipantsView:(id)arg2;
- (unsigned long long)numberOfParticipantsForParticipantsView:(id)arg1;
- (unsigned short)activityStateForParticipantAtIndex:(unsigned long long)arg1 inParticipantsView:(id)arg2;
- (id)supplementalParticipantLabelFormatStringAtIndex:(unsigned long long)arg1 inParticipantsView:(id)arg2;
- (id)labelForParticipantAtIndex:(unsigned long long)arg1 inParticipantsView:(id)arg2;
- (id)nameForParticipantAtIndex:(unsigned long long)arg1 inParticipantsView:(id)arg2;
- (id)contactForParticipantAtIndex:(unsigned long long)arg1 inParticipantsView:(id)arg2;
@property(readonly, nonatomic) PHContactsClient *contactsClient; // @synthesize contactsClient=_contactsClient;
- (void)updateLabelDisplayString;
- (void)reload;
- (_Bool)multipleCallsExist;
- (void)fetchCallInformation:(id *)arg1 name:(id *)arg2 label:(id *)arg3;
- (void)addConstraints;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)showDateView;
- (_Bool)shouldShowLockStatusBarTime;
- (unsigned long long)overlayStyle;
- (unsigned long long)presentationStyle;
- (long long)pluginPriority;
- (void)loadView;
- (_Bool)allowsLockScreenCamera;
- (_Bool)allowsLockScreenMediaControls;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

