/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "DateTimeController.h"

@interface DateTimeController (Private)
- (id)useAutomaticTime:(id)arg1;
- (void)setUseAutomaticTime:(id)arg1 specifier:(id)arg2;
- (id)is24HourTime:(id)arg1;
- (void)set24HourTime:(id)arg1 specifier:(id)arg2;
- (void)significantTimeChange:(id)arg1;
- (id)timeZoneValue:(id)arg1;
- (void)setTimeZoneValue:(id)arg1 specifier:(id)arg2;
@end

