/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "VDBObject.h"

@class NSData, NSNumber, NSSet, NSString, VDBMessage;
/*
@interface VDBAttachment : VDBObject
{
    id <VDBModelInjection> _injection;
    NSString *_state;
    NSString *_ID;
    unsigned long long _idType;
    NSString *_url;
    NSString *_photoLibraryAssetIdentifier;
    NSString *_pictureDoodleType;
    NSNumber *_seq;
    NSNumber *_fileSize;
    NSString *_type;
    NSString *_bucket;
    NSNumber *_duration;
    NSNumber *_range;
    NSNumber *_isFromPublicGroup;
    NSNumber *_isFormatted;
    NSString *_name;
    NSString *_thumbnailBucket;
    NSString *_thumbnailID;
    NSString *_thumbnailUrl;
    NSString *_filename;
    NSData *_encryptionParams;
    NSString *_animatedMessageInfo;
    NSNumber *_cachePolicy;
    NSSet *_messages;
    NSNumber *_mediaDownloadType;
    id <FICEntity> _thumbnailCacheEntity;
    NSString *_commonThumbnailCacheFormatName;
}*/
@interface VDBAttachment (Viber_6_1_5)
+ (id)changedKeysForManagedObjectChangedKeyPaths:(id)arg1;
+ (id)relationshipModelClassesByPropertyKey;
+ (id)managedObjectEntityName;
@property(readonly, nonatomic) NSString *commonThumbnailCacheFormatName; // @synthesize commonThumbnailCacheFormatName=_commonThumbnailCacheFormatName;
@property(readonly, nonatomic) id <FICEntity> thumbnailCacheEntity; // @synthesize thumbnailCacheEntity=_thumbnailCacheEntity;
@property(copy, nonatomic) NSNumber *mediaDownloadType; // @synthesize mediaDownloadType=_mediaDownloadType;
@property(copy, nonatomic) NSSet *messages; // @synthesize messages=_messages;
@property(copy, nonatomic) NSNumber *cachePolicy; // @synthesize cachePolicy=_cachePolicy;
@property(copy, nonatomic) NSString *animatedMessageInfo; // @synthesize animatedMessageInfo=_animatedMessageInfo;
@property(copy, nonatomic) NSData *encryptionParams; // @synthesize encryptionParams=_encryptionParams;
@property(copy, nonatomic) NSString *filename; // @synthesize filename=_filename;
@property(copy, nonatomic) NSString *thumbnailUrl; // @synthesize thumbnailUrl=_thumbnailUrl;
@property(copy, nonatomic) NSString *thumbnailID; // @synthesize thumbnailID=_thumbnailID;
@property(copy, nonatomic) NSString *thumbnailBucket; // @synthesize thumbnailBucket=_thumbnailBucket;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSNumber *isFormatted; // @synthesize isFormatted=_isFormatted;
@property(copy, nonatomic) NSNumber *isFromPublicGroup; // @synthesize isFromPublicGroup=_isFromPublicGroup;
@property(copy, nonatomic) NSNumber *range; // @synthesize range=_range;
@property(copy, nonatomic) NSNumber *duration; // @synthesize duration=_duration;
@property(copy, nonatomic) NSString *bucket; // @synthesize bucket=_bucket;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSNumber *fileSize; // @synthesize fileSize=_fileSize;
@property(copy, nonatomic) NSNumber *seq; // @synthesize seq=_seq;
@property(copy, nonatomic) NSString *pictureDoodleType; // @synthesize pictureDoodleType=_pictureDoodleType;
@property(copy, nonatomic) NSString *photoLibraryAssetIdentifier; // @synthesize photoLibraryAssetIdentifier=_photoLibraryAssetIdentifier;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) unsigned long long idType; // @synthesize idType=_idType;
@property(copy, nonatomic) NSString *ID; // @synthesize ID=_ID;
@property(copy, nonatomic) NSString *state; // @synthesize state=_state;
- (void)setInjection:(id)arg1;
- (id)injection;
//- (void).cxx_destruct;
@property(readonly, nonatomic) VDBMessage *anyMessage;
- (id)previewWithDirectoryName:(id)arg1;
@property(readonly, nonatomic) NSString *tempPreviewPathFormattedMessageeThumbnail;
@property(readonly, nonatomic) NSString *bigPreviewPath;
@property(readonly, nonatomic) NSString *previewPath;
@property(readonly, nonatomic) _Bool canBeRedowloadedUsingID;
@property(readonly, nonatomic) _Bool canBeRedowloadedUsingURL;
- (void)setNilValueForKey:(id)arg1;
- (void)stickerDidDownload:(id)arg1;
- (void)updateStickerCacheFormatName;
- (void)didCompleteDeserializationFromManagedObject:(id)arg1;
- (void)dealloc;
- (void)mergeValueForKey:(id)arg1 fromModel:(id)arg2;

@end

