/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import "LINE-Structs.h"
//#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface TalkUtil : NSObject {//XXUnknownSuperclass {
}
+(void)globalResignFirstResponderRec:(id)rec;
+(void)globalResignFirstResponder;
+(void)globallyDismissKeyboard;
+(BOOL)isReachable;
+(BOOL)isKR;
+(BOOL)isJP;
+(id)currentLocaleCountryCode;
+(id)currentLanguageCode;
+(void)makeAPhoneCall:(id)call;
+(id)makeContentImageBubble:(id)bubble maxSize:(CGSize)size minSize:(CGSize)size3 mask:(id)mask;
+(id)resizeImage:(id)image to:(CGSize)to;
+(CGSize)resizeTo:(CGSize)to source:(CGSize)source;
+(CGSize)resizeTo:(CGSize)to source:(CGSize)source withMinimumSize:(CGSize)minimumSize;
+(BOOL)isNaverAccount;
+(BOOL)isEmpty:(id)empty;
+(BOOL)isNotEmpty:(id)empty;
+(int)iOS5RowAnimationAutomatic;
+(BOOL)iOS6;
+(BOOL)iOS5;
+(void)initialize;
@end

