/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SBUIFullscreenAlertController.h"

@class UIView;

@interface SBUISlidingFullscreenAlertController : SBUIFullscreenAlertController
{
    UIView *_topBar;
    UIView *_bottomBar;
    BOOL _animatingIn;
    BOOL _animatingOut;
}

- (BOOL)isSlidingViewController;
- (BOOL)displaysAboveStatusBar;
- (id)newTopBar;
- (id)newBottomBar;
- (void)viewDidLoad;
- (void)dealloc;
- (id)backgroundView;
- (BOOL)isShowingWallpaper;
- (BOOL)shouldShowBottomBar;
- (void)prepareToAnimateDisplayIn;
- (void)performAnimateDisplayIn;
- (void)animateDisplayIn:(float)arg1 middleDelay:(float)arg2;
- (void)viewWillAnimateOut;
- (void)_fadeOutCompleted:(id)arg1;
- (BOOL)_animatingToHomescreenWallpaper;
- (void)animateViewOut;
- (void)viewWillAppear:(BOOL)arg1;
- (BOOL)viewIsReadyToBeRemoved;
- (void)_updateLayoutForStatusBarAndInterfaceOrientation;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)finishedAnimatingIn;
- (void)finishedAnimatingOut;
@property(readonly, nonatomic) UIView *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(readonly, nonatomic) UIView *topBar; // @synthesize topBar=_topBar;

@end