/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import <XXUnknownSuperclass.h> // Unknown library
//#import "Viber-Structs.h"
//#import "VIBUserPhotoUploaderDelegate.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface VIBUserDetailsManager : NSObject {// XXUnknownSuperclass <VIBUserPhotoUploaderDelegate> {
@private
	BOOL updatePhotoImmediately;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL updatePhotoImmediately;
+(id)sharedVIBUserDetailsManager;
-(void)photoUploaderDidFailUploadingFile:(id)photoUploader;
-(void)photoUploaderDidUploadFile:(id)photoUploader withID:(id)anId;
-(void)saveMyUserDetails:(id)details;
-(void)saveUserPhoto:(id)photo;
-(void)saveUserPhoto:(id)photo immediately:(BOOL)immediately;
-(void)showAddPhotoActionSheetInView:(id)view;
-(void)onUpdateUserName:(unsigned long)name;
-(void)onUpdateUserPhoto:(unsigned long)photo;
-(void)updateMyDetailsIfNecessary;
-(void)removeMyPhotoAndNotify;
-(void)removeMyPhoto;
-(void)removeFacebookInfo;
-(void)updateMyPhoto;
-(id)temporaryMyUserPhoto;
-(void)saveTemporaryMyUserPhoto:(id)photo;
-(id)temporaryMyUserName;
-(void)resetTemporarySavedUserName;
-(void)saveTemporaryMyUserName:(id)name;
-(void)saveMyUserName:(id)name;
-(id)getMyUserPhotoPath;
-(id)getMyUserPhoto;
-(id)getMyUserName;
-(void)setIsAddYourDetailsScreenShown;
-(void)downloadCurrentUserPhotoAfterSync;
-(void)downloadCurrentUserDetailsIfExists;
-(id)copyWithZone:(NSZone*)zone;
@end

