/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SBAlertDisplay.h"

@class SBDeviceLockView, SBEmergencyCallView, UIImage, UIImageView, UIView;

@interface SBSlidingAlertDisplay : SBAlertDisplay
{
    UIImageView *_backgroundView;
    UIImage *_defaultDesktopImage;
    UIView *_topBar;
    UIView *_bottomBar;
    UIView *_overlayView;
    SBDeviceLockView *_deviceLockView;
    SBEmergencyCallView *_emergencyCallView;
    UIView *_emergencyCallTopBar;
    BOOL _playKeyboardClicks;
    unsigned int _animatingEmergencyCall:1;
    unsigned int _animatingIn:1;
    unsigned int _animatingOut:1;
    unsigned int _animatingDeviceLock:1;
    unsigned int _showingDeviceLock:1;
    unsigned int _showingDeviceUnlockFailure:1;
    unsigned int _isDisplayingWallpaper:1;
    int _currentOrientation;
    struct CGAffineTransform _originalStatusBarTransform;
}

+ (id)newTopBarForInstance:(id)arg1;
+ (id)newBottomBarForInstance:(id)arg1;
+ (void)setDisplayPropertiesForActivationOfAlert:(id)arg1;
- (void)_setTopBarImage:(id)arg1 shadowColor:(id)arg2;
- (void)_resetStatusTextView;
- (BOOL)shouldEnableWirelessLCD;
- (BOOL)shouldShowBottomBar;
- (id)_topBarLCDImage;
- (id)_topBarLCDShadow;
- (void)updateTopBarBackground;
- (void)rightNavigationButtonPressed;
- (void)leftNavigationButtonPressed;
- (void)_clearUnlockFailedIndicator;
- (void)_showUnlockFailedIndicator;
- (id)_defaultDesktopImage;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)lockBar;
- (BOOL)isFullscreen;
- (struct CGRect)middleFrame;
- (void)getFrameForTopButton:(struct CGRect *)arg1 bottomButton:(struct CGRect *)arg2;
- (BOOL)showsDesktopImage;
- (BOOL)isShowingWallpaper;
- (void)updateDesktopImage:(id)arg1;
- (void)finishedAnimatingIn;
- (void)finishedAnimatingOut;
- (BOOL)shouldAnimateIconsIn;
- (BOOL)shouldAnimateIconsOut;
- (BOOL)isAnimatingOut;
- (int)currentOrientation;
- (void)_fadeOutCompletedWithDisplayDisablingIconUnscatter:(BOOL)arg1;
- (void)_fadeOutCompleted:(id)arg1;
- (void)setMiddleContentAlpha:(float)arg1;
- (BOOL)isReadyToBeRemovedFromView;
- (float)durationForOthersActivation;
- (void)dismiss;
- (void)beginAnimatingDisplayIn:(BOOL)arg1;
- (void)performAnimateDisplayIn;
- (void)animateDisplayIn:(float)arg1 middleDelay:(float)arg2 animateStatusBar:(BOOL)arg3;
- (void)alertDisplayWillBecomeVisible;
- (void)layoutForInterfaceOrientation:(int)arg1;
- (BOOL)isShowingDeviceLock;
- (BOOL)_shouldZoomDeviceLockView;
- (void)_zoomInDeviceLockViewWithDelay:(double)arg1;
- (void)_zoomOutDeviceLockViewWithDelay:(double)arg1;
- (BOOL)topBarIsVisible;
- (BOOL)bottomBarIsVisible;
- (void)_updateOverlayViewFrame;
- (void)setShowingDeviceLock:(BOOL)arg1 duration:(float)arg2;
- (void)setShowingDeviceLock:(BOOL)arg1;
- (void)setShowingDeviceLock:(BOOL)arg1 animated:(BOOL)arg2;
- (void)animateToShowingDeviceLock:(BOOL)arg1 duration:(float)arg2;
- (void)_animateToHidingOrShowingDeviceLockFinished;
- (void)animateToShowingDeviceLockFinished;
- (void)animateToHidingDeviceLockFinished;
- (void)deviceUnlockSucceeded;
- (void)deviceUnlockFailed;
- (void)_enableEntry;
- (BOOL)shouldShowBlockedRedStatus;
- (void)showBlockedStatus;
- (void)removeBlockedStatus;
- (BOOL)shouldUseTransparentStatusBar;
- (BOOL)isDisplayingErrorStatus;
- (void)_entryFinishedWithPassword:(id)arg1;
- (void)deviceUnlockCanceled;
- (void)deviceLockViewWillAnimateMinimization:(id)arg1;
- (void)deviceLockViewWillAnimateMaximization:(id)arg1;
- (void)deviceLockViewPasscodeDidChange:(id)arg1;
- (void)deviceLockViewPasscodeEntered:(id)arg1;
- (void)deviceLockViewCancelButtonPressed:(id)arg1;
- (void)deviceLockViewEmergencyCallButtonPressed:(id)arg1;
- (int)requiredUnlockStyle;
- (BOOL)shouldShowEmergencyCallButton;
- (void)_moveTopBarForDoubleHeightStatusBar:(BOOL)arg1;
- (void)_updateDeviceLockFrameForDoubleHeightStatusBar:(BOOL)arg1;
- (void)alertWindowResizedFromContentFrame:(struct CGRect)arg1 toContentFrame:(struct CGRect)arg2;
- (void)_animateView:(id)arg1 direction:(int)arg2;
- (void)animateToEmergencyCall;
- (void)emergencyCallWasDisplayed;
- (void)animateFromEmergencyCallWithDuration:(float)arg1;
- (void)emergencyCallWasRemoved;
- (id)bottomBar;
- (id)topBar;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (BOOL)shouldAddClippingViewDuringRotation;

@end

