/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"

@interface SBSMSManager : NSObject
{
    int _badgeState;
}

+ (id)sharedSMSManager;
- (void)messageSent:(id)arg1;
- (void)messageSendError:(id)arg1;
- (void)messageReceived:(id)arg1;
- (id)init;
- (id)badgeNumberOrString;
- (void)setBadge:(id)arg1 badgeState:(int)arg2;
- (void)updateSMSBadgeToState:(int)arg1;
- (void)updateSMSBadges;
- (void)markMessageAsRead:(id)arg1;
@property(nonatomic) int badgeState; // @synthesize badgeState=_badgeState;

@end

