/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "RTLoginState.h"

//#import "RTLoginCookiesFetcherDelegate-Protocol.h"

@class NSHTTPCookieStorage, NSString, RTCookieJarDefender, RTLoginCookiesFetcher, RTLoginCredentialStore;

@interface RTAcquiringCookiesState : NSObject //RTLoginState <RTLoginCookiesFetcherDelegate>
{
    BOOL mLoginInfo;
    BOOL _fetchScrumb;
    RTLoginCookiesFetcher *mCookiesFetcher;
    RTCookieJarDefender *mCookieJarDefender;
    int mCookieFetchType;
    RTLoginCredentialStore *mCredentialStore;
    NSHTTPCookieStorage *_sharedCookieStorage;
}

@property(nonatomic) BOOL fetchScrumb; // @synthesize fetchScrumb=_fetchScrumb;
@property(retain, nonatomic) NSHTTPCookieStorage *sharedCookieStorage; // @synthesize sharedCookieStorage=_sharedCookieStorage;
@property(retain, nonatomic) RTLoginCredentialStore *credentialStore; // @synthesize credentialStore=mCredentialStore;
@property(nonatomic) int cookieFetchType; // @synthesize cookieFetchType=mCookieFetchType;
@property(retain, nonatomic) RTCookieJarDefender *cookieJarDefender; // @synthesize cookieJarDefender=mCookieJarDefender;
@property(nonatomic, getter=hasLoginInfo) BOOL loginInfo; // @synthesize loginInfo=mLoginInfo;
//- (void).cxx_destruct;
- (void)leaveStateWithError:(id)arg1;
- (void)didFailWithError:(id)arg1;
- (void)leaveStateOnSuccess;
- (void)didLoginWithInfo:(id)arg1;
- (id)sessionParameters;
- (id)sessionState;
@property(readonly, nonatomic) RTLoginCookiesFetcher *cookiesFetcher; // @synthesize cookiesFetcher=mCookiesFetcher;
- (void)leave;
- (void)informWatchersWithParams:(id)arg1;
- (void)enter;
- (BOOL)canLeaveTo:(id)arg1;
- (BOOL)canEnter;
- (id)initWithContext:(id)arg1 delegate:(id)arg2 logComponent:(id)arg3 stateFactory:(id)arg4 credentialStore:(id)arg5 cookieJarDefender:(id)arg6 sharedCookieStorage:(id)arg7 fetchScrumb:(BOOL)arg8;
- (id)initWithContext:(id)arg1 delegate:(id)arg2 logComponent:(id)arg3 stateFactory:(id)arg4 credentialStore:(id)arg5 cookieJarDefender:(id)arg6 fetchScrumb:(BOOL)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

