//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  4 2016 10:44:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFetchedResultsController, NSManagedObjectContext, TNDRDataManager;

@interface TNDRDataInspector : NSObject
{
    NSFetchedResultsController *_frcGroups;
    NSFetchedResultsController *_frcUsers;
    NSFetchedResultsController *_frcMatchesNew;
    NSFetchedResultsController *_frcMatchesMessages;
}

+ (id)di;
@property(retain, nonatomic) NSFetchedResultsController *frcMatchesMessages; // @synthesize frcMatchesMessages=_frcMatchesMessages;
@property(retain, nonatomic) NSFetchedResultsController *frcMatchesNew; // @synthesize frcMatchesNew=_frcMatchesNew;
@property(retain, nonatomic) NSFetchedResultsController *frcUsers; // @synthesize frcUsers=_frcUsers;
@property(retain, nonatomic) NSFetchedResultsController *frcGroups; // @synthesize frcGroups=_frcGroups;

- (void)faultAllMatches:(id)arg1 inContext:(id)arg2;
- (void)faultAllUsers:(id)arg1 inContext:(id)arg2;
- (void)faultAllGroups:(id)arg1 inContext:(id)arg2;
- (id)groupRecommendationsInContext:(id)arg1;
- (id)userRecommendationsInContext:(id)arg1;
- (id)groupsWithID:(id)arg1 inContext:(id)arg2;
- (id)usersWithID:(id)arg1 inContext:(id)arg2;
- (id)allCurrentUserGroupsInContext:(id)arg1;
- (id)allGroupIDsInContext:(id)arg1;
- (id)allGroupsInContext:(id)arg1;
- (id)myGroupInContext:(id)arg1;
- (id)groupRecsInContext:(id)arg1;
- (id)userRecsInContext:(id)arg1;
- (id)matchesMessagesInContext:(id)arg1;
- (id)matchesMessages;
- (id)matchesNewInContext:(id)arg1;
- (id)matchesNew;
- (unsigned long long)countTotalRecs;
- (unsigned long long)countGroupRecs;
- (unsigned long long)countUserRecs;
- (void)setupMatchesFRC;
- (void)setupGroupFRC;
- (void)setupUserFRC;
@property(readonly, nonatomic) NSManagedObjectContext *defaultContext;
@property(readonly, nonatomic) TNDRDataManager *dm;
- (void)setup;
- (id)init;

@end

