/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import <XXUnknownSuperclass.h> // Unknown library
//#import "UINavigationControllerDelegate.h"
//#import "NSFetchedResultsControllerDelegate.h"
//#import "UIAlertViewDelegate.h"
//#import "LINE-Structs.h"
//#import "UIApplicationDelegate.h"
//#import "PasscodeViewControllerDelegate.h"
//#import "UITabBarControllerDelegate.h"
//#import "BWQuincyManagerDelegate.h"

@class MessageViewController, MBTimelineViewController, PasscodeViewController, NSString, AVAudioPlayer, UITabBarController, ChatListViewController, SettingsViewController, MoreViewController, NSFetchedResultsController, RecommendationViewController, UIWindow, FriendsViewController, NLManagedMetadata;

__attribute__((visibility("hidden")))
@interface TalkAppDelegate : NSObject {//XXUnknownSuperclass <UIApplicationDelegate, NSFetchedResultsControllerDelegate, PasscodeViewControllerDelegate, UITabBarControllerDelegate, UINavigationControllerDelegate, UIAlertViewDelegate, BWQuincyManagerDelegate> {
	NSFetchedResultsController* fetchedResultsController_;
	NSString* _openChatMID;
	BOOL _checkedRegistrationState;
	BOOL _showingLaunchImage;
	NLManagedMetadata* _managedMetadata;
	BOOL isShowingCallWindow;
	BOOL statusBarWasNotHidden;
	BOOL migratingCoreData;
	BOOL returningFromBackground;
	BOOL _launchingApplication;
	BOOL _isLocked;
	BOOL _navigationInProgress;
	AVAudioPlayer* player;
	PasscodeViewController* _passcodeViewController;
	UIWindow* _passcodeWindow;
	UIWindow* callWindow;
	UIWindow* _window;
	UITabBarController* _tabBarController;
	NSString* temporaryResourceUrl_;
	NSString* temporarySourceApplication_;
	int _applicationState;
	int _unreadMessageCount;
}
@property(retain, nonatomic) UIWindow* window;
@property(assign, nonatomic) BOOL navigationInProgress;
@property(retain, nonatomic) NSString* temporarySourceApplication;
@property(retain, nonatomic) NSString* temporaryResourceUrl;
@property(assign, nonatomic) BOOL statusBarWasNotHidden;
@property(assign, nonatomic) BOOL isShowingCallWindow;
@property(retain, nonatomic) UIWindow* callWindow;
@property(retain, nonatomic) UIWindow* passcodeWindow;
@property(retain, nonatomic) PasscodeViewController* passcodeViewController;
@property(retain, nonatomic) AVAudioPlayer* player;
@property(readonly, assign, nonatomic) NSFetchedResultsController* fetchedResultsController;
@property(assign, nonatomic) int unreadMessageCount;
@property(assign, nonatomic) BOOL isLocked;
@property(retain) NSString* openChatMID;
@property(assign) int applicationState;
@property(assign, nonatomic) BOOL launchingApplication;
@property(assign, nonatomic) BOOL returningFromBackground;
@property(assign, nonatomic) BOOL migratingCoreData;
@property(readonly, assign, nonatomic) int interfaceOrientation;
@property(readonly, assign, nonatomic) SettingsViewController* settingsViewController;
@property(readonly, assign, nonatomic) RecommendationViewController* recommendationViewController;
@property(readonly, assign, nonatomic) MBTimelineViewController* timelineViewController;
@property(readonly, assign, nonatomic) MessageViewController* messageViewController;
@property(readonly, assign, nonatomic) ChatListViewController* chatListViewController;
@property(readonly, assign, nonatomic) MoreViewController* moreViewController;
@property(readonly, assign, nonatomic) FriendsViewController* friendsViewController;
@property(retain, nonatomic) UITabBarController* tabBarController;
+(id)badgeValueForUnreadMessageCount:(int)unreadMessageCount;
+(id)sharedAppDelegate;
//-(void).cxx_destruct;
-(void)shutDown;
-(void)processAppAuthTask;
-(BOOL)needDismissWithLocKey:(id)locKey;
-(void)passcodeViewControllerUnlocked:(id)unlocked;
-(void)didRecieveChangedTheme:(id)theme;
-(void)releaseSubviews:(id)subviews;
-(void)callViewDidUnloadWithViewController:(id)callView currentViewController:(id)controller;
-(void)releaseUnvisibleViewControllers;
-(void)didReceiveCallWindowWillMaximizing:(id)didReceiveCallWindow;
-(void)didReceiveCallWindowWillMinimizing:(id)didReceiveCallWindow;
-(void)didReceiveCallWindowDidDisappear:(id)didReceiveCallWindow;
-(void)didReceiveCallWindowDidAppear:(id)didReceiveCallWindow;
-(void)openChatWithMID:(id)mid type:(int)type beforeSave:(id)save beforeOpen:(id)open;
-(BOOL)application:(id)application openURL:(id)url sourceApplication:(id)application3 annotation:(id)annotation;
-(void)openURL:(id)url baseViewController:(id)controller;
-(void)openURL:(id)url;
-(void)showSharingTargetSelectorViewWithItem:(id)item;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)syncAppBadge;
-(void)updateBadgeOnChatsTab:(int)tab;
-(void)setupChatTabBadge;
-(void)application:(id)application didReceiveRemoteNotification:(id)notification fetchCompletionHandler:(id)handler;
-(void)application:(id)application didReceiveRemoteNotification:(id)notification;
-(void)application:(id)application didReceiveLocalNotification:(id)notification;
-(void)application:(id)application didFailToRegisterForRemoteNotificationsWithError:(id)error;
-(void)application:(id)application didRegisterForRemoteNotificationsWithDeviceToken:(id)deviceToken;
-(void)navigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)__delayed__unblockNavigationFlag;
-(void)tabBarController:(id)controller didSelectViewController:(id)controller2;
-(BOOL)tabBarController:(id)controller shouldSelectViewController:(id)controller2;
-(void)updateBadgeOnTimelineTab;
-(void)__delayed__updateNotiBadge;
-(void)initTabBarControl;
-(void)initTabBarDesign;
-(id)make3rdRootVCInTab;
-(id)selectedViewController;
-(id)currentVisibleViewController;
-(id)selectMoreView;
-(BOOL)isChatTabSelected;
-(id)selectChatListViewByNavigationSchemeWithAnimation:(BOOL)animation;
-(id)selectChatListViewWithAnimation:(BOOL)animation;
-(id)selectedChatListViewWithAnimationIfNeeded;
-(id)selectChatListView;
-(id)selectTimelineView;
-(id)selectRecommendationView;
-(id)selectFriendListView;
-(id)friendListViewController;
-(id)selectFriendsView;
-(id)selectFriendsViewNoAnimation;
-(void)dismissNotificationCenterPopupIfExists;
-(void)removeMyHomeViewerIfExists;
-(void)removeUserInfoViewIfExists;
-(void)runProfileUpdateScenario;
-(void)closeAllWindowsIfExists;
-(void)closeAllPopupsIfExists;
-(void)doNotMarkChatAsReadWhenChatRoomOpened:(id)opened;
-(void)processRemoteNotification:(id)notification fetchCompletionHandler:(id)handler;
-(void)processRemoteNotification:(id)notification;
-(void)removeMigrationWindow;
-(void)processLocalNotification:(id)notification;
-(BOOL)needToMoveChatRoomWithLocKey:(id)locKey;
-(void)dismissIfExistModalViewController;
-(id)viewControllerClassNamesNotToDismiss;
-(BOOL)isCafeWritingState:(id)state;
-(void)dismissAlertViewIfExists;
-(void)dismissActionSheetIfExists;
-(void)dismissAllModalViews;
-(void)removeUFOLineSinceIOS7;
-(void)createMainWindow;
-(void)discardPasscodeView;
-(void)preparePasscodeView;
-(void)dismissPasscodeLock;
-(void)showPasscodeLock;
-(void)dismissLaunchImage;
-(void)presentLaunchImage;
-(void)checkRegistrationState:(unsigned)state;
-(void)applicationProtectedDataDidBecomeAvailable:(id)applicationProtectedData;
-(void)applicationWillTerminate:(id)application;
-(void)applicationDidReceiveMemoryWarning:(id)application;
-(void)applicationDidBecomeActive:(id)application;
-(void)applicationWillEnterForeground:(id)application;
-(void)applicationDidEnterBackground:(id)application;
-(void)applicationWillResignActive:(id)application;
-(BOOL)application:(id)application didFinishLaunchingWithOptions:(id)options;
-(void)initializeLineApplication;
-(void)checkNoName;
-(void)startLineModules;
-(void)removeObservers;
-(void)addObservers;
-(void)initializeLineApplication:(id)application withOptions:(id)options;
-(void)checkAndShowPhoneNumberOrSNSVerificationIfBothNotFound;
-(void)initializeEmojiComponents;
@end

