/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import <XXUnknownSuperclass.h> // Unknown library
//#import "SBUnlockActionHandler.h"
//#import "SBLockScreenNotificationViewDelegate.h"
//#import "SBLockScreenNotificationModel.h"
//#import "SBUIBannerSource.h"
//#import "SBVolumePressBandit.h"
//#import "SBUIBannerTargetManagerObserver.h"
//#import "SpringBoard-Structs.h"
//#import "SBLockScreenNotificationBannerItemDelegate.h"
//#import "BBObserverDelegate.h"

@class BBObserver, NSMutableArray, SBUnlockActionContext, SBLockScreenNotificationListView;
@protocol SBLockScreenNotificationListDelegate, SBUIBannerTarget;

__attribute__((visibility("hidden")))
@interface SBLockScreenNotificationListController : NSObject  {// XXUnknownSuperclass <SBLockScreenNotificationViewDelegate, SBLockScreenNotificationModel, BBObserverDelegate, SBVolumePressBandit, SBUIBannerSource, SBUIBannerTargetManagerObserver, SBUnlockActionHandler, SBLockScreenNotificationBannerItemDelegate> {
	SBLockScreenNotificationListView* _notificationView;
	id<SBLockScreenNotificationListDelegate> _delegate;
	BBObserver* _observer;
	NSMutableArray* _listItems;
	NSMutableArray* _realertTimers;
	BOOL _hibernating;
	BOOL _quietModeEnabled;
	SBUnlockActionContext* _actionContext;
	id<SBUIBannerTarget> _bannerTarget;
	NSMutableArray* _listItemsBannerQueue;
	BOOL _bannersEnabled;
	BOOL _isOnscreen;
	BOOL _hasMissedUnreadNotifications;
	int _messagePrivacyRevealState;
	BOOL _hasAnyContent;
}
@property(assign, nonatomic) BOOL isHibernating;
@property(assign, nonatomic, getter=isBannersEnabled) BOOL bannersEnabled;
@property(readonly, assign, nonatomic) BOOL quietModeEnabled;
@property(retain, nonatomic) SBUnlockActionContext* unlockActionContext;
@property(assign, nonatomic) BOOL hasAnyContent;
@property(assign, nonatomic) id<SBLockScreenNotificationListDelegate> delegate;
+(id)underlayPropertiesFactory;
-(void)handleVolumeIncrease;
-(void)handleVolumeDecrease;
-(void)_reloadVolumePressBanditPreference;
-(void)bannerTargetManager:(id)manager didRemoveTarget:(id)target;
-(void)bannerTargetManager:(id)manager didAddTarget:(id)target;
-(id)newBannerViewForContext:(id)context;
-(id)dequeueNextBannerItemForTarget:(id)target;
-(id)peekNextBannerItemForTarget:(id)target;
-(BOOL)_shouldAddBannerItem:(id)item;
-(void)bannerItemWasTapped:(id)tapped;
-(void)_scheduleRealerts:(id)realerts;
-(void)_killRealerts:(id)realerts;
-(void)_realertTimerFired:(id)fired;
-(void)_playSoundForBulletinIfPossible:(id)bulletinIfPossible;
-(void)_showTestBulletin;
-(id)listItemAtIndexPath:(id)indexPath;
-(unsigned)count;
-(id)lockScreenScrollView;
-(void)noteUnlockActionChanged:(id)changed;
-(void)unlockUIWithActionContext:(id)actionContext;
-(void)lockScreenViewDidEndScrollingOnPage:(int)lockScreenView;
-(void)concealForChangeInMessagePrivacy;
-(void)revealForChangeInMessagePrivacy;
-(void)clearItemsForNotificationCenter;
-(void)_sortListItems;
-(void)_updateModelAndViewForRemovalOfItem:(id)item;
-(void)_updateModelForRemovalOfItem:(id)item updateView:(BOOL)view;
-(void)_updateModelAndViewForReplacingItem:(id)replacingItem withNewItem:(id)newItem;
-(void)_updateModelAndViewForModificationOfItem:(id)item;
-(void)_updateModelAndViewForAdditionOfItem:(id)item;
-(void)updateCardItem:(id)item;
-(void)deactivateCardItem:(id)item;
-(void)activateCardItem:(id)item animated:(BOOL)animated;
-(void)_activateOrUpdateCardItem:(id)item animated:(BOOL)animated;
-(void)performSystemAlertUnlockActions;
-(id)pendOrDeactivateAlertItems;
-(void)deactivateAlertItem:(id)item;
-(BOOL)activateAlertItem:(id)item;
-(void)turnOnScreenIfNecessaryForItem:(id)item;
-(BOOL)shouldPlaySoundForItem:(id)item;
-(BOOL)shouldTreatItemAsInert:(id)inert;
-(void)observer:(id)observer noteServerConnectionStateChanged:(BOOL)changed;
-(void)observer:(id)observer noteInvalidatedBulletinIDs:(id)ids;
-(void)observer:(id)observer noteAlertBehaviorOverridesChanged:(unsigned)changed;
-(id)observer:(id)observer composedAttachmentImageForType:(int)type thumbnailData:(id)data key:(id)key;
-(id)observer:(id)observer multipleThumbnailSizeConstraintsForAttachmentType:(int)attachmentType;
-(BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)observer;
-(void)observer:(id)observer removeBulletin:(id)bulletin;
-(void)observer:(id)observer modifyBulletin:(id)bulletin;
-(void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
-(id)_listItemContainingCardItem:(id)item;
-(id)_listItemContainingSystemAlert:(id)alert;
-(id)_listItemContainingBulletinID:(id)anId;
-(id)_listItemForNewBulletin:(id)newBulletin;
-(BOOL)dismissReadNotifications;
-(BOOL)hasMissedUnreadNotifications;
-(void)setIsOnscreen:(BOOL)onscreen;
-(void)setInScreenOffMode:(BOOL)screenOffMode;
-(void)_hardwareButtonPressed:(id)pressed;
-(void)loadView;
-(void)dealloc;
-(void)prepareForTeardown;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

