/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "MMService.h"
//
//#import "MMPackageDownloadMgrExt-Protocol.h"
//#import "MMResPackageMgrExt-Protocol.h"
//#import "MMService-Protocol.h"

@class CEmoticonDB, NSMutableArray, NSRecursiveLock;

@interface CEmoticonMgr //: MMService <MMService, MMPackageDownloadMgrExt, MMResPackageMgrExt>
{
    CEmoticonDB *m_oEmoticonDB;
    NSRecursiveLock *m_oLock;
    NSMutableArray *m_arrHardCodeEmoticon;
    unsigned int m_uiLastUpdateTime;
}

+ (void)RenameEmoticon;
+ (id)GetPathOfEmoticon:(id)arg1;
+ (id)GetThumbPathOfEmoticon:(id)arg1;
+ (id)GetPathOfTempEmoticon:(id)arg1;
- (id)init;
- (void)onServiceInit;
- (void)dealloc;
- (BOOL)onServiceMemoryWarning;
- (void)InitEmoticonMgr:(id)arg1 Lock:(id)arg2;
- (void)AddHardCode:(id)arg1 Type:(unsigned long)arg2 GameType:(unsigned long)arg3 OriginPath:(id)arg4;
- (void)CopyPic:(id)arg1 From:(id)arg2;
- (void)InitLocalList;
- (id)GetEmoticonList;
- (id)AddEmoticon:(id)arg1 Type:(unsigned long)arg2 Source:(int)arg3;
- (id)AddEmoticon:(id)arg1 Type:(unsigned long)arg2 ExtInfo:(id)arg3 Source:(int)arg4;
- (BOOL)DeleteEmoticonByMD5:(id)arg1;
- (id)GetEmoticonByMD5:(id)arg1;
- (BOOL)CheckEmoticonExist:(id)arg1;
- (BOOL)IsCanDelete:(id)arg1;
- (id)GetEmojiList:(unsigned long)arg1;
- (BOOL)AddEmoji:(id)arg1;
- (BOOL)DeleteEmojiByEmoji:(id)arg1;
- (void)InitHardCodeEmojiArtList;
- (id)GetEmojiCataLogList;
- (void)UpdateEmojiArtByXml:(struct XmlReaderNode_t *)arg1;
- (void)UpdateLocalEmojiArtByData:(id)arg1;
- (void)UpdateEmojiArtFromResource;
- (void)CheckUpdate;
- (void)onPackageListUpdated:(id)arg1;
- (void)onResPackageReady:(id)arg1;
- (void)ResetEmojiArt;
- (void)ResetEmoticon;
@property(retain, nonatomic) NSRecursiveLock *m_oLock; // @synthesize m_oLock;

@end

