/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "FBMSessionClassProvidable-Protocol.h"
#import "MessageSenderDelegate-Protocol.h"

@class MQTTMessageSender, UIApplication;

@interface FBMThreadQueueSender : NSObject <MessageSenderDelegate, FBMSessionClassProvidable>
{
    MQTTMessageSender *_sender;
    UIApplication *_application;
    struct __CFDictionary *_offlineThreadingIdToObserverDictionary;
}

- (void)thread:(id)arg1 couldNotSendMessage:(id)arg2 error:(id)arg3;
- (void)thread:(id)arg1 didSendMessage:(id)arg2;
- (void)_sendNextPendingMessageForThread:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)retryMessage:(id)arg1 forThread:(id)arg2 observer:(id)arg3;
- (void)sendMessage:(id)arg1 forThread:(id)arg2 observer:(id)arg3;
- (id)initWithProviderMapData:(id)arg1;
- (void)dealloc;
- (id)initWithSender:(id)arg1 application:(id)arg2;

@end

