/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "NSObject.h"

@class CLLocation, FBMParticipantInfo, NSArray, NSDictionary, NSMutableArray, NSString;

@interface ThreadMessage : NSObject
{
    NSDictionary *_attachmentMap;
    NSString *_text;
    NSString *_offlineThreadingId;
    FBMParticipantInfo *_senderInfo;
    BOOL _isIncomplete;
    NSString *_adminSnippet;
    BOOL _isDirty;
    NSDictionary *_logMessage;
    NSString *_sessionID;
    BOOL _isSnippetMessage;
    NSDictionary *_shareMap;
    NSString *_messageId;
    BOOL _placeholder;
    long long _timestamp;
    NSMutableArray *_outgoingAttachments;
    long long _actionId;
    CLLocation *_location;
    BOOL _sendHasFailedBefore;
    long long _sendTimestamp;
    NSString *_adminText;
    NSDictionary *_coordinates;
    int _type;
    NSArray *_tags;
    int _sendState;
    NSString *_threadId;
}

+ (id)messageFromActionJSON:(id)arg1;
+ (id)messageFromJSON:(id)arg1;
+ (id)writeCoordinates:(id)arg1;
+ (id)readCoordinates:(id)arg1;
+ (id)messageFromMessage:(id)arg1;
@property(copy, nonatomic) NSString *threadId; // @synthesize threadId=_threadId;
@property(nonatomic) int sendState; // @synthesize sendState=_sendState;
@property(retain, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) NSDictionary *coordinates; // @synthesize coordinates=_coordinates;
@property(copy, nonatomic) NSString *adminText; // @synthesize adminText=_adminText;
@property(nonatomic) long long sendTimestamp; // @synthesize sendTimestamp=_sendTimestamp;
@property(nonatomic) BOOL sendHasFailedBefore; // @synthesize sendHasFailedBefore=_sendHasFailedBefore;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(nonatomic) long long actionId; // @synthesize actionId=_actionId;
@property(retain, nonatomic) NSMutableArray *outgoingAttachments; // @synthesize outgoingAttachments=_outgoingAttachments;
@property(nonatomic) long long timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) BOOL placeholder; // @synthesize placeholder=_placeholder;
@property(copy, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
@property(retain, nonatomic) NSDictionary *shareMap; // @synthesize shareMap=_shareMap;
@property(nonatomic) BOOL isSnippetMessage; // @synthesize isSnippetMessage=_isSnippetMessage;
@property(copy, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
@property(retain, nonatomic) NSDictionary *logMessage; // @synthesize logMessage=_logMessage;
@property(nonatomic) BOOL isDirty; // @synthesize isDirty=_isDirty;
@property(copy, nonatomic) NSString *adminSnippet; // @synthesize adminSnippet=_adminSnippet;
@property(nonatomic) BOOL isIncomplete; // @synthesize isIncomplete=_isIncomplete;
@property(retain, nonatomic) FBMParticipantInfo *senderInfo; // @synthesize senderInfo=_senderInfo;
@property(copy, nonatomic) NSString *offlineThreadingId; // @synthesize offlineThreadingId=_offlineThreadingId;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSDictionary *attachmentMap; // @synthesize attachmentMap=_attachmentMap;
- (id)accessibilityLabel;
- (void)prepareOutgoingAttachmentsDataWithCompletionBlock:(id)arg1;
//- (void)_prepareAttachment:(id)arg1 barrierSemaphore:(struct dispatch_semaphore_s **)arg2;
@property(readonly, nonatomic) int source;
- (unsigned long long)getStickerFbId;
- (id)getSticker;
- (id)getShare;
- (int)compareForDisplay:(id)arg1;
- (int)compareTimestampDesc:(id)arg1;
- (id)timestampDate;
- (long long)sendOrServerTimestamp;
- (void)mergeMessage:(id)arg1;
- (BOOL)isNonUserGeneratedLogMessage;
- (BOOL)isDraftEquivalentToMessage:(id)arg1;
- (BOOL)isEquivalentToMessage:(id)arg1;
@property(readonly) BOOL hasOutgoingAudioAttachment;
- (int)totalAttachmentSize;
@property(readonly) BOOL hasOutgoingPhotoAttachment;
- (BOOL)hasAttachments;
@property(readonly) BOOL displayAsSent;
@property(readonly) BOOL sendPending;
- (id)description;
- (void)dealloc;
- (id)init;

@end

