//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  4 2016 10:44:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class IGUserSession, NSMutableSet;

//@interface IGAuthHelper : NSObject
//{
//    _Bool _isForcingOut;
//    IGUserSession *_currentUserSession;
//    unsigned long long _lastAccountSwitchEntryPoint;
//    NSMutableSet *_authUserData;
//}

@interface IGAuthHelper (Instagram_8_3_0)

+ (void)doLocalLogoutStepsAffectingAllUsers;
+ (void)doLocalLogoutStepsSpecificToUser:(id)arg1;
+ (void)migrateOldCurrentUser;
+ (id)authenticatedUserFromUser:(id)arg1;
+ (id)currentUser;
+ (id)sharedAuthHelper;
@property(nonatomic) _Bool isForcingOut; // @synthesize isForcingOut=_isForcingOut;
@property(retain, nonatomic) NSMutableSet *authUserData; // @synthesize authUserData=_authUserData;
@property(nonatomic) unsigned long long lastAccountSwitchEntryPoint; // @synthesize lastAccountSwitchEntryPoint=_lastAccountSwitchEntryPoint;
@property(retain, nonatomic) IGUserSession *currentUserSession; // @synthesize currentUserSession=_currentUserSession;

- (void)swapFromCookiesOfUserWithPk:(id)arg1 toCookiesOfUserWithPk:(id)arg2;
- (_Bool)currentUserIsLoggedIn;
- (void)onProfilePictureFailed:(id)arg1;
- (void)onProfilePictureChanged:(id)arg1;
- (void)removeProfilePicture;
- (void)uploadProfilePicture:(id)arg1 fromOption:(long long)arg2;
- (id)profilePictureDataFromImage:(id)arg1;
- (id)profilePictureImageFromSourceImage:(id)arg1;
- (void)sendServerLogoutRequestForUser:(id)arg1 ssoEnabled:(_Bool)arg2 completionHandler:(id)arg3;
- (void)logOutAllUsersWithCompletionHandler:(id)arg1 ssoEnabledUsers:(id)arg2;
- (void)logOutUser:(id)arg1 ssoEnabled:(_Bool)arg2 completionHandler:(id)arg3;
- (void)handleLoginRequiredByServer;
- (void)clearAllUsers;
- (void)clearCurrentUser;
- (void)saveCookiesForInternalUsers;
- (void)handleLoginError;
- (void)logInWithUserDictionary:(id)arg1 facebookAccessToken:(id)arg2 authLogInType:(long long)arg3;
- (void)logInWithDictionary:(id)arg1 facebookAccessToken:(id)arg2 authLogInType:(long long)arg3;
- (void)logInWithAuthenticatedUser:(id)arg1 facebookAccessToken:(id)arg2 authLogInType:(long long)arg3;
- (void)switchToAuthenticatedUserWithForce:(id)arg1 authLogInType:(long long)arg2 defaultSelectedTab:(long long)arg3 entryPoint:(unsigned long long)arg4;
- (void)switchToNilUserWithEntryPoint:(unsigned long long)arg1;
- (void)switchToLastAccessedUserWithForceDueToAddUserCancel;
- (void)switchToLastAccessedUserWithForceDueToCurrentUserLogoutWithEntryPoint:(unsigned long long)arg1;
- (void)switchToAuthenticatedUser:(id)arg1 defaultSelectedTab:(long long)arg2 entryPoint:(unsigned long long)arg3;
- (void)synchronizeUserWithKeychain:(id)arg1;
- (_Bool)hasMultipleAccounts;
- (_Bool)hasMaximumNumberOfAccounts;
- (id)currentAuthenticatedUsersSortedByAccessTime;
- (id)currentAuthenticatedUsers;
- (id)authenticatedUserMatchingUserPK:(id)arg1;
- (void)archive;
- (void)updateCurrentUser:(id)arg1;
- (void)updateCurrentUserWithDictForCurrentUser:(id)arg1;
- (void)storeLastUserPK:(id)arg1;
- (id)lastUserPK;
- (void)removeOldUserData;
- (id)oldCurrentUser;
- (void)removeOldStoredUsersData;
- (id)oldStoredUsers;
- (void)storeAuthUserData:(id)arg1;
- (id)storedAuthUserData;
- (void)unarchiveUsers;
- (void)setCurrentUser:(id)arg1;
- (void)restoreCurrentUser;
- (id)init;

@end

