//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr 19 2016 14:33:02).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

//#import "WAViewController.h"

//#import "CLLocationManagerDelegate-Protocol.h"
//#import "WACallActionViewDelegate-Protocol.h"
//#import "WACallSpamReportViewDelegate-Protocol.h"
//#import "WACallViewDelegate-Protocol.h"
//#import "WAPttRecorderDelegate-Protocol.h"
//#import "WAVoiceCallRatingViewDelegate-Protocol.h"

@class NSString, NSTimer, SoundEffect, UIImage, UIView, WACallView, WAMediaStreamUploadOperation, WAPttRecorder;
@protocol WACallViewControllerDelegate;

@interface WACallViewController : NSObject //WAViewController <CLLocationManagerDelegate, WAVoiceCallRatingViewDelegate, WACallSpamReportViewDelegate, WAPttRecorderDelegate, WACallViewDelegate, WACallActionViewDelegate>
{
    _Bool _minimized;
    _Bool _changingMinimizedState;
    NSTimer *_timer;
    _Bool _hasTimerFired;
    UIImage *_blurredImage;
    unsigned long long _backgroundTask;
    WACallView *_callView;
    _Bool _isMonitoringProximity;
    WAPttRecorder *_pttRecorder;
    double _pttRecordStartTime;
    NSTimer *_pttAudioRecorderUpdateTimer;
    _Bool _pttInterruption;
    _Bool _recordingPtt;
    WAMediaStreamUploadOperation *_voiceMsgStreamOperation;
    SoundEffect *_startRecordSoundEffect;
    SoundEffect *_stopRecordSoundEffect;
    SoundEffect *_errorRecordSoundEffect;
    NSString *_peerDisplayName;
    NSString *_peerFirstName;
    _Bool _isPeerKnown;
    _Bool _isIncomingCall;
    double _lastCallStatsTime;
    int _lastPacketLossSum;
    float _callQuality;
    double _lastBatteryPrintTime;
    int _callDurationInSeconds;
    _Bool _debugInfoHidden;
    UIView *_snapshotOfPresentingView;
    int _oldState;
    _Bool _idleTimerDisabled;
    int _callState;
    NSString *_calleeJID;
    id <WACallViewControllerDelegate> _delegate;
}

@property(nonatomic) float callQuality; // @synthesize callQuality=_callQuality;
@property(nonatomic) int callState; // @synthesize callState=_callState;
@property(nonatomic) __weak id <WACallViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) WACallView *callView; // @synthesize callView=_callView;
@property(readonly, copy, nonatomic) NSString *calleeJID; // @synthesize calleeJID=_calleeJID;
@property(readonly, nonatomic, getter=isChangingMinimizedState) _Bool changingMinimizedState; // @synthesize changingMinimizedState=_changingMinimizedState;
@property(readonly, nonatomic, getter=isMinimized) _Bool minimized; // @synthesize minimized=_minimized;
//- (void).cxx_destruct;
- (void)windowDidBecomeKey:(id)arg1;
- (void)proximityStateDidChange:(id)arg1;
- (void)stopMonitoringProximity;
- (void)startMonitoringProximityIfNeeded;
- (void)updateProximityMonitoring;
- (void)updatePushToTalkRecordTime;
- (void)sendAudioAtFilePath:(id)arg1 quotedMessage:(id)arg2 durationSeconds:(long long)arg3 streamingHash:(id)arg4 mediaKey:(id)arg5;
- (void)pttRecorder:(id)arg1 didFinishRecordingSuccessfully:(_Bool)arg2 filePath:(id)arg3;
- (void)pttRecorderWasInterrupted:(id)arg1;
- (void)pttRecorderDidFailToRecord:(id)arg1;
- (void)pttRecorderDidStartRecording:(id)arg1;
- (void)pttRecordWillStartRecording:(id)arg1;
@property(readonly, nonatomic, getter=isVoiceMessageScreenVisible) _Bool voiceMessageScreenVisible;
@property(readonly, nonatomic, getter=isCallRatingViewVisible) _Bool callRatingViewVisible;
- (void)dismissCallRatingScreen;
- (void)voiceCallRatingView:(id)arg1 didFinishWithAction:(unsigned long long)arg2;
- (_Bool)shouldShowRatingView;
@property(readonly, nonatomic, getter=isSpamReportViewVisible) _Bool spamReportViewVisible;
- (void)dismissSpamReportScreen;
- (void)callSpamReportView:(id)arg1 didFinishWithAction:(unsigned long long)arg2;
- (_Bool)shouldShowSpamReportView;
- (void)remindToCallWhenLeaving;
- (void)remindToCallInOneHour;
- (id)createReminder;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)becomeActiveFromView:(id)arg1;
- (void)minimizeWithAnimation:(_Bool)arg1;
- (void)openChatWithJID:(id)arg1 presentKeyboard:(_Bool)arg2;
- (void)rejectCallAndGoToChatView;
- (void)rejectCallAndSendMessageText:(id)arg1;
- (void)callActionViewDidRequestSendMessage:(id)arg1;
- (void)callActionViewDidRequestCancelAndSendMessage:(id)arg1;
- (void)callActionViewDidToggleSpeaker:(id)arg1;
- (void)callActionViewDidRequestSwitchCamera:(id)arg1;
- (_Bool)callActionView:(id)arg1 didRequestSetMute:(_Bool)arg2;
- (void)callActionViewDidRequestAcceptOrEndCall:(id)arg1;
- (void)callActionViewDidRequestCancelAndAddReminder:(id)arg1;
- (void)callActionViewDidRequestRejectCall:(id)arg1;
- (void)callActionViewDidEndPTTRecording:(id)arg1;
- (void)callActionViewDidBeginPTTRecording:(id)arg1;
- (void)callActionViewDidRequestCallBack:(id)arg1;
- (void)callActionViewDidCancelPTTRecording:(id)arg1 cancelledByUser:(_Bool)arg2;
- (double)callActionViewWillEndPTTRecording:(id)arg1;
- (void)callActionViewDidRequestCancelVoiceMail:(id)arg1;
- (_Bool)isChatScreenSupportedForCallActionView:(id)arg1;
- (id)snapshotOfPresentingViewForCallView:(id)arg1;
- (id)pttRecorder;
@property(readonly, nonatomic, getter=isVideoCall) _Bool videoCall;
- (void)rejectOrEndCall;
- (void)cancelOutgoingCall;
- (void)handleCallUnavailable;
- (void)handleCallBusy;
- (void)handleCallTimeout;
- (void)handleCallFailure;
- (void)handleCallRejectedByPeer;
- (void)handleCallTerminationByPeer;
- (void)reallyDismissWithDelayIfNeeded:(_Bool)arg1;
- (void)dismiss:(_Bool)arg1;
- (void)setCallState:(int)arg1 animated:(_Bool)arg2;
- (void)appWillResignActive:(id)arg1;
- (void)callStateDidBecomeActive:(id)arg1;
- (void)applicationDidChangeStatusBarFrame:(id)arg1;
- (void)printBatteryLevel;
- (void)loadLargeProfileImageAsync;
- (void)updateCallStateLabels;
- (void)timerFired:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (long long)preferredStatusBarStyle;
- (void)setBlurredImageFromView:(id)arg1;
- (void)updateSnapshot;
- (void)prepareToAnimateInFromView:(id)arg1;
- (id)uniqueIdentifier;
- (void)dealloc;
- (void)reinitWithCallState:(int)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithInitialCallState:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

