/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import "Viber-Structs.h"
//#import <XXUnknownSuperclass.h> // Unknown library

@class Conversation, NSURL, RACSignal, RACSubject, NSMutableSet, NSMutableArray;

@interface VIBAttachmentUploader : NSObject { // XXUnknownSuperclass {
@private
	NSURL* serverURL;
	NSMutableArray* activeDownloads;
	NSMutableArray* activeUploads;
	NSMutableArray* uploads;
	NSMutableArray* downloads;
	NSMutableArray* connections;
	NSMutableSet* _downloadsStartedByUser;
	Conversation* conversationWithHightPriority;
	RACSubject* _uploadingCompleteSignal;
	RACSubject* _uploadingProcessSignal;
}
@property(readonly, assign, nonatomic) RACSignal* uploadingProcessSignal;
@property(readonly, assign, nonatomic) RACSignal* uploadingCompleteSignal;
+(id)downloadAttachmentThumbnailWithAttachment:(id)attachment withPriority:(id)priority;
+(id)buildDownloadThumbnailURLForAttachment:(id)attachment;
+(id)downloadAttachmentThumbnailWithID:(id)anId path:(id)path downloadUrl:(id)url withPriority:(id)priority;
+(void)decreaseDownloadPriorityForAttachmentThumbnailWithContext:(id)context;
+(void)increaseDownloadPriorityForAttachmentThumbnailWithContext:(id)context;
+(void)downloadVibeAttachmentThumbnailWithMantleAttachment:(id)mantleAttachment;
+(void)downloadVibeAttachmentThumbnailWithAttachment:(id)attachment withPriority:(id)priority;
+(void)downloadVibeAttachmentThumbnailWithAttachment:(id)attachment;
+(id)buildURLForVibeDownloadID:(id)vibeDownloadID fileType:(id)type imageSize:(id)size;
+(id)sharedVIBAttachmentUploader;
//-(void).cxx_destruct;
-(void)conversationWillBeDeleted:(id)conversation;
-(void)downloadConnectionDidFinishLoadingWithAttachment:(id)downloadConnection;
-(id)fileTypeForAttachmentType:(id)attachmentType;
-(id)animationWebPageRequestForAttachment:(id)attachment;
-(id)animationInformationRequestForAttachment:(id)attachment;
-(id)downloadRequestForAttachment:(id)attachment;
-(void)resetDownloadStartedByUserFlagForAttachment:(id)attachment;
-(void)downloadAttachment:(id)attachment startedByUser:(BOOL)user;
-(BOOL)isAlreadyDownloading:(id)downloading;
-(id)downloadConnectionWithRequest:(id)request attachment:(id)attachment;
-(void)requestWebPageForAnimatedMessage:(id)animatedMessage completionHandler:(id)handler;
-(void)requestInfoForForAttachment:(id)attachment completionHandler:(id)handler;
-(void)urlConnectionWithRequest:(id)request withSizeCheck:(BOOL)sizeCheck completionHandler:(id)handler;
-(void)uploadConnectionDidFinishLoadingWithAttachment:(id)uploadConnection;
-(void)uploadConnectionWithAttachment:(id)attachment didReceiveData:(id)data;
-(void)connection:(id)connection didSendBodyData:(int)data totalBytesWritten:(int)written totalBytesExpectedToWrite:(int)write;
-(id)uploadThumbnailWithRequest:(id)request attachment:(id)attachment;
-(void)uploadThumbnailForVibeAttachment:(id)vibeAttachment;
-(void)sendUploadRequestWithAttachment:(id)attachment;
-(void)uploadAttachment:(id)attachment;
-(BOOL)isAlreadyUploading:(id)uploading;
-(id)uploadConnectionWithRequest:(id)request attachment:(id)attachment;
-(void)cancelUpload:(id)upload;
-(void)removeDownloadConnectionWithAttachment:(id)attachment;
-(void)removeUploadConnectionWithAttachment:(id)attachment;
-(void)removeConnectionWithAttachment:(id)attachment;
-(void)connectionFinishedWithAttachment:(id)attachment;
-(void)markAsIncompleteUpLoadingOrIsOkAttachment:(id)attachment;
-(void)markAsIncompleteDownLoadingAttachment:(id)attachment;
-(BOOL)isDownloadStartedByUserForAttachment:(id)attachment;
-(void)compressAndResizePictureAttachment:(id)attachment;
-(void)compressVideoAttachment:(id)attachment;
-(void)sortDownloadByPriority;
-(void)setConversationWithHightPriority:(id)hightPriority;
-(void)isOkUpload:(id)upload;
-(id)isOkConnectionWithRequest:(id)request attachment:(id)attachment;
-(void)beginLoading:(id)loading;
-(void)endBackgroundTask:(id)task;
-(void)beginBackgroundTask:(id)task;
-(id)animatedMessageURLForScript:(id)script messageInformation:(id)information;
-(id)attachmentURLForVibeScript:(id)vibeScript;
-(id)attachmentURLForScript:(id)script;
-(void)dealloc;
-(id)init;
-(id)getHeaderName:(id)name;
-(id)copyWithZone:(NSZone*)zone;
@end

