/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "UIViewController.h"

@interface PHCallViewController : UIViewController
{
    BOOL _didSilenceIncomingCall;
    BOOL _wantsApplicationDismissalStyle;
//    id <PHInCallRootViewControllerProtocol> _inCallRootViewController;
}

@property BOOL wantsApplicationDismissalStyle; // @synthesize wantsApplicationDismissalStyle=_wantsApplicationDismissalStyle;
@property BOOL didSilenceIncomingCall; // @synthesize didSilenceIncomingCall=_didSilenceIncomingCall;
//@property(nonatomic) __weak id <PHInCallRootViewControllerProtocol> inCallRootViewController; // @synthesize inCallRootViewController=_inCallRootViewController;
//- (void).cxx_destruct;
- (void)showFailureAlertIfNecessaryForCall:(id)arg1;
- (void)releaseDismissalAssertionIfNeeded;
- (void)obtainDismissalAssertionIfNeeded;
- (id)dismissalAssertionReason;
- (BOOL)needsDismissalAssertion;
- (float)_yOffsetForLoweredButtons;
- (float)_bottomMarginForBottomBar;
- (BOOL)shouldShowActionTypeSendToVoicemail;
- (void)showErrorAlertWithTitle:(id)arg1 message:(id)arg2 alternateButton:(id)arg3 alternateButtonURL:(id)arg4;
- (void)showErrorAlertWithTitle:(id)arg1 message:(id)arg2 alternateButton:(id)arg3 alternateButtonURL:(id)arg4 otherButton:(id)arg5 otherButtonURL:(id)arg6;
- (void)showErrorAlertWithTitle:(id)arg1 message:(id)arg2;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)setStatusBarHidden:(BOOL)arg1 withDuration:(double)arg2;
- (void)autoAnswer;
- (void)cancelAutoAnswer;
- (void)setupAutoAnswer;
- (BOOL)_shouldAutoAnswer;
- (BOOL)canCreateReminder;
- (BOOL)canSendMessage;
- (int)desiredButtonEvents;
- (BOOL)allowsBanners;
- (BOOL)allowsOtherAlertsToStackOnTop;
- (BOOL)allowsMenuButtonDismissal;

@end

