/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "FlickrViewController.h"
//
//#import "CreateAccountViewControllerDelegate-Protocol.h"
//#import "FacebookAccessTokenStatusDelegate-Protocol.h"
//#import "FlickrForgetPasswordDelegate-Protocol.h"
//#import "FlickrGetAPIDelegate-Protocol.h"
//#import "FlickrPostAPIDelegate-Protocol.h"
//#import "RTLabelDelegate-Protocol.h"
//#import "SignUpUserProfileViewControllerDelegate-Protocol.h"
//#import "UIAlertViewDelegate-Protocol.h"
//#import "UIGestureRecognizerDelegate-Protocol.h"
//#import "UITextFieldDelegate-Protocol.h"
//#import "YahooCaptchaViewControllerDelegate-Protocol.h"

@class FacebookSignInUpHandler, FlickrAPICheckYID, FlickrAPIGetYID, GoogleSignInHandler, NSString, NativeConnectDelegate, NativeSignInDelegate, RrichContentLabel, UIButton, UIImageView, UILabel, UITextField, UIView;

@interface SignInPageNewUIController //: FlickrViewController <FlickrForgetPasswordDelegate, UIAlertViewDelegate, UITextFieldDelegate, UIGestureRecognizerDelegate, YahooCaptchaViewControllerDelegate, RTLabelDelegate, FlickrGetAPIDelegate, FlickrPostAPIDelegate, CreateAccountViewControllerDelegate, SignUpUserProfileViewControllerDelegate, FacebookAccessTokenStatusDelegate>
{
    //NativeSignInDelegate *signInDelegate_;
    BOOL bSignInAction_;
    BOOL bAnimationHasDismissed_;
    BOOL bKeyboardshow_;
    int passInputCound_;
    int signinMethod_;
    //FacebookSignInUpHandler *fbSignInUpHandler_;
    //GoogleSignInHandler *_googleSigninUpHandler;
    //FlickrAPICheckYID *_yahooIDCheckAPI;
    int _nativeSigninState;
    //FlickrAPIGetYID *_getYIDAPI;
    NSString *_yahooID;
    UIButton *signInBtn;
    UIButton *cancelBtn;
    //RrichContentLabel *signUpLabel;
    //RrichContentLabel *forgetLabel;
    UIButton *fbButton;
    UIButton *gButton;
    UIImageView *fbImgView;
    UIImageView *gImageView;
    UIImageView *logoView;
    UITextField *userIDTxt;
    UITextField *passTxt;
    UIView *loginBackgroundView;
    UIButton *fbSigninButton;
    UIButton *googleSigninButton;
    //NSDictionary<FBGraphUser> *fbUser;
    UILabel *orSigninLabel;
    UIImageView *leftSpeLine;
    UIImageView *rightSpeLine;
    //id <SignInFinishedDelegate> mSignInFinishDelegate;
    NSString *mUserName;
    UIButton *_signUpBtn;
    UILabel *_yahooIDLabel;
    UILabel *_pswordIDLabel;
    //NSDictionary<FBGraphUser> *_fbUserInfo;
    //NativeConnectDelegate *_connectDelegate;
}

//@property(retain, nonatomic) NativeConnectDelegate *connectDelegate; // @synthesize connectDelegate=_connectDelegate;
//@property(retain, nonatomic) NSDictionary<FBGraphUser> *fbUserInfo; // @synthesize fbUserInfo=_fbUserInfo;
@property(retain, nonatomic) UILabel *pswordIDLabel; // @synthesize pswordIDLabel=_pswordIDLabel;
@property(retain, nonatomic) UILabel *yahooIDLabel; // @synthesize yahooIDLabel=_yahooIDLabel;
@property(retain, nonatomic) UIButton *signUpBtn; // @synthesize signUpBtn=_signUpBtn;
@property(copy, nonatomic) NSString *mUserName; // @synthesize mUserName;
//@property(nonatomic) id <SignInFinishedDelegate> mSignInFinishDelegate; // @synthesize mSignInFinishDelegate;
//@property(retain, nonatomic) NativeSignInDelegate *mSignInDelegate; // @synthesize mSignInDelegate=signInDelegate_;
@property(retain, nonatomic) UIImageView *rightSpeLine; // @synthesize rightSpeLine;
@property(retain, nonatomic) UIImageView *leftSpeLine; // @synthesize leftSpeLine;
@property(retain, nonatomic) UILabel *orSigninLabel; // @synthesize orSigninLabel;
//@property(retain, nonatomic) NSDictionary<FBGraphUser> *fbUser; // @synthesize fbUser;
@property(retain, nonatomic) UIButton *googleSigninButton; // @synthesize googleSigninButton;
@property(retain, nonatomic) UIButton *fbSigninButton; // @synthesize fbSigninButton;
@property(retain, nonatomic) UIView *loginBackgroundView; // @synthesize loginBackgroundView;
@property(retain, nonatomic) UITextField *passTxt; // @synthesize passTxt;
@property(retain, nonatomic) UITextField *userIDTxt; // @synthesize userIDTxt;
@property(retain, nonatomic) UIImageView *logoView; // @synthesize logoView;
@property(retain, nonatomic) UIImageView *gImageView; // @synthesize gImageView;
@property(retain, nonatomic) UIImageView *fbImgView; // @synthesize fbImgView;
@property(retain, nonatomic) UIButton *gButton; // @synthesize gButton;
@property(retain, nonatomic) UIButton *fbButton; // @synthesize fbButton;
//@property(retain, nonatomic) RrichContentLabel *forgetLabel; // @synthesize forgetLabel;
//@property(retain, nonatomic) RrichContentLabel *signUpLabel; // @synthesize signUpLabel;
@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn;
@property(retain, nonatomic) UIButton *signInBtn; // @synthesize signInBtn;
//- (void).cxx_destruct;
- (void)signUpUserProfileViewControllerFinish:(id)arg1;
- (void)createAccount:(id)arg1 finishedWithYCookie:(id)arg2 andTCookie:(id)arg3;
- (void)flickrGetAPI:(id)arg1 didFailedWithError:(id)arg2;
- (void)flickrGetAPI:(id)arg1 didFetchedData:(id)arg2;
- (void)adjustControlPos;
- (void)handleFBTokenFail;
- (void)enableUserInteraction;
- (void)disableUserInteraction;
- (void)enterFBBindingPageUsingFBUser:(id)arg1;
- (void)skipGoogleBind:(id)arg1;
- (void)skipFBBind;
- (void)enterGoogleBindingPage:(id)arg1;
- (void)openGoogleCreateAccountViewController:(id)arg1;
- (void)handleGoogleSignInUpAction:(id)arg1;
- (void)handleGoogleSignInUp:(id)arg1 andError:(id)arg2;
- (void)handleFBSignInUpAction:(id)arg1;
- (void)finishedQueryStatusWithResults:(id)arg1;
- (void)handleFBSignInUp:(id)arg1 andError:(id)arg2;
- (void)fireAnimation;
- (void)rtLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (void)finishedUnBindProcessWithYCookie:(id)arg1 andTCookie:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (BOOL)textFieldShouldClear:(id)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (id)getDataToSignIn;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)popCAPTCHAMessage:(id)arg1 withTitle:(id)arg2;
- (id)popSimpleErrorMessage:(id)arg1 withTitle:(id)arg2;
- (void)tryAgainErrorMessage:(id)arg1 withTitle:(id)arg2 clicked:(id)arg3;
- (void)keyboardDidShow:(id)arg1;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShown:(id)arg1;
- (void)handleSignInReturnCode:(id)arg1;
- (void)handleCreateAccountReturnCode:(id)arg1;
- (void)handlereturnCodeForOpenID:(id)arg1;
- (void)hideKeyboard:(id)arg1;
- (void)forgetPassword;
- (void)doneForgetPassword:(id)arg1;
- (void)actionGoogleSignIn:(id)arg1;
- (void)actionFacebookSignIn:(id)arg1;
- (void)actionSignIn:(id)arg1;
- (void)actionCreateAccount:(id)arg1;
- (void)nativeSignInUsingUsername:(id)arg1 password:(id)arg2;
- (void)cancelSignIn:(id)arg1;
- (void)getYIDUsingScreenName:(id)arg1;
- (void)forceResignActive:(id)arg1;
- (void)viewDidUnload;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;

@end

