//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

//#import "QLPreviewItem.h"

@class NSData, NSDictionary, NSString, NSURL;
/*
@interface CKMediaObject : NSObject <QLPreviewItem>
{
    id <CKFileTransfer> _transfer;
}*/
@interface CKMediaObject (iOS8)
+ (id)attachmentSummary:(unsigned int)arg1;
+ (id)fallbackFilenamePrefix;
+ (id)UTITypes;
+ (Class)__ck_attachmentItemClass;
+ (id)iconCache;
+ (BOOL)isPreviewable;
//@property(retain, nonatomic) id <CKFileTransfer> transfer; // @synthesize transfer=_transfer;
@property(readonly) NSURL *previewItemURL;
@property(readonly, nonatomic) int mediaType;
- (id)pasteboardItem;
@property(readonly, copy, nonatomic) NSString *UTIType;
@property(readonly, copy, nonatomic) NSString *mimeType;
@property(readonly, copy, nonatomic) NSDictionary *transcoderUserInfo;
@property(readonly, copy, nonatomic) NSString *filename;
@property(readonly, copy, nonatomic) NSURL *fileURL;
@property(readonly, copy, nonatomic) NSData *data;
@property(readonly, copy, nonatomic) NSString *transferGUID;
- (id)initWithTransfer:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)composeImages;
- (id)JPEGDataFromImage:(id)arg1;
- (id)fileManager;
- (id)previewDispatchCache;
- (id)generateThumbnailFillToSize:(struct CGSize)arg1 contentAlignmentInsets:(struct UIEdgeInsets)arg2;
- (id)generateThumbnailForWidth:(float)arg1 orientation:(BOOL)arg2;
- (struct CGSize)bbSize;
- (id)bbPreviewFillToSize:(struct CGSize)arg1;
- (id)savedPreviewFromURL:(id)arg1 forOrientation:(BOOL)arg2;
- (void)savePreview:(id)arg1 toURL:(id)arg2 forOrientation:(BOOL)arg3;
- (id)generatePreviewFromThumbnail:(id)arg1 width:(float)arg2 orientation:(BOOL)arg3;
- (void)_sampleImageEdges:(id)arg1 usingRect:(struct CGRect)arg2 forMostlyWhitePixels:(unsigned int *)arg3 otherPixels:(unsigned int *)arg4;
- (id)previewForWidth:(float)arg1 orientation:(BOOL)arg2;
- (id)fileSizeString;
- (id)downloadProgressString;
- (id)downloadProgressImage;
- (BOOL)shouldShowDisclosure;
- (id)previewCachesFileURLWithOrientation:(BOOL)arg1 extension:(id)arg2;
- (id)previewCacheKeyWithOrientation:(BOOL)arg1;
- (BOOL)canBeAttachmentContiguous;
- (void)export:(id)arg1;
- (BOOL)canExport;
- (BOOL)shouldBeQuickLooked;
- (BOOL)shouldShowViewer;
- (id)location;
- (id)icon;
- (id)subtitle;
- (id)title;
- (Class)previewBalloonViewClass;
- (Class)coloredBalloonViewClass;
- (Class)balloonViewClassForWidth:(float)arg1 orientation:(BOOL)arg2;
- (BOOL)isPreviewable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) NSString *previewItemTitle;
@property(readonly) Class superclass;

@end
