/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

//#import "UIView.h"
//
//#import "BBMAppointmentPickerDelegate-Protocol.h"
//#import "BBMContactPickerDelegate-Protocol.h"
//#import "BBMLocationPickerDelegate-Protocol.h"

@class BBMContactPickerViewController, BBMQuickActionAndTextInput, BBMQuickActionCameraHelper, NSString, UIViewController;

@interface BBMQuickActionAttachmentView : UIView //<BBMContactPickerDelegate, BBMAppointmentPickerDelegate, BBMLocationPickerDelegate>
{
    UIView *_view;
    NSString *_conversationURI;
    BBMQuickActionAndTextInput *_quickActionBar;
    UIViewController *_parentVC;
    BBMQuickActionCameraHelper *_cameraHelper;
    BBMContactPickerViewController *_contactPicker;
}

@property(retain, nonatomic) BBMContactPickerViewController *contactPicker; // @synthesize contactPicker=_contactPicker;
@property(retain, nonatomic) BBMQuickActionCameraHelper *cameraHelper; // @synthesize cameraHelper=_cameraHelper;
//@property(nonatomic) __weak UIViewController *parentVC; // @synthesize parentVC=_parentVC;
@property(retain, nonatomic) BBMQuickActionAndTextInput *quickActionBar; // @synthesize quickActionBar=_quickActionBar;
@property(retain, nonatomic) NSString *conversationURI; // @synthesize conversationURI=_conversationURI;
//@property(nonatomic) __weak UIView *view; // @synthesize view=_view;
//- (void).cxx_destruct;
- (void)didPickRecentLocation:(id)arg1;
- (void)didPickLocationWithLocationInfo:(id)arg1;
- (void)didPickAppointment:(id)arg1;
- (void)pickedCommonContact:(id)arg1;
- (void)contactsSelected:(id)arg1 fromPickerWithID:(int)arg2;
- (void)btnQuickAttachContact:(id)arg1;
- (void)btnQuickAttachAppointment:(id)arg1;
- (void)btnQuickAttachLocation:(id)arg1;
- (void)btnQuickAttachDropbox:(id)arg1;
- (void)btnQuickAttachPicture:(id)arg1;
- (void)updateAttachmentOptions;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

