/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "BBMGenStickerPack.h"

@class NSMutableArray;

@interface BBMStickerPack : BBMGenStickerPack
{
    NSMutableArray *_stickers;
}

@property(retain, nonatomic) NSMutableArray *stickers; // @synthesize stickers=_stickers;
//- (void).cxx_destruct;
- (BOOL)stickersLoaded;

@end

