//************************************************************
//This file is auto-generated by the SecurityTool v1.0. 
//************************************************************


#import <Foundation/Foundation.h>

@interface  KDMWhiteHouse : NSObject // KeyDataManager
{

}

- (id)gkdffai0:(int)fileIndex; // Fake
- (id)gkdffai1:(int)fileIndex; // Fake
- (id)gkdffai2:(int)fileIndex; // getKeyDataForFileAtIndex:
- (id)gkdffai3:(int)fileIndex; // Fake
- (id)gkdffai4:(int)fileIndex; // Fake
- (id)gkdffai5:(int)fileIndex; // Fake

@end