//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  4 2016 10:44:45).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSData, NSDictionary, NSNumber, NSString, NSURL, NSURLRequest;

@interface NLObjectStorageOperationParameters : NSObject
{
    unsigned long long _fileSize;
    _Bool _isContentEncrypted;
    _Bool _isBackgroundOpReqeust;
    _Bool _saveRequestType;
    long long operationType;
    NSString *hostName;
    long long port;
    NSString *_serviceCode;
    NSString *spaceID;
    NSString *objectID;
    NSString *thumbID;
    long long mediaType;
    NSString *_objectName;
    NSString *userID;
    NSString *_languageCode;
    NSString *accessToken;
    NSString *filePath;
    NSData *fileData;
    NSURL *downloadURL;
    unsigned long long offset;
    NSString *sourceOBSPathForCopy;
    NSString *postID;
    NSString *reqSeq;
    NSString *tomid;
    NSString *_audlen;
    NSString *_obsPopInfo;
    NSString *_sourceAccessTokenHeaderNameForCopy;
    NSString *_sourceAccessTokenForCopy;
    NSString *_quality;
    NSString *_requestImageSize;
    NSString *_groupID;
    NSString *_albumID;
    NSString *_userAgentString;
    double _timeOutSeconds;
    long long _numberOfTimesToRetryOnTimeout;
    NSString *_scenetime;
    NSString *_lineMID;
    NSString *_keepContentID;
    NSString *_category;
    NSNumber *_shouldAttemptPersistentConnection;
    NSURLRequest *_URLRequest;
    NSString *_serializerGroup;
    long long _priority;
    long long _forcedOpRequestType;
    NSData *_downloadResumeData;
    NSDictionary *_customRequestHeaderDictionary;
    NSDictionary *_postValueAndKeys;
    NSString *_obsAccessToken;
}

@property(retain, nonatomic) NSString *obsAccessToken; // @synthesize obsAccessToken=_obsAccessToken;
@property(retain, nonatomic) NSDictionary *postValueAndKeys; // @synthesize postValueAndKeys=_postValueAndKeys;
@property(retain, nonatomic) NSDictionary *customRequestHeaderDictionary; // @synthesize customRequestHeaderDictionary=_customRequestHeaderDictionary;
@property(nonatomic) _Bool saveRequestType; // @synthesize saveRequestType=_saveRequestType;
@property(retain, nonatomic) NSData *downloadResumeData; // @synthesize downloadResumeData=_downloadResumeData;
@property(nonatomic) _Bool isBackgroundOpReqeust; // @synthesize isBackgroundOpReqeust=_isBackgroundOpReqeust;
@property(nonatomic) _Bool isContentEncrypted; // @synthesize isContentEncrypted=_isContentEncrypted;
@property(nonatomic) long long forcedOpRequestType; // @synthesize forcedOpRequestType=_forcedOpRequestType;
@property(nonatomic) long long priority; // @synthesize priority=_priority;
@property(retain, nonatomic) NSString *serializerGroup; // @synthesize serializerGroup=_serializerGroup;
@property(retain, nonatomic) NSURLRequest *URLRequest; // @synthesize URLRequest=_URLRequest;
@property(retain, nonatomic) NSNumber *shouldAttemptPersistentConnection; // @synthesize shouldAttemptPersistentConnection=_shouldAttemptPersistentConnection;
@property(retain, nonatomic) NSString *category; // @synthesize category=_category;
@property(retain, nonatomic) NSString *keepContentID; // @synthesize keepContentID=_keepContentID;
@property(retain, nonatomic) NSString *lineMID; // @synthesize lineMID=_lineMID;
@property(retain, nonatomic) NSString *scenetime; // @synthesize scenetime=_scenetime;
@property(nonatomic) long long numberOfTimesToRetryOnTimeout; // @synthesize numberOfTimesToRetryOnTimeout=_numberOfTimesToRetryOnTimeout;
@property(nonatomic) double timeOutSeconds; // @synthesize timeOutSeconds=_timeOutSeconds;
@property(retain, nonatomic) NSString *userAgentString; // @synthesize userAgentString=_userAgentString;
@property(retain, nonatomic) NSString *albumID; // @synthesize albumID=_albumID;
@property(retain, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
@property(retain, nonatomic) NSString *requestImageSize; // @synthesize requestImageSize=_requestImageSize;
@property(retain, nonatomic) NSString *quality; // @synthesize quality=_quality;
@property(retain, nonatomic) NSString *sourceAccessTokenForCopy; // @synthesize sourceAccessTokenForCopy=_sourceAccessTokenForCopy;
@property(retain, nonatomic) NSString *sourceAccessTokenHeaderNameForCopy; // @synthesize sourceAccessTokenHeaderNameForCopy=_sourceAccessTokenHeaderNameForCopy;
@property(retain, nonatomic) NSString *obsPopInfo; // @synthesize obsPopInfo=_obsPopInfo;
@property(retain, nonatomic) NSString *audlen; // @synthesize audlen=_audlen;
@property(retain, nonatomic) NSString *tomid; // @synthesize tomid;
@property(retain, nonatomic) NSString *reqSeq; // @synthesize reqSeq;
@property(retain, nonatomic) NSString *postID; // @synthesize postID;
@property(retain, nonatomic) NSString *sourceOBSPathForCopy; // @synthesize sourceOBSPathForCopy;
@property(nonatomic) unsigned long long offset; // @synthesize offset;
@property(retain, nonatomic) NSURL *downloadURL; // @synthesize downloadURL;
@property(retain, nonatomic) NSData *fileData; // @synthesize fileData;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath;
@property(retain, nonatomic) NSString *accessToken; // @synthesize accessToken;
@property(retain, nonatomic) NSString *languageCode; // @synthesize languageCode=_languageCode;
@property(retain, nonatomic) NSString *userID; // @synthesize userID;
@property(retain, nonatomic) NSString *objectName; // @synthesize objectName=_objectName;
@property(nonatomic) long long mediaType; // @synthesize mediaType;
@property(retain, nonatomic) NSString *thumbID; // @synthesize thumbID;
@property(retain, nonatomic) NSString *objectID; // @synthesize objectID;
@property(retain, nonatomic) NSString *spaceID; // @synthesize spaceID;
@property(retain, nonatomic) NSString *serviceCode; // @synthesize serviceCode=_serviceCode;
@property(nonatomic) long long port; // @synthesize port;
@property(retain, nonatomic) NSString *hostName; // @synthesize hostName;
@property(nonatomic) long long operationType; // @synthesize operationType;

- (id)description;
- (id)convertToDictionary;
- (id)objectTypeFromMediaType;
@property(readonly, nonatomic) unsigned long long fileSize;
- (id)requestKey;

@end

